### ISSUE TITLE
Decomposition of app 

### ISSUE THREAD

**Issue by gugakatsi** [project-travel-mate/Travel-Mate#10]
currently app architecture is pretty much is mixed up , we could  decompose it nicely , also there is many repeated code as you know , so i think it is good idea , i would work on those issues.

**Comment by Swati4star** [comment]
@gugakatsi Elaborate it properly, like what parts of app would you like to decompose?

**Comment by gugakatsi** [comment]
i'll do in few days too

**Comment by gugakatsi** [comment]
@Swati4star finally me exams are over and i'll start working on this and also on retrofit, about decomposition i'll start with basics like packaing them , mergin adapters from activity code  and etc, models, buss. logic.

**Comment by Swati4star** [comment]
@gugakatsi Sure, Go ahead with this.

**Comment by Swati4star** [comment]
@gugakatsi Any updates?

**Comment by gugakatsi** [comment]
@Swati4star i'll let u know tomorrow morning or earlier , i can't write down everything right now

**Comment by gugakatsi** [comment]
@Swati4star  sorry for delay i will notify you as fast as i can

**Comment by gugakatsi** [comment]
@Swati4star so here i am :D again ,  so i though about that and reviewed code couple of times , i guess it could be a nice idea to refactor to mvp and package by layers , it would really make app overally pretty clear and scalable. what do you think about that.

**Comment by Swati4star** [comment]
Sure, we can surely do this. But then we need to discuss clearly upon this first. We can start with modules at a time.
Let me create a doc of all the features that are there in Travel Mate. Then, we can work on which module to start with the decomposition. Sounds good?

**Comment by Swati4star** [comment]
One of the things you can start with is working on https://github.com/Swati4star/Travel-Mate/issues/9

**Comment by gugakatsi** [comment]
yeap, that's actually is a great idea.

**Comment by Swati4star** [comment]
Look at this file [Features.md](https://github.com/Swati4star/Travel-Mate/blob/swati/Features.md)

**Comment by wesk0** [comment]
Hi there,

Is there any way i can help with the project ?

**Comment by Swati4star** [comment]
@wesk0 You can work on changing from okhttp to retrofit https://github.com/Swati4star/Travel-Mate/issues/9

If you want to go ahead with this, we can discuss upon this further.

**Comment by gugakatsi** [comment]
@Swati4star i checked it , so i can start working on it alone or we can split up , let me know what we gonna do about that.

**Comment by Swati4star** [comment]
Why don't you take up one module at a time. Let me know what module are you gonna start with?
Start with Signup/Login first. Sounds fine?

**Comment by gugakatsi** [comment]
Sounds fine , i will start it with alongside #9 , and will commit step by step by modules . should we use dagger or anything else?

**Comment by Swati4star** [comment]
Do we need to use daggers? Not sure about these.

For #9 also, go module by module only.

**Comment by gugakatsi** [comment]
@wesk0 let me know if you gonna work on issue , we could split it up in many different ways.

**Comment by wesk0** [comment]
@swati, I'm not sure if I can make it.

**Comment by Swati4star** [comment]
@gugakatsi You are starting with Signup/Login, or some other module?

**Comment by gugakatsi** [comment]
@Swati4star Signup/Login with alongside #9 issue , but i'll do step by step as you mentioned.

**Comment by gugakatsi** [comment]
@Swati4star  i have not changed anything else , ( i mean okhttp call stuff etc ... ) but here is an error : 

https://gist.github.com/gugakatsi/62193131ba196a22bc805d3f37e42e4d

**Comment by Swati4star** [comment]
@gugakatsi The domain name has expired. We are looking into this.

**Comment by gugakatsi** [comment]
@Swati4star ah okay , than i'll pull request in a minutes.

**Comment by Niranjan-B** [comment]
Hi @Swati4star, I would like to contribute to the modularization of app as well. I can see that gugakatsi has raised a PR for login module. I would like to start off with Destinations feature if no one is already working on it. What do you say?

**Comment by gugakatsi** [comment]
@Niranjan-B checkout pull request alongside with comment.

**Comment by Niranjan-B** [comment]
@gugakatsi yup, did see your PR and comment

**Comment by gugakatsi** [comment]
@Niranjan-B so start working on any module  , after refactoring in that style , we'll refactor okhttp -> retro/rx

**Comment by Niranjan-B** [comment]
@gugakatsi yes, I mentioned which module I wanted to work on in my previous comment. Refactoring to Retrofit/RX post modularization sounds good.

**Comment by Niranjan-B** [comment]
@Swati4star, I would continue to work on FunFacts sub-module. However, there seems to be something wrong with the city-info request (http://csinsit.org/prabhakar/tie/city/info.php?id=1). It returns a 502. I can raise a new issue if you want me to.

**Comment by Swati4star** [comment]
Hi @Niranjan-B , I and prabhakar are currently working on setting up the server. You can continue to work on cleaning up the Android part. We will fix it soon.

**Comment by apoorv9990** [comment]
Hi,

I came across this thread while looking for open source projects to contribute and I would suggest including Dagger 2 for dependency as well since you are moving to MVP architecture. Dagger 2 can be used to inject the Retrofit class directly into the presenter where it is needed. As a result, the OkHttpClient and Retrofit objects can be injected from one class removing the need to instantiate them in each of the presenters.

**Comment by Niranjan-B** [comment]
Yes, Dagger-2 is definitely on the plate. How about refactoring to MVP first and then Dagger-2? Codebase will get messed up since MVP modularization is in progress IMHO. Suggestions @Swati4star ?

**Comment by gugakatsi** [comment]
@Niranjan-B @apoorv9990 i already mentioned that , after refactor to mvp , we could start injecting <3 :D

**Comment by rahul-953** [comment]
Hi, I am new to open source and I want to contribute to this. How can I contribute to this project?

**Comment by gugakatsi** [comment]
@rahul-953 take a any module and start refactoring to mvp , but first review pr , or if u see another issue here just mention and start working on it

**Comment by Swati4star** [comment]
We would be putting this issue on hold until https://github.com/Swati4star/Travel-Mate/issues/24 is fixed.

**Comment by Swati4star** [comment]
This issue seems to be a big one. I will be breaking into multiple units and create multiple issues for different modules.

**Comment by gugakatsi** [comment]
we could make todolist by modules - [ ]  etc..

**Comment by Swati4star** [comment]
The modules have been moved to separate packages in 0e84ab188bff8cae7e290eefc076c96054ce7d18
