### ISSUE TITLE
Add Google Sign in , in the Login Screen

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#105]
A Google sign in button would make the UX so much smoother for a new user to login fast.

**Comment by Swati4star** [comment]
We need server side integration also for this issue.

**Comment by knightcube** [comment]
Yup, since this is android based i think we can keep the issue open until the backend code gets updated

**Comment by Swati4star** [comment]
Sure. I'll create a similar issue for server repo for Facebook & Google logins.

**Comment by Swati4star** [comment]
We won't be adding this to our application.
