### ISSUE TITLE
Show user name of Logged in user in Navigation Drawer

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#107]
The navigation drawer should show the name and the email of the Logged in user

**Comment by adi44** [comment]
I would like to try

**Comment by Swati4star** [comment]
Sure. Go ahead 👍

**Comment by Swati4star** [comment]
@adi44 Are you working on this issue?

**Comment by Swati4star** [comment]
@adi44 You asked to take up this issue 3 days ago. This is a really simple issue, shouldn't have taken more than a day.
I am marking it as up-for-grabs again.

**Comment by amy6** [comment]
I'd like to take this up.
