### ISSUE TITLE
Add Issues and Pull Request templates to the project

### ISSUE THREAD

**Issue by brijeshshah13** [project-travel-mate/Travel-Mate#109]
**Actual Behavior**

Currently neither Issues nor PR template exist for the project.

**Expected Behavior**

Create Issues and PR templates.

**Steps to reproduce it**

Create an issue or PR.

**Would you like to work on the issue?**

Yes.

**Comment by Swati4star** [comment]
Fixed by 934f85849cea88d278d838a6bfd9e9dff6edb402
Thanks for the suggestion 👍
