### ISSUE TITLE
Remove extra Signup/Login option from Signup/Login screen

### ISSUE THREAD

**Issue by brijeshshah13** [project-travel-mate/Travel-Mate#114]
Currently, `Signup` and `Login` options are provided in the respective `Signup` and `Login` screens even though the user is currently on that screen. This doesn't makes sense.

### Steps to reproduce
Land on the Signup or Login screen.

### Expected behaviour
On the `Signup` screen, only the Login option should be provided and likewise for the `Login` screen.

### Actual behaviour
Both options are provided no matter the screen.

### Would you like to work on the issue?
Yes.

**Comment by Swati4star** [comment]
This doesn't seem to be a valid issue. This is by design. A lot of apps do have this only.

**Comment by brijeshshah13** [comment]
@Swati4star When on the Signup screen, please click on the `Signup` button. It doesn't has any use there as the user is already on the Signup screen. Similarly for the Login screen. Doesn't this seem to be a valid issue?

**Comment by brijeshshah13** [comment]
@Swati4star Any final decision on this issue?

**Comment by Swati4star** [comment]
Hold on to this one. Let me search for some other UI for this.
I am thinking : 
For login screen, we can have something like, "Not registered yet? Cretae new account". Make create new account a button, which takes you to sign up screen.
For sign up Screen, we can have "Already a member? Login". Make login a button here.

Any take on this UI?

**Comment by brijeshshah13** [comment]
@Swati4star I agree with the your idea. We need to just change the text to the one you mentioned.

**Comment by Swati4star** [comment]
You can implement this issue & share the screenshot here. We'll decide on it then.

**Comment by brijeshshah13** [comment]
Login page:

![screenshot_20180624-131419](https://user-images.githubusercontent.com/18366144/41817026-987febb2-77b0-11e8-84bd-54d9ba289deb.png)

Signup page:

![screenshot_20180624-131413](https://user-images.githubusercontent.com/18366144/41817029-a1138036-77b0-11e8-9ca1-6e73eb4942a7.png)

Changes have been done. Shall I send the PR of the same?

**Comment by Swati4star** [comment]
Correct the spelling of create. 
Can you underline the texts? It'll make them look like they are links.

**Comment by brijeshshah13** [comment]
Updated pics:

![screenshot_20180624-133047](https://user-images.githubusercontent.com/18366144/41817154-e98172ae-77b2-11e8-81d1-4a154eebb4df.png)

![screenshot_20180624-133053](https://user-images.githubusercontent.com/18366144/41817156-eae0a106-77b2-11e8-9997-c4981381be5b.png)

**Comment by Swati4star** [comment]
Looks good. You can open a PR for this now.

**Comment by Swati4star** [comment]
Fixed in https://github.com/project-travel-mate/Travel-Mate/pull/115 👍
