### ISSUE TITLE
[New Feature] Add contributors list

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#116]
- Add a new option in the navigation panel, `Contributors`
- It should contain a list of contributors as received from this API
https://github.com/project-travel-mate/server/issues/20

**Comment by brijeshshah13** [comment]
@Swati4star Please provide a sketch or sample UI of how the contributors are to be displayed.

**Comment by Swati4star** [comment]
I'll provide a UI by tonight. If you have something in mind, you can post it here.

**Comment by brijeshshah13** [comment]
@Swati4star Sure 👍

**Comment by brijeshshah13** [comment]
@Swati4star Btw, please assign this task to me. I will get started with it as soon as you provide the UI.

**Comment by Swati4star** [comment]
The API is also not ready yet. You won't be able to work on this issue before that.

**Comment by brijeshshah13** [comment]
@Swati4star I don't think we need to implement this in our back-end server as we can directly call the GitHub API for the same.

**Comment by Swati4star** [comment]
@brijeshshah13 We can have the UI like this : 
- On clicking the individual items, open up their github profile should open up
- On 'See More', show all the remaining contributors
- On the last item, when user clicks on the card, Open `project-travel-mate`  organization link.
- PS, the icon next to `Github` in the end is Octocat icon :octocat: 
![img_20180626_204814](https://user-images.githubusercontent.com/9164477/41922333-7873518c-7982-11e8-8fca-ca8fbfcf2c56.jpg)

**Comment by brijeshshah13** [comment]
@Swati4star Where in this will the number of contributions of each person is to be displayed?

**Comment by Swati4star** [comment]
By the right side of the name? Try out if that looks okay.

**Comment by Swati4star** [comment]
Waiting in this issue till the API for contributors is ready...

**Comment by brijeshshah13** [comment]
@Swati4star Please provide the details of the end-point.

**Comment by Swati4star** [comment]
@brijeshshah13 The plan now is to add this in the `About us` screen only (https://github.com/project-travel-mate/Travel-Mate/issues/252). 
So, we first need to add an About us. Then, create a new list item for contributors & then, this list should open up.

**Comment by brijeshshah13** [comment]
@Swati4star Picking up this one.

**Comment by Swati4star** [comment]
Updates @brijeshshah13 ?

**Comment by brijeshshah13** [comment]
@Swati4star Will work on #307 first.

**Comment by amoraitis** [comment]
The do have an [endpoint for contributors](https://developer.github.com/v3/repos/#list-contributors).

Also, I can work on it

**Comment by Swati4star** [comment]
We have our own API implemented for this too : https://github.com/project-travel-mate/server/blob/master/api/urls.py#L95
`get-contributors/<str:project>`


Sure, Go ahead 👍

**Comment by amoraitis** [comment]
@Swati4star I implemented a solution for this one.
It's not excactly what you designed, but i think its fine. 

Let me know, if you want something ele than this!

![img_20181004_124425](https://user-images.githubusercontent.com/17813786/46466328-a54b4300-c7d3-11e8-863e-ea039f30de43.jpg)

**Comment by Swati4star** [comment]
Just a few UI suggestions : 
- Make the images smaller (smaller radius). [Do check if 3 in a row looks good]
- what are the numbers in green border [I know it's number of commits, but we should write that]
- Make the github logo smaller (and use this one https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png )
- I hope, the user's profile opens up when we click on a card
- Make the `Android View` header's width `match parent`

**Comment by amoraitis** [comment]
> Just a few UI suggestions :
> 
> * Make the images smaller (smaller radius). [Do check if 3 in a row looks good]
    I reduced the size
> * what are the numbers in green border [I know it's number of commits, but we should write that]
    Added below
> * Make the github logo smaller (and use this one https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png )
    Done
> * I hope, the user's profile opens up when we click on a card
    Hahaaha of course!
> * Make the `Android View` header's width `match parent`
    Done
![screenshot_2018-10-04-13-50-00-685_io github project_travel_mate](https://user-images.githubusercontent.com/17813786/46469778-0aeffd00-c7dd-11e8-9227-a1dea7bb6708.png)

**Comment by Swati4star** [comment]
Looks good. You can create a PR for this. 👍
