### ISSUE TITLE
[New Feature] Add checklist widget to home screen

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#118]
We already have checklist utility in our application. Create a widget for the same.

Reference:
- https://developer.android.com/guide/topics/appwidgets/
- https://www.androidauthority.com/create-simple-android-widget-608975/

**Comment by santoshhiremani** [comment]
Any UI idea on it?

**Comment by Swati4star** [comment]
Similar to google keep. You can check this issue https://github.com/project-travel-mate/Travel-Mate/issues/300

**Comment by Swati4star** [comment]
Are you working on it @santoshhiremani ?

**Comment by santoshhiremani** [comment]
Yes, I'm working on it....

**Comment by santoshhiremani** [comment]
What need to show on widget...?

**Comment by Swati4star** [comment]
<img width="313" alt="screenshot 2018-09-09 at 6 03 47 pm" src="https://user-images.githubusercontent.com/9164477/45264483-c92c9a80-b45a-11e8-97cf-740f40b738bb.png">

Make it something like that in the screenshot. On clicking any item, just open the app & then checklist.
Instead of `Pinned`, show `Travel Mate. Ignore the `+` icon

**Comment by Swati4star** [comment]
Sure. You can use these. Just show a listview for the time being, we will see about adding the checkboxes later. @santoshhiremani
