### ISSUE TITLE
[New feature] User profile page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#121]
Create a profile icon on the top of naviagtion bar 
When user clicks on that, open up a new page `user-profile`
Show all the user details in that page.

**Comment by samyak8853** [comment]
i can do it

**Comment by Swati4star** [comment]
Sure

**Comment by samyak8853** [comment]
please give the time limit for it so i can manage my time.

**Comment by Swati4star** [comment]
You can submit it by this Tuesday.

**Comment by samyak8853** [comment]
I didn't read the technologies used here  and i know to profile page create by javascript, html ,css.So i unable to do it.

**Comment by Swati4star** [comment]
Well, you should atleast look at the project code & what the product is, before asking to take up the issue.

This issue is open to take-up for others now.

**Comment by syedjahangirpeeran** [comment]
Can you elaborate user details? like name and ??

**Comment by syedjahangirpeeran** [comment]
Can I start working on this @Swati4star ?

**Comment by Swati4star** [comment]
Yes. Sure 👍

**Comment by syedjahangirpeeran** [comment]
How to retrieve data from Shared preferences this code isn't working:
 ```
SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(this);
        String Email = preferences.getString("email", "Email ID");
        
```

**Comment by Swati4star** [comment]
See here : https://github.com/project-travel-mate/Travel-Mate/blob/master/Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java#L141

Change you code to get `USER_EMAIL`

Also, we are not keeping user name in sharedPreferences, add some placeholder name for now.
( we will replace it with the string received from the API. https://github.com/project-travel-mate/server/issues/28 )

**Comment by Swati4star** [comment]
Fixed via https://github.com/project-travel-mate/Travel-Mate/pull/126 by @syedjahangirpeeran 👍
