### ISSUE TITLE
Provide support for Java 8 language features

### ISSUE THREAD

**Issue by brijeshshah13** [project-travel-mate/Travel-Mate#122]
### Steps to reproduce
N/A.

### Expected behaviour
Provide the support so that major features like `Lambda expressions`, `Default and static interface methods`, etc. can be put to use in the development.

### Actual behaviour
Not yet provided.

### Would you like to work on the issue?
Yes.

**Comment by Swati4star** [comment]
What exactly would be required for enabling this support?
Share an appropriate link or something

**Comment by brijeshshah13** [comment]
@Swati4star Here, https://developer.android.com/studio/write/java8-support

**Comment by Swati4star** [comment]
So, are you thinking of adding the support only, or using the Java 8 features too in this PR?

**Comment by brijeshshah13** [comment]
@Swati4star I thought of adding the support and converting possible methods to lambda expressions, where possible.

**Comment by Swati4star** [comment]
Sure. You can start working on this one. 👍

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/124
