### ISSUE TITLE
Confirm Password field

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#123]
- On Signup screen, add a confirm password field.
- Add validation to check if password & confirm password values are equal.

**Comment by shreyag12** [comment]
Hi! I would like to work on this but how to set up the project locally. Couldn't find any contributing guidelines.

**Comment by Swati4star** [comment]
@shreyag12 
You can clone the project & import the Android folder in the `Android Studio`
Build & run the project. It should work.

Are you gonna work on this?

**Comment by shreyag12** [comment]
Ok. Is it for an android app, I thought the issue was for web app in Django?

**Comment by Swati4star** [comment]
You can check the language for the repo. It is `Java`. That definitely means this in Android issue.

Also, all the server related issues of Travel-Mate are there on https://github.com/project-travel-mate/server

**Comment by brijeshshah13** [comment]
@Swati4star I haven't claimed the Snackbar issue yet so can I work on this one first?

**Comment by Swati4star** [comment]
Sure @brijeshshah13 . Go ahead with this one. 👍

**Comment by brijeshshah13** [comment]
Alright. I'm claiming this one 👍

**Comment by brijeshshah13** [comment]
@Swati4star If password and confirm password do not match, then what should be the behavior?

**Comment by Swati4star** [comment]
Just show a snackbar/toast message showing that they don't match.

Also, add the eye icon to both of them.

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/130
Thanks to @brijeshshah13 👍
