### ISSUE TITLE
Image not displaying

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#128]
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. 
1)From the Home Screen where all the cities are listed out
2)Select Hyderabad 
### Expected behaviour
Image should load in the corresponding detail screen

### Actual behaviour
Image does not load in the corresponding detail screen

### Would you like to work on the issue?
Tell us if you would like to work on this issue

**Comment by Swati4star** [comment]
Fixed by 0f2924b6f91126c5d13d235a1cc0ebac1c06912c
