### ISSUE TITLE
Fun facts does not load results

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#129]
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. 
1)From the Main screen select any city
2) From the city's detail screen select Fun Facts tile

### Expected behaviour
Fun facts should get displayed

### Actual behaviour
Fun facts are not getting displayed

**Comment by Swati4star** [comment]
Right now, we don't have fun facts for every city. 
I'll hide the fun facts option for the city which don't have any fun facts.

**Comment by knightcube** [comment]
Okay we can keep this issue open and address it later once we have all the fun facts updated

**Comment by Swati4star** [comment]
I have assigned it to myself only. I'll look into this one.

**Comment by Swati4star** [comment]
Fixed by 0f2924b6f91126c5d13d235a1cc0ebac1c06912c
