### ISSUE TITLE
UI suggestion/mock-up for city trends feature

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#132]
Come up with an awesome looking UI designed in adobe xd or sketch or whichever design tool that you want to use. Keep in mind that whatever colors you use should be like different shades of blue used in the logo of the app. Ofcourse you can have one complementary color as an accent color.
Once you are done simply post your UI design in the comments below as a png file. Keep in mind that we are just asking for mockup right now and not the fully developed layout through xml. So if you want to work on the issue simply comment below. Once you are assigned the issue you can continue to work on the UI mockup

**Comment by knightcube** [comment]
I am taking up this issue

**Comment by Swati4star** [comment]
@knightcube  Any updates on this?

**Comment by nitinnatural** [comment]
![artboard 1](https://user-images.githubusercontent.com/2595032/46833402-2c954980-cdc6-11e8-875b-531eb3771b73.png)

@Swati4star Design suggestion. 
source: Google IO Android app (filter screen).

if no progress here I want to pick this up.

**Comment by nitinnatural** [comment]
![artboard 1](https://user-images.githubusercontent.com/2595032/46833755-20f65280-cdc7-11e8-8f30-c769ab0ec389.png)

Design suggestion
- source : google IO 2018 android app.

**Comment by Swati4star** [comment]
The UI looks great! ♥️ If you want to code this in app also, you can work on it :)

**Comment by nitinnatural** [comment]
@Swati4star Cool! I will create a pull request soon.
