### ISSUE TITLE
UI suggestion/mock-up for checklist feature in utilities

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#133]
Come up with an awesome looking UI designed in adobe xd or sketch or whichever design tool that you want to use. Keep in mind that whatever colors you use should be like different shades of blue used in the logo of the app. Ofcourse you can have one complementary color as an accent color.
Once you are done simply post your UI design in the comments below as a png file. Keep in mind that we are just asking for mockup right now and not the fully developed layout through xml. So if you want to work on the issue simply comment below. Once you are assigned the issue you can continue to work on the UI mockup

**Comment by knightcube** [comment]
![android mobile 1](https://user-images.githubusercontent.com/22871961/42855559-b6d0a6e0-8a5e-11e8-9894-65d791b6c9ee.png)

**Comment by Swati4star** [comment]
This looks perfect! Will be creating issues for implementing this UI.
