### ISSUE TITLE
Show multiple images in city info page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#135]
- We get an array of images for a particular city from the server.
- Use that array to show multiple images in city info page
- Right now, we show only 1 image at the top. Change that to create slideshow of the images we have received.

Reference: 
https://github.com/project-travel-mate/Travel-Mate/blob/0f2924b6f91126c5d13d235a1cc0ebac1c06912c/Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfo.java#L252

**Comment by syedjahangirpeeran** [comment]
I would like to work on this.

**Comment by syedjahangirpeeran** [comment]
Same problem app is crashing saying that layout should be in Theme.AppCompat. But that theme has ActionBar already which properties aren't changing. Its becoming white for alpha =0 instead of becoming invisible.

**Comment by Swati4star** [comment]
Define some other new theme for this particular activity. That might help.

**Comment by syedjahangirpeeran** [comment]
Did it but still it is crashing saying that it should in Theme.AppCompat only.

**Comment by Swati4star** [comment]
create a PR, I'll try to look into the code

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/168
