### ISSUE TITLE
[New Feature] Weather forecast

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#136]
- Go to a city info page & it shows weather.
- When you click on the weather, show the weather forecast
- Use weather forecast API to show weather for next few days.
The endpoint for API is : `/api/get-multiple-days-weather/4/chennai`
- The UI should be like this:
<img width="391" alt="screen shot 2018-06-24 at 10 15 53 pm" src="https://user-images.githubusercontent.com/9164477/41929580-2e48583c-7996-11e8-995b-1ed51462fa70.png">

In the response,
The `condensed` parameter can be:
```
Thunderstorm
Drizzle
Rain
Snow
Atmosphere
Clear
Clouds
```
Show the UI background appropriate according to the above parameter values.

**Comment by amy6** [comment]
I'd like to work on this issue.

**Comment by Swati4star** [comment]
Sure @amy6 💯

**Comment by amy6** [comment]
I'll be using Retrofit. Can I get more details about the endpoint? Is condensed a parameter/object in the response? I'm not able to invoke the one shared (/api/get-multiple-days-weather/4/chennai).

**Comment by Swati4star** [comment]
- We are already using okhttp everywhere. You can use that only.
- Also, how are you trying to invoke this endpoint? See this for example:
https://github.com/project-travel-mate/Travel-Mate/blob/f0bf4fed479088fd0ad488ac28f8e8964a8bd632/Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java#L202

We need to send authorization token also in the headers parameter.

**Comment by Swati4star** [comment]
You will get response like this:
```
[
    {
        "temp": null,
        "temp_units": "C",
        "max_temp": 35.25,
        "min_temp": 26.8,
        "code": 501,
        "condensed": "Rain",
        "description": "moderate rain",
        "icon": "http://openweathermap.org/img/w/10d.png",
        "humidity": 88,
        "humidity_units": "%",
        "pressure": 1017.48,
        "pressure_units": "hPa"
    },
    {
        "temp": null,
        "temp_units": "C",
        "max_temp": 32.06,
        "min_temp": 25.5,
        "code": 501,
        "condensed": "Rain",
        "description": "moderate rain",
        "icon": "http://openweathermap.org/img/w/10d.png",
        "humidity": 76,
        "humidity_units": "%",
        "pressure": 1016.11,
        "pressure_units": "hPa"
    },
    {
        "temp": null,
        "temp_units": "C",
        "max_temp": 32,
        "min_temp": 27.36,
        "code": 501,
        "condensed": "Rain",
        "description": "moderate rain",
        "icon": "http://openweathermap.org/img/w/10d.png",
        "humidity": 75,
        "humidity_units": "%",
        "pressure": 1015.55,
        "pressure_units": "hPa"
    },
    {
        "temp": null,
        "temp_units": "C",
        "max_temp": 32.99,
        "min_temp": 27.84,
        "code": 500,
        "condensed": "Rain",
        "description": "light rain",
        "icon": "http://openweathermap.org/img/w/10d.png",
        "humidity": 0,
        "humidity_units": "%",
        "pressure": 1007.55,
        "pressure_units": "hPa"
    }
]
```

**Comment by amy6** [comment]
Great! Got it, thank you! Will use OkHttp.

**Comment by Swati4star** [comment]
@amy6 Updates?

**Comment by amy6** [comment]
@Swati4star apologies for the delay. I'm working on adding new weather icons. Will post the UI screenshots on Slack tomorrow.
