### ISSUE TITLE
Move My Trips to navigation bar

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#140]
To view MyTrips, the user has to:
- Open up navigation bar
- Select `Travel`
- Then, Go to `My Trips`
The discoverability of this feature is low.
What to do?
- Move `My Trips` to navigation bar
- Right now it is activity, convert it to a fragment
- Remove it from `Travel`

**Comment by syedjahangirpeeran** [comment]
I would like to work on this

**Comment by syedjahangirpeeran** [comment]
Sorry I will work on #142 first.

**Comment by Swati4star** [comment]
Sure. Go ahead 👍

**Comment by syedjahangirpeeran** [comment]
@Swati4star  If i change MyTrips to fragment then i need to change MyTripsAdapter and some other files also which need huge changes. Shall I proceed??

**Comment by Swati4star** [comment]
Yes. Go ahead with these.

**Comment by Swati4star** [comment]
Closed by https://github.com/project-travel-mate/Travel-Mate/pull/155
