### ISSUE TITLE
Use API to fill information in profile page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#141]
Right now, the information in profile page is static.

What to do?
- Call `api/get-user` endpoint to get user's details
- Fill the username & image using the response of API
In case the image is null, show the default image only.
- The information for `joined-on` is not available right now. ( being worked on in https://github.com/project-travel-mate/server/issues/30 )

**Comment by brijeshshah13** [comment]
@Swati4star Shall I integrate Gson library so that we can use Java classes as Models to parse JSON response from the server?

**Comment by Swati4star** [comment]
Yeah sure! @brijeshshah13

**Comment by brijeshshah13** [comment]
@Swati4star The `username` is already being fetched from the SharedPreferences. So why are we fetching it again from the `get-user` again?

**Comment by Swati4star** [comment]
-The problem is `username` is not being saved at the time of signup right now. 
-Also, we don't have username in case user just login through our app.
-
