### ISSUE TITLE
[UI bug] UI quirk in the card items

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#142]
There is a UI quirk in the card items. There is extra black space by the right & left of these card items:
<img width="328" alt="screen shot 2018-06-27 at 8 22 59 pm" src="https://user-images.githubusercontent.com/9164477/41982034-04398d06-7a48-11e8-8d54-24931ed8590a.png">
<img width="311" alt="screen shot 2018-06-27 at 8 23 09 pm" src="https://user-images.githubusercontent.com/9164477/41982035-04804296-7a48-11e8-8e92-2fd1e397fe4e.png">

### Expected behaviour
There shouldn't be this black space. The Image should cover that space too.

**Comment by syedjahangirpeeran** [comment]
I would like to take this

**Comment by Swati4star** [comment]
Sure :+1:
