### ISSUE TITLE
Allow users to select City Name in hotels page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#149]
- Go to Navigation bar, click on `Travel`
- Select `Hotel Booking`
- Allow users to select a city

What to do?
- On the top, there is a bar showing `Showing Mumbai Hotels`.
- When user clicks on that bar, open a dialog ( popular with a list of popular cities from our server )
- Also add a search bar on that dialog that searches for the city starting with the typed name

Endpoints to use : 
- `get-all-cities`
- `get-city-by-name/city_prefix`

**Comment by aayushinigam** [comment]
I would like to work on this.

**Comment by Swati4star** [comment]
Sure :)
