### ISSUE TITLE
Add option to view as list in Map activities

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#150]
What is the issue?
- Go to Navigation bar, then `Travel`, then `Real Time Locator`, or
- Select on any destination, then `Hangouts`, `Monument` or any other map item,
On going to any of above two, the map opens up with a lit of items. 
Viewing all the items on map becomes a bit difficult

What to do?
- Add another option on the same page to view the items as list too
- Add this option in the navigation bar ( to switch between map & list view)

**Comment by aayushinigam** [comment]
I would like to work on this

**Comment by Swati4star** [comment]
Add an option of the top to switch between the 2 views. You can have 2 icons:
- When there is map view, show a list icon somewhere to switch to list view
- When there is list view, show a map icon somewhere to switch to map view

**Comment by Swati4star** [comment]
@aayushinigam 
You can see Zomato for reference. There is button to switch between the 2 views:
![screenshot_20180728-184935](https://user-images.githubusercontent.com/9164477/43356944-35860b16-9297-11e8-9196-00cfac976b24.jpg) ![screenshot_20180728-184930](https://user-images.githubusercontent.com/9164477/43356946-36958a5e-9297-11e8-9788-7627bf2d2e9e.jpg)

**Comment by aayushinigam** [comment]
@Swati4star for hangouts, monuments etc in destination page, there already is a horizontal recyler view of lists. Plus there's this issue #154. So do you want me to implement a new activity for lists?
I have done this for real time locator, but I think I shouldn't change it for the ones in city description page.
