### ISSUE TITLE
Change in Maps UI

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#154]
What is the issue?
- Go to Navigation bar, then Travel, then Real Time Locator, or
- Select on any destination, then Hangouts, Monument or any other map item,
On going to any of above two, the map opens up with a lit of items.
Right now, the map shown zero items & clicking on card item shows the item on map

What to do?
- Create the UI similar to the below image. Show all the items on map at once & highlight the item when it's card is clicked
- Also, the list view is horizontal right now. Make it vertical only.
![download](https://user-images.githubusercontent.com/9164477/42088000-9979f626-7bb5-11e8-9ccb-7d50569a67a3.jpeg)

- Increase the zoom level (Right now, it is very less)
- The text (description) on map items sometime shows `html` tags. The tags should not be there, they should rather be converted to formatted text.

**Comment by aayushinigam** [comment]
Taking this up!
