### ISSUE TITLE
Allow users to update or edit profile image

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#156]
What should be the flow?
- In the profile page, Add a `+` icon by the side of the profile image
- When the user clicks on that icon, open up the gallery & allow him to select an image
- Open up a photo editor that crops the image into a square.
- Compress the image (256x256) and create a link using Cloudinary API ( https://cloudinary.com/documentation/solution_overview )
- Send the created link to below endpoint:
POST request on `update-profile-image`
parameter : `profile-image-url`

**Comment by aayushinigam** [comment]
I would like to work on this issue.

**Comment by Swati4star** [comment]
Sure. Go ahead 👍

**Comment by aayushinigam** [comment]
I'm going to be a little late because I was trying to remove some merge conflicts and I lost all my changes. So I'm gonna have to start all over again :(

**Comment by Swati4star** [comment]
Checkout `reflog` command. It might help you to recover lost changes.
