### ISSUE TITLE
Open a user's profile page when someone clicks on his name in my trips 

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/Travel-Mate#164]
In my trips, if someone clicks on any user's name, open that user's profile page similar to what we see in my profile currently 

+ On clicking the + icon, the view should show/hide
+ Show the arrow icon on each friend item
+ On clicking anywhere on the list item, the user's profile page should open up.

**Comment by Swati4star** [comment]
Adding more enhancements to this issue:
Create the UI like this:

![whatsapp image 2018-07-01 at 11 51 16 pm 1](https://user-images.githubusercontent.com/9164477/42167021-619ce17e-7e2a-11e8-934d-256c1096e1f9.jpeg)

- On clicking the + icon, the view should show/hide
- Show the arrow icon on each friend item
- On clicking anywhere on the list item, the user's profile page should open up.

**Comment by aayushinigam** [comment]
I'm taking this up.

**Comment by Swati4star** [comment]
Sure @aayushinigam

**Comment by aayushinigam** [comment]
@Swati4star Do you suggest using an ExpandableListView for implementing the first point?

**Comment by Swati4star** [comment]
Yes. Something like that only.
