### ISSUE TITLE
Show fact source in the City facts page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#166]
The `get-city-facts` API responds with the following for each fact:
```
    {
        "id": 2,
        "fact": "As early as in the year 1911, British announced to shift their capital from the then Calcutta to Delhi and it was shifted to Delhi in 1912.",
        "source_text": "service sutra",
        "source_url": "https://www.servicesutra.com/blog/20-amazing-interesting-facts-about-delhi/"
    },
```

The current facts page look like this:
![screenshot_20180701-124719](https://user-images.githubusercontent.com/9164477/42132028-588247f8-7d2d-11e8-8ca8-e150a69d5d5b.jpg)

Add a text at the bottom of this facts page, which shows `source_text`, and on clicking that source_text, `source_url` should open up in the browser.
The fontsize should be very small for this & font color should be greyish.

**Comment by vyankatesh24** [comment]
Hi @Swati4star 
I would like to work on this issue.

**Comment by Swati4star** [comment]
Sure!

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/179 👍
