### ISSUE TITLE
Create Android search dialog on Home Page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#167]
In the Home Page, when we click on "Search a city" edit text, open Android Search Dialog with the suggestions. In the current UI, the suggestions are shown, but in a simple autocomplete list view only.
The UI should be like below:
![aww0s](https://user-images.githubusercontent.com/9164477/42132725-2e11af0a-7d3b-11e8-98f7-36206d2f10ef.jpg)

![screenshot_20180701-142644](https://user-images.githubusercontent.com/9164477/42132733-74888062-7d3b-11e8-8749-8634bf7c3ec6.jpg)

**Comment by amy6** [comment]
I'd like to work in this.

**Comment by Swati4star** [comment]
Sure @amy6 !

If you face any problem, ask here. 👍

**Comment by Swati4star** [comment]
@amy6 Status?
