### ISSUE TITLE
Add a signout button on profile page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#172]
- Open up navigation drawer
- Click on your photo, profile page opens up
- Add a new option in the action bar for `signout`
- On clicking that, an alert should open up & if user selects ok, sign him out from the app.

Sign out is already implemented. You can use that piece of code.

**Comment by syedjahangirpeeran** [comment]
I would like to work on this

**Comment by Swati4star** [comment]
Sure!!

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/176 👍
