### ISSUE TITLE
Use Zxing library for QR code reader & creator

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#173]
Currently, we are using `"QRDroidServices", by DroidLa.` for creating & reading the QR code for `Share Contact`

### Steps to reproduce
- Go to navigation drawer. Select `Travel`
- Go to `Utilities`. Select `Share Contact`
- For "QRDroidServices",  we need to download another app.

###What to do?
- Use google's Zxing library for creating as well as reading the QR code.
- Remove the code of "QRDroidService"

References:
- https://www.simplifiedcoding.net/android-qr-code-scanner-tutorial/
- https://medium.com/@aanandshekharroy/generate-barcode-in-android-app-using-zxing-64c076a5d83a

**Comment by aayushinigam** [comment]
What exactly is the expected functionality here?
Click on Share My Contact -> A bar code has to generated -> Next?

**Comment by Swati4star** [comment]
There are 2 buttons on that page:
1. **Share my contact**: The purpose of this is to share your contact via qr code. So, a qr code is presented on the screen (as well as placed in the gallery)
2. **View someone's contact**: This opens up a scanner, can read that particular qr code, decodes it & saves the person's contact (name, phone number) in user's contact list.
 
Earlier, we used to have phone number also in the login/signup process. But now it is replaced by email ids. So, replace the phone number also in qr code with the email id.

**Comment by aayushinigam** [comment]
Alright. I'll take this up!

**Comment by aayushinigam** [comment]
Does removing phone number from QR code mean phone number won't be shared at all? And only email id will be shared?

**Comment by Swati4star** [comment]
Yes. Only email id will be shared for now.

Regards,
Swati Garg

**Comment by aayushinigam** [comment]
Phone numbers were getting saved in contacts. Where are email ids to be saved after scanning qr codes?

**Comment by Swati4star** [comment]
We can save email id also in contacts. Do that
