### ISSUE TITLE
Add option in Trip info page to view city info

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#174]
There is no way to go to city page from my trip info page

### Steps to reproduce
- Open navigation drawer, Go to my trips
- Go to any trip

### Expected behaviour
- Add an option `Know more about city-name`
- On clicking that, the city info page for that particular city should open up.

**Comment by syedjahangirpeeran** [comment]
Can you state the position where the option should be?

**Comment by knightcube** [comment]
Thid can be merged with #162. I wanted almost the same thing

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/183
