### ISSUE TITLE
gradle missing

### ISSUE THREAD

**Issue by git-typecode** [project-travel-mate/Travel-Mate#175]
### Steps to reproduce
fork, clone and Import project in android studio

### Expected behaviour
android studio can build it

### Actual behaviour
Gradle seems to be missing.
message is: Migrate Project to Gradle?
This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build system.

### Would you like to work on the issue?
How do i fix it?

**Comment by Swati4star** [comment]
Please share a screenshot of what actual error message are you getting?

Also, googling it will help. Because, everyone else seems to be able to build the project successfully on Android studio.

**Comment by git-typecode** [comment]
I have fixed it now, however it seems that the project dosent build with Gradle 4.6. I downgraded to 4.5 and the then it worked
