### ISSUE TITLE
Show image in collapsible toolbar City Detail screen

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#181]
Currently, the image of the city is being shown in an image view below the toolbar in the City detail screen. Show it inside a collapsible toolbar

**Comment by Swati4star** [comment]
Use https://github.com/ksoichiro/Android-ObservableScrollView library for above.

**Comment by knightcube** [comment]
Do we need a library for that? We can use the normal CollapsibleToolbarLayout to achieve it as well

**Comment by syedjahangirpeeran** [comment]
Is it possible to do so for view pager?

**Comment by Swati4star** [comment]
See this : http://blog.nkdroidsolutions.com/collapsing-toolbar-with-tabs-android-example/
