### ISSUE TITLE
[New Feature]Add a Google Assistant quiz app

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#182]
This feature would let users take a small quiz of 5 questions on cities around India. The user can simply say "Talk to Travel Mate Quiz" and the assistant app would start. The user can play the quiz and get the results from the assistant instantly.

**Comment by Swati4star** [comment]
We need content for this first. Find the source first which will provide this content, and add server issue to get API for that.

**Comment by knightcube** [comment]
We won't require server to handle it as such. The source that you are looking for would be a simple spreadsheet that we can create in google sheets. It would have all the questions and the answers

**Comment by Swati4star** [comment]
Are you willing to create a spreadsheet? Then, it's fine. But we need proper APIs for this.

**Comment by knightcube** [comment]
No we won't require API because its a simple Intent action that has to be handled and that can be done without the help of server :)

**Comment by Swati4star** [comment]
what about the data? Post a spreadsheet link here which can be used for this purpose.

**Comment by knightcube** [comment]
Yes we need to make a spreadsheet with questions however it should not be shared publicly as then it can be edited easily. So it would be better if we don't share it publicly. You can read about Actions on Google to get a clear picture - https://developers.google.com/actions/

**Comment by Swati4star** [comment]
I suppose this issue in done? @knightcube

**Comment by Swati4star** [comment]
https://assistant.google.com/services/a/uid/0000008961d39fc7
