### ISSUE TITLE
Remove friend from trip

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#185]
### Steps to reproduce
- Go to navigation drawer. Select `My Trips`
- Go to any trip
- There is a list of friends
- There is no way to remove a friend from the trip

### Expected behaviour
- Add an option on the list item to remove the friend from trip

### Endpoint to use
Everything is mentioned in https://github.com/project-travel-mate/server/issues/16

**Comment by aayushinigam** [comment]
I would like to work on this
