### ISSUE TITLE
Improve the UI when there are no friends in a trip

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#186]
When there are no friends on a trip, the UI is this:
![screenshot_20180705-121427](https://user-images.githubusercontent.com/9164477/42306765-e0ca11c2-804d-11e8-86db-ae35ed1c5963.jpg)

### Expected behaviour
When there are no friends on a trip:
- Hide the edit text & button
- change the text to `Travelling with someone? Add friends to this trip` (Don't make this bold. )
- When user click on above text, show the edit text & button

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
Sure @syedjahangirpeeran :)

**Comment by Swati4star** [comment]
Closed by #200
