### ISSUE TITLE
Save most popular cities offline

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#188]
Every time, user visit `Destinations` page, an API call is made. This experience is not good.

### Steps to reproduce
- Go to the navigation drawer. Click `Destinations`
- Go to some other fragment. Come to `Destinations` again.
- Again the API call is made.

### Expected behaviour
The information should be saved locally.

### Actual behaviour
API call is made every time

### What to do?
- Create a local database (using `Room persistence library`)
- If the database is empty, show the loader & fetch response & fill the db. (Set an expiration time. 24 hours for the database, after which it is deleted & has to be filled again)
- If the database has information, use that to fill the layout on `Destinations` page

**Comment by santoshhiremani** [comment]
Approach sounds good, Let me know if i can...Will see how much we can optimise and reduce API calls.
