### ISSUE TITLE
Update friends list after adding a new friends

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#189]
The `Friends in this trip` list doesn't get updated automatically updated after adding a new friend

### Steps to reproduce
- Go to the navigation drawer. Click on `My Trips`
- Go to a trip. Type the email of a friend & click on `add friend`
- There is no change in the friends list

### Expected behaviour
- The friends list should get automatically updated

**Comment by syedjahangirpeeran** [comment]
Would like to work on this!

**Comment by Swati4star** [comment]
Sure @syedjahangirpeeran 👍

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/193
