### ISSUE TITLE
Don't show dots below image of there is only one image in city page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#190]
The UI when there is one image is:
![screenshot_20180705-180032](https://user-images.githubusercontent.com/9164477/42328060-024a0ffe-808b-11e8-9d13-8cb6e66f9233.jpg)

### Steps to reproduce
- Select `Destinations` from the navigation drawer. Select `Chennai` or any other city with 1 image

### Expected behaviour
- There should not be a dot below the image

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
Sure @syedjahangirpeeran 👍

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/194
