### ISSUE TITLE
Use calendar picker library when calendar is opened

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#192]
### Library to be integrated
https://github.com/maxyou/CalendarPicker

### When does calendar open up?
- Go to `My Trips`. Click on `Add new Trip`.
- When you press `start date` button, calendar open up

### What to do?
- Use the mentioned library in both the above cases.
- Set the default date to today

**Comment by RathodKinjal76** [comment]
I would like to work on this issue.

**Comment by knightcube** [comment]
Also update the button to show the results for the current date....right it is showing a fixed date everytime. Get the current date from user's phone ,update UI and show results accordingly.

**Comment by Swati4star** [comment]
I have added in the description to set default date to today (@knightcube)

@RathodKinjal76, start with this issue & do the other one after this is resolved.

**Comment by Swati4star** [comment]
@RathodKinjal76 any updates?

**Comment by Swati4star** [comment]
Won't be doing this since we have removed calendar from hotel booking
