### ISSUE TITLE
Show appropriate animations on screens when there are no results

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#195]
When we get no results from the API due to any reason ( there are actually no results, server error, internet connection), we just show a snackbar with some appropriate message. Replace, the snackbar with proper animations.

### Which screens are to be added with this layout?
- `City info` (opens up on clicking any city)
- `Hotel booking`
- `Online shopping`
- `Trip info` (opens up on clicking any trip)
- `Profile` 

### What to do?
- Checkout https://github.com/project-travel-mate/Travel-Mate/blob/1dac4f949697f2766c923a16eb0eb89cd0386286/Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripsFragment.java
We have functions for `networkError` `noResults`. These functions show approriate animations. Add these functions & `animationView` to above mentioned screens & show them when required.

**Comment by RathodKinjal76** [comment]
I would like to work on this issue.

**Comment by Swati4star** [comment]
You can pick up only 1 issue at a time. Pick https://github.com/project-travel-mate/Travel-Mate/issues/192 first.

**Comment by RathodKinjal76** [comment]
Okay

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
Also, there is a possibility that a few of them might already be resolved.
