### ISSUE TITLE
Open Image in full screen when image is clicked on the profile page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#196]
### Steps to reproduce
- Open the navigation drawer. Click on your photo
- Go to my profile page
- When image is clicked, open it in a new activity

### what to do?
- Use TouchImageView.java ( https://github.com/project-travel-mate/Travel-Mate/blob/master/Android/app/src/main/java/utils/TouchImageView.java ) to open this image in new activity.

This view allows user to zoom the image also.

**Comment by syedjahangirpeeran** [comment]
I'm not able to upload any image of mine. It's says **Editing this image not supported for this image** .

**Comment by Swati4star** [comment]
A lot of other users are also facing the same problem, I'll create an issue for this.

**Comment by aayushinigam** [comment]
I'm taking this up!

**Comment by Swati4star** [comment]
Do this for user's as well as friend's profile photo.
