### ISSUE TITLE
Allow users to update trip name

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#198]
Add an option to update trip name

### Steps to reproduce
- click on the navigation drawer. Go to `My Trips`
- Click on any trip

### What to do?
- Add a pencil icon by the side of trip name.
- On clicking the pencil icon, the trip name should become editable.
- Allow user to edit it (For reference: check user profile page; user name is editable there)

### Endpoint to use
The information is given in https://github.com/project-travel-mate/server/issues/58

**Comment by aayushinigam** [comment]
I would like to work on this.
