### ISSUE TITLE
Remove the option to share contact & create qr code by default

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#201]
The current UI of sharing the contact is: 
![screenshot_20180706-120950](https://user-images.githubusercontent.com/9164477/42369881-df4f5dc6-8128-11e8-934f-8d879c24f752.jpg)

### Steps to reproduce
- Go to the navigation drawer. Click `Utilities`
- Select `Share contact`

### What happens right now?
- Click on `Share my contact` and then, the qr code is generated.

### What to do?
- Remove the `Share my contact` button.
- The QR code should automatically be generated on the screen
- Add a text below the QR code, that says, `Share this code with the people to share your contact details`

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
Sure.

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/202
