### ISSUE TITLE
Doesn't redirect back on adding a trip  

### ISSUE THREAD

**Issue by f71uday** [project-travel-mate/Travel-Mate#203]
Describe your issue here.

### Steps to reproduce

My Trips -> Add new Trip

### Expected behaviour
Application should redirect back on the list of the Trips 

### Actual behaviour
Display a Toast of successful addition of trip and remain on same activity

### Would you like to work on the issue?
yes

**Comment by Swati4star** [comment]
Sure. You can work on this issue.

**Comment by Swati4star** [comment]
@f71uday You working in this one?

**Comment by f71uday** [comment]
Yes I m on @swati4star
