### ISSUE TITLE
AutoCompleteText not Working

### ISSUE THREAD

**Issue by f71uday** [project-travel-mate/Travel-Mate#204]
Describe your issue here.

### Steps to reproduce
My Trips -> Add New Trip -> Enter City Name 
### Expected behavior
Should Autocomplete the city name. as they are predefined names
### Actual behavior
doesn't suggest any item
### Would you like to work on the issue?
Tell us if you would like to work on this issue

**Comment by Swati4star** [comment]
We are converting autocomplete textview to a button only. ( https://github.com/project-travel-mate/Travel-Mate/issues/254 )
