### ISSUE TITLE
Unable to edit profile image

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#205]
Users are not able to edit the profile image.

### Steps to reproduce
- Open the navigation drawer. Click on profile photo.
- Profile page opens up. 
- Select Camera icon

### Expected behaviour
The image editor should open up.

### Actual behaviour
The message is displayed **Editing this image not supported for this image .**

**Comment by aayushinigam** [comment]
@Swati4star @syedjahangirpeeran Was this happening before adding camera icon on profile picture?

**Comment by Swati4star** [comment]
No no. It is happening after the update.

**Comment by aayushinigam** [comment]
Oh alright!

**Comment by syedjahangirpeeran** [comment]
@aayushinigam  Yes, I wasn't able to upload even before.

**Comment by aayushinigam** [comment]
Hmmm. It's happening for some people because I'm able to edit it even after addition of camera icon.

**Comment by syedjahangirpeeran** [comment]
Taking this up.

**Comment by Swati4star** [comment]
What was the issue actually? 

The error was there for the users who don't have apps with image cropping ability?

**Comment by syedjahangirpeeran** [comment]
Yes. Crop intent isn't supported with most of devices which run Stock Android. So, We need to have our own crop activity as whatsapp.
