### ISSUE TITLE
Allow user to remove profile photo

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#207]
Allow user to remove profile photo

### Steps to reproduce
- Open navigation drawer. Click on profile icon
- On clicking the camera icon, there should come an option to `Remove picture`
- If the user clicks on `Remove picture`, make an API call

Endpoint to use: `remove-profile-image`
No parameter required.

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
Sure.

**Comment by syedjahangirpeeran** [comment]
My bad, I can't test it. My image isn't getting uploaded. I will take the #206 instead.

**Comment by Swati4star** [comment]
Oh. Okay.

**Comment by syedjahangirpeeran** [comment]
@Swati4star can you update the cloudinary links. I will start working on this.

**Comment by Swati4star** [comment]
Connect with me on slack regarding this.
