### ISSUE TITLE
Change friends default icon in my trips page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#210]
Modify the default friend icon on this screen
<img width="330" alt="screen shot 2018-07-07 at 10 03 16 pm" src="https://user-images.githubusercontent.com/9164477/42412898-e5eccfd2-8232-11e8-84c0-02b7fe8914dd.png">

### Steps to reproduce
- Go to the navigation drawer
- Select `My Trips`. Go to any trip
- The above screen is displayed

**Comment by aayushinigam** [comment]
I'm taking this up

**Comment by aayushinigam** [comment]
While I'm at it, can I also solve #296 along with it, because both of them requires changes in trip's UI?

**Comment by Swati4star** [comment]
Sure.
