### ISSUE TITLE
Improve Add Trip screen UI

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#213]
<img width="336" alt="screen shot 2018-07-08 at 3 08 32 pm" src="https://user-images.githubusercontent.com/9164477/42418567-d393e076-82c0-11e8-8e16-303ea7a1c5e0.png">

### Steps to reproduce
- Go to the navigation drawer. Go to `My Trip`
- Click on `+` button. 
- The above screen opens up.

### Expected behaviour
- Remove the `enter end date` button
- When user has entered the start date, show it somewhere in the UI.

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
Sure 👍

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/214
