### ISSUE TITLE
add a list of the issues reported by the user

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#217]
### Steps to reproduce
- Go to the navigation drawer. Click on `report a bug`

### Expected behaviour
Add a list of issues reported by the user in the following screen:
<img width="338" alt="screen shot 2018-07-08 at 10 57 34 pm" src="https://user-images.githubusercontent.com/9164477/42422374-86a6d52e-8302-11e8-904d-d058526bd792.png">

### Endpoint to use
`get-all-user-feedback`

**Comment by aayushinigam** [comment]
I'm taking this up!
