### ISSUE TITLE
Some changes in share contact screen

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#218]
### Steps to reproduce
- Go to `Utilities` -> `Share Contact`

### Expected behaviour
- Change text on button to `View Someone's contact`
- Move the button to bottom of screen
- Move QR code to center of screen
- Go to `View someone contact` & press back. The toast message says,`Result not found`. Remove this toast.

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/228
