### ISSUE TITLE
Add user status in user profile screen

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#219]
### Steps to reproduce
- Open navigation drawer. select your profile photo.
- Profile screen opens up

### Expected behaviour
- Add a status string below the user profile
- By default, the text should be `Write something about yourself`
- Add a pencil icon by the side of it.
- On clcking the icon, user should be able to enter a status (limit it to 30 letters)
- On clciking done, it should be updated on the server also
- Add user status to sharedPreferences also.

### Endpoints to use
Details are there in : https://github.com/project-travel-mate/server/issues/71

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
The API is not yet ready for this. You might not be able to implement it fully.

**Comment by syedjahangirpeeran** [comment]
I am ready with the code .  Will create PR as soon as the API is ready.

**Comment by Swati4star** [comment]
Oh. Then you can create a PR. Leave the API call. Just add a placeholder API link for now. I'll replace new as soon as it's ready.

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/227

**Comment by syedjahangirpeeran** [comment]
@Swati4star  Can you assign it so it would be easy for you to filter out my assigns during evaluations?

**Comment by Swati4star** [comment]
Also, I check your contributions from here : https://github.com/project-travel-mate/Travel-Mate/commits?author=syedjahangirpeeran
