### ISSUE TITLE
add swipe refresh layout in `My Trips` page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#221]
### Steps to reproduce
- Open the navigation drawer. Go to `My Trips`

### Expected behaviour
- Add swipe refresh layout to this fragment.
- On swiping, the view should refresh (Make the API call again & fetch the trips)

**Comment by f71uday** [comment]
Started working on this

**Comment by Swati4star** [comment]
Sure @f71uday
