### ISSUE TITLE
Share your QR code 

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#222]
There should be a feature for the user to share his/her QR code with others on different social media apps

**Comment by f71uday** [comment]
would like to work on this issue

**Comment by Swati4star** [comment]
Sure @f71uday

**Comment by Swati4star** [comment]
@f71uday 
### Steps 
- Go to `Utilities` in navigation drawer
- Select `Share my contact`

We have a QR code generated over there. You can add a share button on the action bar. On clicking that, an image with that QR code should be shared.

(We have a similar functionality in Funfacts also. That shares a snapshot of whole screen. I guess, you can use that code)

**Comment by f71uday** [comment]
Should I go for FloatingAction Button or Share Menu ??? @Swati4star

**Comment by Swati4star** [comment]
A share button on the action bar

**Comment by f71uday** [comment]
this file is never generated 
@Swati4star 
**ShareContactAcvity.java**
            Bitmap bitmap = barcodeEncoder.createBitmap(bitMatrix);
            //saving the generated qr code in device
            String path = Environment.getExternalStorageDirectory().getPath();
            File qrCodeFile = new File(path + "/TravelMate/QRCodes");
            qrCodeFile.mkdir();
            //for providing name to image
            Random generator = new Random();
            int n = 10000;
            n = generator.nextInt(n);

            String fname = "Image-" + n + ".jpg";
            File file = new File(qrCodeFile, fname);

            if (file.exists())
                file.delete();
            try {
                FileOutputStream out = new FileOutputStream(file);
                bitmap.compress(Bitmap.CompressFormat.JPEG, 90, out);`

**Comment by f71uday** [comment]
i tried generating file usig `getCacheDir().getAbsolutePath()`  then also there are no changes
if you try accessing `file` object within local , it throughs FileNotFoundException
