### ISSUE TITLE
Add "Favourite cities to visit" option

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#224]
- On the Main Screen where all the cities are shown add a Favourite button (e.g- Heart , Star,etc)
- Make a new section in Navigation drawer for Favourite Cities to visit and show all the favourite cities in a new Activity.
- Use Room Persistence Library to implement the feature and saving into local database

**Comment by prakhar1001** [comment]
any progress here?

**Comment by Swati4star** [comment]
No. 
You can take this one up 👍

**Comment by PeterHorbulak** [comment]
Can I work on this issue?

**Comment by Swati4star** [comment]
Yes @PeterHorbulak 👍

**Comment by AbdulDroid** [comment]
I will like to work on this issue after my registration/login issues have been fixed @Swati4star

**Comment by Swati4star** [comment]
@prakhar1001 @PeterHorbulak Any updates here?

**Comment by PeterHorbulak** [comment]
Not yet but  this week i will start. Working on this issue is part of my project in school so i hope that i can work on this :)

**Comment by Swati4star** [comment]
@PeterHorbulak Updates?

**Comment by wmisqaw** [comment]
@PeterHorbulak is this issue free or are you working on it?

**Comment by PeterHorbulak** [comment]
It´s free. You can work on it.

**Comment by wmisqaw** [comment]
I will try to complete this issue if  i can.

**Comment by Swati4star** [comment]
Sure @wmisqaw 👍

**Comment by wmisqaw** [comment]
I have created a pull request @Swati4star

**Comment by oluwadara-abijo** [comment]
I guess this issue can be closed now.

**Comment by Swati4star** [comment]
@wmisqaw @oluwadara-abijo 
I have been quite busy lately, didnt get the time to review the code. Will try to merge this in a week or so.
