### ISSUE TITLE
Fix bug in Add New Trip Screen

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#225]
There is a bug in the Add New trip screen where the user enters the details of the trip.
- Keep everything blank and click on the "add trip" button directly.
- The app crashes

**Comment by Swati4star** [comment]
The first issue you mentioned is already solved by this : https://github.com/project-travel-mate/Travel-Mate/issues/213

Update the issue for app crash only. (Make it cakewalk)

**Comment by f71uday** [comment]
This bug Fix is on Me

**Comment by Swati4star** [comment]
Sure @f71uday 👍

**Comment by Swati4star** [comment]
Just show a snackbar message, that the fields cannot be blank.

**Comment by f71uday** [comment]
ok

**Comment by f71uday** [comment]
Fixed with #259
