### ISSUE TITLE
Create a spotlight view on home page that asks user to swipe the cards

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#230]
### Library to use:
https://github.com/TakuSemba/Spotlight

Use the above library to add a custom spotlight on first card, and write a message like `Unfold the city cards to get easy access to information`.
Show this spotlight the first 3 times user tries to click on the card. Don't show it after that.

**Comment by santoshhiremani** [comment]
Only on first card of the cities fragment or navigation to guide other sections as well?

**Comment by Swati4star** [comment]
@santoshhiremani 
We can get started with the cities fragment only.

And then move on to adding this to other sections.
