### ISSUE TITLE
The dots for images in city info page does not sync

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#232]
### Steps to reproduce
- Select any destination with more than 1 image
- The images are shown on the top with dots below
- Manually swipe the images

### Expected behaviour
- The dot should also become active accordingly

### Actual behaviour
- It doesn't become active

### What to do?
- Change the corresponding dot to active when image is swiped manually also
- The images slide too fast. Decrease the sliding time. 
- In case there are no images for a city, the app crashes. Fix that also.

**Comment by aayushinigam** [comment]
I'm taking this up!
