### ISSUE TITLE
Show count of unread notifications on notification icon in action bar

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#240]
There is a notification icon on the action bar : 
<img width="346" alt="screen shot 2018-07-10 at 9 18 20 pm" src="https://user-images.githubusercontent.com/9164477/42521574-d75238bc-8486-11e8-9f17-ff037227598d.png">

### Expected behaviour
- show the count of unread notifications by the side of the bell icon

### How to get the count of unread notifications?
Use the following endpoint: https://github.com/project-travel-mate/server/issues/83

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
@syedjahangirpeeran The API is not ready for this yet. You can pick up this one: https://github.com/project-travel-mate/Travel-Mate/issues/241

**Comment by syedjahangirpeeran** [comment]
Ya sure.

**Comment by Swati4star** [comment]
The API is ready for this now. This issue can also be picked now.

**Comment by syedjahangirpeeran** [comment]
Would like to work on it.

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/245
