### ISSUE TITLE
Open the corresponding trip page when notification is clicked

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#242]
### Steps to reproduce
- Click the bell icon on any page

### Expected behaviour
- The corresponding trip page should open up clicking on the notification item.
- Also, mark the notification as read when it is clicked 
(Use this endpoint: `mark-notification/<int:notification_id>'`)

### Endpoint to use
The current endpoint being used to fetch notification details now provide trip info also. Use trip id from there & open the trip page.

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/257
