### ISSUE TITLE
Add a `mark all notifications as read` icon in Notifications page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#243]
### Steps to reproduce
- Click on the bell icon in any activity

### Expected behaviour
- Add a tick mark icon in action bar in notifications activity
- On clciking that icon, an alert should open with message `Do you want to mark all notifications as read?`. If user clicks yes, call the below endpoint, else do nothing.

### Endpoint to use
`mark-all-notification`

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
Sure!

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/247
