### ISSUE TITLE
add a swipe refresh layout on notifications page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#248]
### Steps to reproduce
- Click on bell icon on any activity
- Notification page opens up
 
### Expected behaviour
- Add a swipe refresh layout on notifications page
- On swiping, the notifications should refresh. (Make the API call again & refresh the list)

**Comment by syedjahangirpeeran** [comment]
would like to work on this!

**Comment by Swati4star** [comment]
Sure 👍

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/260
