### ISSUE TITLE
App crashes when clicked on add trip without filling anything in the form

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/Travel-Mate#249]
When you click on "Add Trip" without filling any information in the form, app crashes

### Steps to reproduce
Go to "My Trips" > Add a new trip > Click on "Add Trip"

### Expected behaviour
Should show an appropriate error message

### Actual behaviour
App Crashes

**Comment by Swati4star** [comment]
We already have an issue for this https://github.com/project-travel-mate/Travel-Mate/issues/225
