### ISSUE TITLE
Bug when user edits the status as nothing

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#250]
### Steps to reproduce
- Go to profile page
- click on pencil icon by the side of status
- Remove everything that is already there in the status
- click on ✔️ 

### Expected behaviour
- User's status should be removed, and default message `Write something about yourself should be shown`

### Actual behaviour
- The status editbox is shown empty
- The status does not get updated to anything (go back & come to your profile again. The status is same as previous one)
- The following toast appears
![screenshot_20180712-140533_02](https://user-images.githubusercontent.com/9164477/42622025-efb7b312-85dc-11e8-898c-8be82e4bb5c5.jpg)

### Endpoint to use
`remove-user-status`

**Comment by aayushinigam** [comment]
I would like to work on this.

**Comment by Swati4star** [comment]
@aayushinigam Do test it once, what happens if we send `null` as the new status to the API. If there seems to be a problem with the API, we will log an issue for the server then.

**Comment by aayushinigam** [comment]
Can we simply send "no status" to the API?

**Comment by Swati4star** [comment]
"no status" string can also be the status of some person.

**Comment by aayushinigam** [comment]
That's right!
`  if(mStatus.length() == 0)
            mStatus = "   ";`
Above code works though. Is this approach okay?

**Comment by Swati4star** [comment]
Don't do this. The problem is, we want a difference between when the user's status is set & not set. 
If it's not set, we show a different message like "write something about yourself".
So, null would be the best to differentiate.


PS. Use mstatus.trim().length() (we don't want just spaces also as a status)

**Comment by aayushinigam** [comment]
Then I guess API has to updated to handle empty status. Because if I send "null" to API for an empty status, then the same case arises - what if someone has actually set "null" as a status?

**Comment by Swati4star** [comment]
I'll create a bug in the server side for this then. You can pick up any other issue by the time.

**Comment by Swati4star** [comment]
Created https://github.com/project-travel-mate/server/issues/89

**Comment by Swati4star** [comment]
There is no string which is default status. That's why we have a new API for this.

**Comment by aayushinigam** [comment]
I'm taking this up!
