### ISSUE TITLE
Show small loader icon instead of material dialog loader on profile page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#251]
In the profile page, user can update 
- status
- name

### Steps to reproduce
- Go to the navigation drawer. Select your profile.
- PRofile activity opens up.

### Expected behaviour
- Instead of material dialog with loader, show a small progress icon by the side of status (if status is being updated) or name(if name is being updated)

### Actual behaviour
The material dialog with loader opens up
<img width="500" alt="screen shot 2018-07-12 at 2 20 00 pm" src="https://user-images.githubusercontent.com/9164477/42622735-bc090e1a-85de-11e8-9012-0280790b0302.png">

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/265
