### ISSUE TITLE
Create an About Us screen

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#252]
### What to do?
- Add a new option in the navigation drawer `About us`
- On selecting that, an about us fragment should open up

### UI screen
- Show small travel mate logo & app name at the top center
- Below that, write a small description of the app `A must-have app for those interested in travel. The app provides users with various features from choosing the correct destination to making all the bookings and to easily organizing the trip. `

- Below this, show various cards (with icon & text) : (keep the sequence as mentioned here)
   - Version code (Don't hardcode it. should change when version code of app changes)
   - Website : Redirect to http://project-travel-mate.github.io/Travel-Mate/
   - Contact us : open email intent to `projecttravelmate.github.io@gmail.com` with subject `Hello`
   - Join Slack : Don't do anything on clicking this for now
   - Share app : Create a share intent with text `Hi! I found out this app for the travellers. Do download it : https://play.google.com/store/apps/details?id=io.github.project_travel_mate`
   - Fork on Github : Redirect to https://github.com/project-travel-mate/Travel-Mate/
   - Report a bug : Open the report bug screen. (Remove the report bug from navigation drawer & change it from fragment to activity)
   - Privacy policy: Redirect to https://sites.google.com/view/privacy-policy-travel-mate/home

![img_20180712_145818](https://user-images.githubusercontent.com/9164477/42625151-ab0ffe38-85e4-11e8-8f9e-201493207275.jpg)

**Comment by brijeshshah13** [comment]
@Swati4star I'm picking up this one.

**Comment by Swati4star** [comment]
@brijeshshah13 
After the `Fork on Github` element, add `View Contributors` list item.
Don't do anything on clicking that for now.

**Comment by Swati4star** [comment]
Also, you can change the order of elements based on their relevance as per your choice.

**Comment by brijeshshah13** [comment]
@Swati4star Alright.

**Comment by brijeshshah13** [comment]
@Swati4star Why are we converting `BugReportFragment` to activity? I mean we can use it as a fragment itself as it will be lighter as compared to activity.

**Comment by Swati4star** [comment]
@brijeshshah13 Sounds good. You can keep it as fragment only.
