### ISSUE TITLE
Change autocomplete text view to Select city button in Add trip activity

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#254]
We currently have autocomplete text view for city name. Change it to this dialog:

![](https://user-images.githubusercontent.com/24635221/42645732-6c851f6c-861c-11e8-990b-e3e71ad0d067.png)
[Reference: This was implemented in https://github.com/project-travel-mate/Travel-Mate/pull/253 for hotels activity]

### Steps to reproduce
- Go to `my trips` in the navigation drawer
- Select `+` icon

### Expected behaviour
- Remove the autcomplete textview for city name
- Change it to a button
- On selecting that button, the dialog with city names should open up

**Comment by aayushinigam** [comment]
I would like to work on this.

**Comment by Swati4star** [comment]
All the classes related to this dialog are right now in hotels package. You can move them to a different one (or create a new one: CityDialog)
