### ISSUE TITLE
Add app shortcuts for various sections

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#255]
We can have shortcuts for destinations, my trips, travel, utilities, my profile just like the screenshot below
![screenshot_20180711-224954](https://user-images.githubusercontent.com/22871961/42650540-4a67fedc-862a-11e8-98d1-4012aaeb609e.png)

Resource -
https://developer.android.com/guide/topics/ui/shortcuts

**Comment by Swati4star** [comment]
Adding shortcuts is very easy. That's why moving it from topcoder to pro

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by Swati4star** [comment]
Sure!

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/264
