### ISSUE TITLE
Prevent 2 colors from being same

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#256]
![screenshot_20180712-060153](https://user-images.githubusercontent.com/22871961/42650753-dec7d0e8-862a-11e8-9a3c-14787bac1caf.png)

In the above screenshot both cities are having the same color. Prevent this from happening?

**Comment by syedjahangirpeeran** [comment]
@Swati4star 10 cities are called in the activity and we have only 8 colors as default. It's better to add to 2 more colors and assign them uniquely rather than randomly because in worst case it might effect the performance of the app. What do you say?

**Comment by Swati4star** [comment]
Seems like a good idea. We can create an array of 10 different color values & just shuffle the elements of array. It'll be unique then

**Comment by Swati4star** [comment]
@syedjahangirpeeran Are you working on this one?

**Comment by syedjahangirpeeran** [comment]
It's up for grabs.

**Comment by Mudra01** [comment]
I would like to work on it.

**Comment by Swati4star** [comment]
Sure!

**Comment by knightcube** [comment]
Yes @Mudra01....you can work on the issue. Since no one is working on it so you can take it up. Go ahead

**Comment by Mudra01** [comment]
I did this already but the running is still disabled though the gradle build is successful.

**Comment by Mudra01** [comment]
How about using double randomization. I added the index in a list shuffled it and the got a random value and extracted the value at that index from the list?

**Comment by Swati4star** [comment]
Looks good. Keep 10 color values. Have a list of indices 0 to 9. Shuffle it. Then, extract the color value at that index.

**Comment by Mudra01** [comment]
I have done the changes and committed. I am new to open source, please guide me if I am wrong.

**Comment by Swati4star** [comment]
You are supposed to create a pull request.

**Comment by Mudra01** [comment]
I did commit directly from command line what am I supposed to do now?

**Comment by Swati4star** [comment]
@Mudra01 Connect with someone on slack on how to create a pull request or google it.
