### ISSUE TITLE
Change select text from edittext to a button

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#261]
### Steps to reproduce
Tell us how to reproduce this issue. 
- Go to `my trips` in the navigation drawer
- Click on `+` icon
- Following view opens up
<img width="330" alt="screen shot 2018-07-13 at 10 37 13 pm" src="https://user-images.githubusercontent.com/9164477/42704437-5f43e4b0-86ed-11e8-84ec-e006f55e6d91.png">

### Expected behaviour
- Change edit text to button
- Open date picker on clicking that
- Also, show the selected date below, so that the user knows which date is selected

### Actual behaviour
- Nothing happens when I click once on the select date edit text. I have to click that again to open the date picker

**Comment by f71uday** [comment]
would like to work on this!

**Comment by Swati4star** [comment]
@f71uday Sure

**Comment by f71uday** [comment]
![screenshot_20180715-003944](https://user-images.githubusercontent.com/19256444/42727616-dab96ee6-87c7-11e8-9104-202b6dffd78e.png)
Somthing like this @Swati4star

**Comment by Swati4star** [comment]
@f71uday The UI doesn't look good! Remove the icon & let there be previous text only.
Do one thing. Make `Select Date` and `Select City` be in one row (take up 1/2 of the width)

..and when user has selected the date, just show the date below the add trip button, something like
`Trip date : <date>` (Add required margin between the this view & add trip button)

**Comment by f71uday** [comment]
Ok @Swati4star

**Comment by f71uday** [comment]
![screenshot_20180715-011310](https://user-images.githubusercontent.com/19256444/42727906-58ed7bc8-87cc-11e8-9dd6-b34bb7bf8200.png)
What about this @Swati4star

**Comment by Swati4star** [comment]
Looks good. Just change the text to "Select Trip Date"
