### ISSUE TITLE
City Dialog shows only limited cities

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#262]
### Steps to reproduce
First way
- Go to `Travel`. Select `Hotels`. The following dialog opens up

Second way
- Go to `My Trips`. Select `+` icon. Select `Select City`. The dialog opens up.

![](https://user-images.githubusercontent.com/24635221/42645732-6c851f6c-861c-11e8-990b-e3e71ad0d067.png)

This dialog currently has only 10 cities. The autocomplete also uses these 10 cities only.

### Expected behaviour
- We have a number of cities on the server.
- Use the city automcomplete API to dynamically fetch those based on what user has typed.

**Comment by syedjahangirpeeran** [comment]
The way the API is coded, a maximum Number = (all cities -1) is possible, if we leave it empty then default value of 8 cities is set to it. Should change the server side code.

**Comment by mursyidah** [comment]
does it mean, the city only will show up when user type in search?

**Comment by prakhar1001** [comment]
Can I take this issue?

**Comment by weiyang94** [comment]
Can i take this issue?

**Comment by Swati4star** [comment]
Sure @weiyang94 👍

**Comment by weiyang94** [comment]
@Swati4star hi, by any chances we are allowed to access the server api? It seems like we need a new api to achieve the feature ( dynamically fetch cities based on what user has typed).

**Comment by Swati4star** [comment]
We already have an API for this. 
Try this API endpoint, `get-city-by-name/<str:city_prefix>`

**Comment by Swati4star** [comment]
Any updates @weiyang94 ??

**Comment by jddeep** [comment]
@Swati4star i would like to work on this issue.

**Comment by Swati4star** [comment]
Sure
