### ISSUE TITLE
Notification count & marked notification UI is not getting updated

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#266]
### Steps to reproduce
- Let's say you have 1 unread notification
- The bell icon will show 1 count. 
- The notifications page will show 1 card with blue outlined card (this means it's unread)
- Open that notification & press back

### Expected behaviour
- The blue line on that card should go
- On pressing back, the count on bell icon should also get updated

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.
