### ISSUE TITLE
Don't show mark all notifications as read in action bar, if there are no unread notifications

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#269]
![screenshot_20180714-194937](https://user-images.githubusercontent.com/9164477/42725592-d47697a8-87a3-11e8-8a0d-f918c46518ee.jpg)

Hide the check icon on action bar, if there are no unread notifications

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.
