### ISSUE TITLE
Don't show anything by default on the shopping screen

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#270]
### Steps to reproduce
- Select `Travel` from the navigation drawer
- Select `Hotel Booking`

It automatically searches for bags & show results.
<img width="333" alt="screen shot 2018-07-14 at 8 47 44 pm" src="https://user-images.githubusercontent.com/9164477/42725867-e4f9ecce-87a8-11e8-8bc7-9de3550dbf6f.png">

### Expected behaviour
- Don't search for anything by default
- Show this animation on the screen in the center: https://www.lottiefiles.com/373-streetby-test-loading
- Below this, write a text, `Want to shop something? Select the search icon on top`

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.
