### ISSUE TITLE
Show selected city name in Add trip 

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#272]
### Steps to reproduce
- Select `My Trips`
- Click on `+` icon
- Click on `Select a city`. Select any city

### Actual behaviour
There is no change in the UI. User doesn't get to know if the city was actually selected or not

### Expected behaviour
Show the name of city in Add trip activity

**Comment by f71uday** [comment]
On me

**Comment by Swati4star** [comment]
Sure @f71uday

**Comment by f71uday** [comment]
![screenshot_20180715-014752](https://user-images.githubusercontent.com/19256444/42728137-30a8d3c4-87d1-11e8-9f33-c93f97b23bfd.png)
is it ok @Swati4star

**Comment by Swati4star** [comment]
Looks good!
