### ISSUE TITLE
Hotel Page keeps on showing loader in case of no internet

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#275]
### Steps to reproduce
- Turn off your internet
- Select `Travel` from the navigation drawer
- Select `Hotel Booking`
<img width="350" alt="screen shot 2018-07-15 at 10 38 15 am" src="https://user-images.githubusercontent.com/9164477/42730791-5871f5e4-881b-11e8-9ee0-19fbb1cebc7b.png">

### Expected behaviour
- Show no internet animation in case of no internet
(https://github.com/project-travel-mate/Travel-Mate/blob/master/Android/app/src/main/res/raw/network_lost.json)

**Comment by f71uday** [comment]
would like to work

**Comment by Swati4star** [comment]
Sure @f71uday

**Comment by f71uday** [comment]
![screenshot_20180715-220213](https://user-images.githubusercontent.com/19256444/42735962-da0db4f8-887a-11e8-8eda-9ddee1026979.png)

**Comment by Swati4star** [comment]
See the issue description. We want the animation to be played in case of no internet.

**Comment by f71uday** [comment]
oops Sorry
