### ISSUE TITLE
Show a list of user's friends

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#285]
### What to do?
- Create a new option in the navigation drawer `My friends`
- On clicking that, open a new fragment
- That should have a list of user's friends
- The UI should be similar to that of `My Trips`. Circular profile image + write friend's name below
- On clicking that, friend's profile page should open up

### Endpoint to use
`trip-friends-all`

**Comment by aayushinigam** [comment]
I would like to work on this.

**Comment by aayushinigam** [comment]
Do we have an API where we can remove friend without providing trip Id?

**Comment by Swati4star** [comment]
No. We don't have that yet.

**Comment by aayushinigam** [comment]
Okay!
Also, the given endpoint returns user's own info along with other friends.

**Comment by Swati4star** [comment]
It shouldn't return user's own info. Will create an issue on server side for this.
