### ISSUE TITLE
Create new utilities : Currency Converter

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#286]
### What to do?
- Go to `utilities` from the navigation drawer
- Add a new section to it `Currency converter`
- On clicking that, open a new activity
- Show UI something like this
<img width="476" alt="screen shot 2018-07-17 at 3 03 04 pm" src="https://user-images.githubusercontent.com/9164477/42809161-8f8a3fb0-89d2-11e8-96cb-b784b81afd80.png">

- The country names can be a spinner. Keep the textbox below first country name to be editable. When value changes in that box, correspondingly change the value in text box below second country name.
- Don't add the last updated field, API doesn't provide that yet
- Show no internet animation, in case of no internet

### Getting list of currencies & currency code in java
https://stackoverflow.com/a/3537085/3623128

### Endpoint to use
`get-currency-conversion-rate/<str:source_currency_code>/<str:target_currency_code>`

**Comment by santoshhiremani** [comment]
Drawable size bloat generally, including all approximately 1Mb or something. Is that ok ? It will impact on apk size as well.

**Comment by Swati4star** [comment]
Yes. We can afford to increase app size by that much.

Are you working on this issue?

**Comment by santoshhiremani** [comment]
Than its fine, I have some plan about material UI, not exactly the above one but will be in vertical manner. I will share screen.

**Comment by Swati4star** [comment]
Sure. The UI doesn't need to same as the one in the description. It can vary.

**Comment by santoshhiremani** [comment]
![device-2018-09-03-143454](https://user-images.githubusercontent.com/644341/44978094-831d9580-af87-11e8-8a06-3925b60ce8d0.png)

**Comment by Swati4star** [comment]
Looks good @santoshhiremani !!

Are these countries tabs spinners? I mean, how do I change the country.

**Comment by Swati4star** [comment]
Add a drop down icon by the side of country names (or something else that makes it look like they are listviews)
Please use the endpoint mentioned in the description. We already have it.

**Comment by santoshhiremani** [comment]
Yes it will be listview with items having icon and country name on it. Oh i didn't notice that, we can use that.
