### ISSUE TITLE
Remove myself from trip

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#287]
### Steps to reproduce
- Select `My Trips` from navigation drawer
- Select any trip

### Expected behaviour
- Add a 3 dot menu in the trip info page
- There should be an option to `Remove me from trip`
- Add a confirmation dialog. 
- On clicking OK, call below endpoint. Go back to `my trips` page & the trip list should be refreshed

### Endpoint to use
`remove-user-from-trip/<int:trip_id>`

**Comment by syedjahangirpeeran** [comment]
Would like to work on this!

**Comment by syedjahangirpeeran** [comment]
Code is ready but API isn't merged yet to test.

**Comment by Swati4star** [comment]
Just create a PR for this then, and I'll test it when the code is ready
( You can pick any other issue by the time)
