### ISSUE TITLE
Move remove friend from trip to trip page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#290]
Currently, the `Remove friend from trip` option is in friend's profile page:
<img width="336" alt="screen shot 2018-07-17 at 7 58 18 pm" src="https://user-images.githubusercontent.com/9164477/42823692-c9130130-89fb-11e8-8890-08566ba69ae8.png">

### Expected behaviour
- The functionality should remain the same
- Add a cross icon (at the right) in each friend list item in trips page
- On clicking that, the same behaviour should happen (open a confirmation dialog, if the user clicks yes, remove the friend from the trip)

Change the message on the dialog from
<img width="310" alt="screen shot 2018-07-17 at 7 57 08 pm" src="https://user-images.githubusercontent.com/9164477/42823654-b7cf270a-89fb-11e8-9a28-8bd16803f089.png">
to
`Are you sure you want to remove <friend's first name> from this trip?`

**Comment by aayushinigam** [comment]
Would like to work on this.

**Comment by aayushinigam** [comment]
So cross icon has to be removed from the screen where all of friend's info is displayed?

**Comment by Swati4star** [comment]
Yes.
