### ISSUE TITLE
Shopping page shows no internet connection error in case of no results

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#291]
### Steps to reproduce
- Select `Travel` -> `Online Shopping`
- Search for something like `blaaah`

### Expected behaviour
The no results animation should be displayed

### Actual behaviour
The screen shows no internet connection animation
<img width="330" alt="screen shot 2018-07-17 at 8 06 32 pm" src="https://user-images.githubusercontent.com/9164477/42824203-f68db83e-89fc-11e8-897f-9d940cbfddd4.png">

**Comment by syedjahangirpeeran** [comment]
I'm taking this up.
