### ISSUE TITLE
Email is getting truncated in friend's profile page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#297]
<img width="314" alt="screen shot 2018-07-17 at 11 56 19 pm" src="https://user-images.githubusercontent.com/9164477/42837928-17727128-8a1d-11e8-80b3-ec164979ddab.png">

### Steps to reproduce
- Go to `My friends`
- Select any friend

### Expected behaviour
- Email should not be truncated

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.
