### ISSUE TITLE
Friends profile UI is messed up

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#307]
<img width="322" alt="screen shot 2018-07-18 at 11 50 47 pm" src="https://user-images.githubusercontent.com/9164477/42900038-793c0fb8-8ae5-11e8-8d12-94f49c0eb38f.png">

### Steps to reproduce
- Go to `my friends`
- Select any friend

### Expected behaviour
- Add spacing between icon & content

**Comment by brijeshshah13** [comment]
@Swati4star Claiming this one.
