### ISSUE TITLE
UI suggestion/ mockup for Hotel Screen

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#309]
Just designed in adobe xd. XML part is needed. We will break down the issue into smaller issues. But this is the thing that we want to achieve ultimately
![hotels](https://user-images.githubusercontent.com/22871961/42919726-f44b3080-8b30-11e8-982e-f50ca9dffe19.png)
![hotels 1](https://user-images.githubusercontent.com/22871961/42919729-f5d550fc-8b30-11e8-90a0-6e564655cf62.png)

**Comment by Swati4star** [comment]
The UI looks good. It has 2 things to be implemented:
- Bottom sheet for cities selection
- UI change in list items.

Will be creating different issues for these.

**Comment by Swati4star** [comment]
Already created issue to incorporate these...
