### ISSUE TITLE
Hotel list item UI

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#310]
### Steps to reproduce
- Select `Travel`
- Select `Hotel Booking`
- The following screen opens up:
<img width="318" alt="screen shot 2018-07-18 at 11 19 38 pm" src="https://user-images.githubusercontent.com/9164477/42921619-77eaf930-8b3a-11e8-827e-341d442a960e.png">

### Expected behaviour
- Change the list item UI to grid view, where each item looks like this:
<img width="217" alt="screen shot 2018-07-19 at 10 00 15 am" src="https://user-images.githubusercontent.com/9164477/42921657-9d6d39b6-8b3a-11e8-940a-f6f3c9cfedd4.png">

- There should be 2 elements in each row
- On selecting `Top for more details`, this should come up:
<img width="359" alt="screen shot 2018-07-19 at 10 01 48 am" src="https://user-images.githubusercontent.com/9164477/42921693-c88f109c-8b3a-11e8-871b-11b6a6d38ef5.png">

**Comment by knightcube** [comment]
We won't be needing grid view. We will show the items in a RecyclerView with a Horizontal LinearLayoutManager

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.
