### ISSUE TITLE
Remove me from trip option not working correctly

### ISSUE THREAD

**Issue by aayushinigam** [project-travel-mate/Travel-Mate#312]
![removetrip](https://user-images.githubusercontent.com/24635221/42928499-12a1c4da-8b55-11e8-8884-be9ebca3151c.gif)

### Steps to reproduce
1. Go to `My Trips`
2. Select any trip
3. Click on remove trip option

### Expected behaviour
Trip should be removed and UI of `My trips` should change accordingly.

### Actual behaviour
A toast with a long message is appeared. And on refreshing `My trips` page, weird behaviour is observed.

**Comment by syedjahangirpeeran** [comment]
API isn't merged yet.

**Comment by aayushinigam** [comment]
Oh that's the reason! Nvm I'll close the issue
