### ISSUE TITLE
Create a city restaurants page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#319]
### Steps to reproduce
- Click on any destination in home page
- Select restaurants

### Actual behaviour
A map opens up with restaurants.

### Expected behaviour
- Don't show the map
- Show a list view with restaurant items received from the API given below
- Create UI like this:
<img width="764" alt="screen shot 2018-07-21 at 12 40 15 am" src="https://user-images.githubusercontent.com/9164477/43020744-b072b758-8c7e-11e8-8a7f-47b538538ce8.png">

- Show restaurant name, cost for 2 & address at the bottom (just line in above image)
- Show rating and votes at the top right corner
- Open restaurant url on clicking the list item

### Endpoint to use
`api/get-all-restaurants/<lat>/<lon>`

### Response format
```
{
        "restaurant_id": "309629",
        "restaurant_name": "Kebab Xpress",
        "restaurant_url": "https://www.zomato.com/ncr/kebab-xpress-rohini-new-delhi?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
        "restaurant_latitude": "28.7148332542",
        "restaurant_longitude": "77.1163436025",
        "avg_cost_2": 650,
        "currency": "Rs.",
        "restaurant_image": "https://b.zmtcdn.com/data/pictures/3/301653/94acf9aa98cc36f3349f626b71afb793.jpg",
        "aggregate_rating": "3.7",
        "votes": "678",
        "address": "118, 1st Floor, Unity Metro Mall, Rohini West Metro Station, Rohini, New Delhi"
    }
```

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by syedjahangirpeeran** [comment]
I am getting Authentication error for above endpoint. `Message : Value {"detail":"Authentication credentials were not provided."}`

**Comment by Swati4star** [comment]
@prabhakar267 we are getting this error in restaurants API.

**Comment by Swati4star** [comment]
@syedjahangirpeeran It's working fine for me. You are not sending authentication token in the header.
For example:
https://github.com/project-travel-mate/Travel-Mate/blob/76ee8a059a82cbad04d587b410bee4f00ef3e465/Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoPresenter.java#L51
