### ISSUE TITLE
My Friends screen does not show all the freinds

### ISSUE THREAD

**Issue by aayushinigam** [project-travel-mate/Travel-Mate#324]
### Steps to reproduce
1. Go To `My Friends` in navigation drawer

### Expected behaviour
All friends should be shown.

### Actual behaviour
Among all the friends, one friend is missed.

### Would you like to work on the issue?
Yes.

**Comment by Swati4star** [comment]
Is this an issue with the API or android side?

**Comment by aayushinigam** [comment]
Android. I checked, to make sure that user doesn't get added to list, I added a loop and I mistakenly ran it in such a way that user gets added while last friend does not.
