### ISSUE TITLE
Replace `View on Map` from city card to `View Weather forecast`

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#325]
### Steps to reproduce
- Open `destinations` screen.
- Swipe any city card. Following view is displayed

<img width="353" alt="screen shot 2018-07-21 at 4 36 10 pm" src="https://user-images.githubusercontent.com/9164477/43034968-3437deda-8d04-11e8-8e9c-44a86ec74592.png">

### Expected behaviour
Replace `View on Map` with `View weather forecast`. On clicking that option, weather forecast screen should open up.

- Currently, the `weather forecast` screen opens up by following steps:
    - Select any destination
    - Click on weather card

**Comment by aayushinigam** [comment]
I'm taking this up!
