### ISSUE TITLE
Show no internet animation in map activity

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#328]
### Steps to reproduce
- Turn off your internet
- Select `Travel`
- Select `Real Time Locator`
- Nothing happens

### Expected behaviour
Show no internet animation

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.

**Comment by syedjahangirpeeran** [comment]
Should I show animation when user opens the real time locator by turning off internet or when the user selects the places in the dialog with no internet?

**Comment by Swati4star** [comment]
- For both the cases.
   - When user open the activity for the first time, then also, we are making an API call (i think). In that case, show the animation
   - Also, suppose, user's internet is turned off in between. So, when user selects the places & new API call is made, then also show no internet animation
