### ISSUE TITLE
Remove dialog from my trip activity

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#331]
### Steps to reproduce
- Go to `My trips`. Select any trip
- Select pencil icon by the side of trip name
- Click on ✔️ icon
- A material dialog is shown

### Expected behaviour
- Show a small progress bar only, by the side of trip name (instead of ✔️ icon)
- Remove material dialog

**Comment by aayushinigam** [comment]
Taking this up!
