### ISSUE TITLE
Add trip page keeps showing loader on no internet

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#338]
### Steps to reproduce
- Turn on your internet
- Go to `My trips` page. Select `+` icon
- Write a trip name. Select trip city & date
- turn off your internet
- Click on add trip

### Expected behaviour
- Dismiss the dialog & show no internet animation

### Actual behaviour
- The material dialog keeps on showing

**Comment by aayushinigam** [comment]
I'm taking this up!
