### ISSUE TITLE
Remove extra space after card in real time activity

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#341]
### Steps to reproduce
- Select `Travel` -> `Real time locator`
- Select any marker on the map
- The UI is:
<img width="329" alt="screen shot 2018-07-23 at 9 55 07 pm" src="https://user-images.githubusercontent.com/9164477/43089790-380111c4-8ec3-11e8-8496-f950ee069ea0.png">

### Expected behaviour
Remove the extra space after the card

**Comment by syedjahangirpeeran** [comment]
Does it mean to remove right padding or bottom padding??

**Comment by Swati4star** [comment]
Remove extra margin below the card. 

I think, the height of view at bottom is more than the height of the card.

**Comment by Mudra01** [comment]
can I work on this?

**Comment by Swati4star** [comment]
Finish the previous issue first

**Comment by syedjahangirpeeran** [comment]
Taking this up.
