### ISSUE TITLE
Getting a red line below the email id

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#344]
Describe your issue here.

<img width="309" alt="screen shot 2018-07-23 at 10 19 47 pm" src="https://user-images.githubusercontent.com/9164477/43090994-9a9b7c54-8ec6-11e8-9b65-005e3f6072aa.png">

### Steps to reproduce
- This is happening for a few email ids. You can swa@abc.com to any of your trips.
- This email id will show up in your friends page
- Click on this, & profile page would open up.

### Expected behaviour
There shouldn't be red line

### Actual behaviour
There is a red line below the email id

**Comment by syedjahangirpeeran** [comment]
I'm taking this up.
