### ISSUE TITLE
Draw a separator line between checked & unchecked items

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#350]
### Steps to reproduce
- Select `Utitlites` -> `Checklist`

### Expected behaviour
- Draw a greysih separator line between checked & unchecked items
- Change the icon before `Enter task name`
- Below the separator, line, write `x checked items` & below this, show checked items
<img width="325" alt="screen shot 2018-07-24 at 8 39 17 pm" src="https://user-images.githubusercontent.com/9164477/43147856-a8d942cc-8f81-11e8-994f-493507d9e828.png">

**Comment by supermzn** [comment]
I can take it.
> Change the icon before Enter task name

Is there any particular icon to replace this one? Should it be something more like a prompt, or something?

**Comment by Swati4star** [comment]
Sure. It's just that the current icon does not look that good. If you find something better, do replace it.

**Comment by Akramhussain4** [comment]
Can I take this?

**Comment by supermzn** [comment]
> Can I take this?

Yeah, sure

**Comment by Swati4star** [comment]
Sure @Akramhussain4 👍

**Comment by Swati4star** [comment]
will be fixed by https://github.com/project-travel-mate/Travel-Mate/issues/300
