### ISSUE TITLE
Show our loading animation instead of progress bar in Trips info page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#351]
### Steps to reproduce
- Go to `my trips`. Select any trip. 
- Following view comes up:
![screenshot_1532538612](https://user-images.githubusercontent.com/9164477/43216172-dbe6dee2-905b-11e8-9809-f49de00e5822.png)

### Expected behaviour
- Show our default loading animation, instead of progress bar

**Comment by aayushinigam** [comment]
I'll take this up
