### ISSUE TITLE
Weather icon not loading for haze condition

### ISSUE THREAD

**Issue by syedjahangirpeeran** [project-travel-mate/Travel-Mate#362]
Describe your issue here.

### Steps to reproduce
![screenshot_20180729-135724](https://user-images.githubusercontent.com/26850482/43364658-2ee6f9fa-933c-11e8-8971-ad84aa6cd05a.png)

### Expected behaviour
Haze icon should load.

### Actual behavior
No icon is being displayed.

### Would you like to work on the issue?
Yes I would like to work on this issue.

**Comment by syedjahangirpeeran** [comment]
@Swati4star

**Comment by Swati4star** [comment]
@syedjahangirpeeran I am still not getting icon for haze condition.
<img width="319" alt="screen shot 2018-07-30 at 10 58 16 pm" src="https://user-images.githubusercontent.com/9164477/43413134-cf385b86-944c-11e8-94e9-7600aa6f2671.png">

This is the response I am getting for weather info

```
{"temp":32.0,"temp_units":"C","max_temp":32.0,"min_temp":32.0,"code":721,"condensed":"Haze","description":"haze","icon":"http://openweathermap.org/img/w/50n.png","humidity":75,"humidity_units":"%","pressure":999,"pressure_units":"hPa"}
```

**Comment by syedjahangirpeeran** [comment]
There is no haze weather xml file(Vector drawable) for night.

**Comment by Swati4star** [comment]
In that case, can we have the day one only? (or do one thing, in case, we are not able to find the vector drawable, show the icon url only, which was getting displayed before)

**Comment by aayushinigam** [comment]
Same is for "dust" and "smoke". 
![dust](https://user-images.githubusercontent.com/24635221/43415402-15bc543a-9453-11e8-8edb-325e7c682bf2.png)
![smoke](https://user-images.githubusercontent.com/24635221/43415407-1719b87c-9453-11e8-99ba-626db660be7c.png)

**Comment by Swati4star** [comment]
Opening a new issue for this https://github.com/project-travel-mate/Travel-Mate/issues/377
