### ISSUE TITLE
Updates in UI and functionality of Weather Activity.

### ISSUE THREAD

**Issue by syedjahangirpeeran** [project-travel-mate/Travel-Mate#364]
Describe your issue here.

### Steps to reproduce
1) Open any city info page -> Click on weather item. The following page opens up.
![screenshot_20180729-192047](https://user-images.githubusercontent.com/26850482/43367062-cf6feff8-9364-11e8-897c-a13db4409c5d.png)

### Expected behaviour
1)Weather icon and condition should change.
2)The UI should be properly aligned.(Changing from constrained to relative layout)

### Actual behavior
1)Showing the same icon and weather condition for all cities. Only temp is changing.
2) UI alignment changes across different devices due to constrained layout.

### Would you like to work on the issue?
Yes I would like to work on this issue.

**Comment by syedjahangirpeeran** [comment]
@Swati4star.

**Comment by Swati4star** [comment]
@syedjahangirpeeran The weather icon & condition is changing for cities.  (I tried for delhi & kolkata. It is showing correct)

Is it not working correctly for few cities?

**Comment by syedjahangirpeeran** [comment]
Shouldn't the icons and weather condition in WeatherActivity match with FinalCityInfoActivity? The icons and weather condition which is shown in FinalCityInfoActivity are matching with google weather but the ones in WeatherActivity aren't.

**Comment by Swati4star** [comment]
Isn't this a server issue then?

**Comment by syedjahangirpeeran** [comment]
Ohh I got it now. The weather info shown in weatheractivity is the full day weather...whereas in finalcityinfo is current conditions.

**Comment by Swati4star** [comment]
So, you can just align the views properly in this issue.
