### ISSUE TITLE
Show notification date in notification

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#366]
### Steps to reproduce
- Press the bell icon on navigation drawer
- The notification view comes up
<img width="324" alt="screen shot 2018-07-29 at 8 31 20 pm" src="https://user-images.githubusercontent.com/9164477/43367672-69a3a9ee-936e-11e8-87a5-2c132f064e8c.png">

### Expected behaviour
- Make the size of icons a bit bigger
- Show the notification date & time in a pretty format on each notification card, like,
```
8 minutes ago
8 hours ago
8 days ago
8 months ago
8 years ago
```
### Reference:
https://stackoverflow.com/a/35858833/3623128

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.
