### ISSUE TITLE
[Checklist] Don't show delete action on action bar when there are no checked items

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#367]
### Steps to reproduce
- Select `utilities` -> `checklist`
<img width="306" alt="screen shot 2018-07-29 at 8 35 00 pm" src="https://user-images.githubusercontent.com/9164477/43367703-fe228112-936e-11e8-98b4-6a211e9222c5.png">

### Expected behaviour
- Don't show delete action on action bar when there are no checked items

**Comment by kbisht84** [comment]
hi ..I can take this one

**Comment by Swati4star** [comment]
@kbisht84 Sure. Go ahead 👍

**Comment by Swati4star** [comment]
@kbisht84 Any updates?

**Comment by kbisht84** [comment]
@Swati4star 
I have implemented it though it has a side effect.Undo functionality stopped working .I have to dig a little bit to fix that issue. Thanks

**Comment by kbisht84** [comment]
so I implemented the functionality onPrepareOptionsMenu in CheckListFragment class
now for checking the how many check boxes are clicked  I am using mVieModel.getCompletedItems .Its works fine.But the existing undo functionality breaks when I am putting this change .I tried a lot recreate view in snackbar on click listener but failed as soon as the code enters the snackbar onClickListerner view mItems value becomes 0 and wont recreate a listview .Here is the complete ChecklistFragment.java

    package io.github.project_travel_mate.utilities;

    import android.app.Activity;
    import android.arch.lifecycle.ViewModelProviders;
    import android.content.Context;
    import android.content.SharedPreferences;
    import android.os.Bundle;
    import android.preference.PreferenceManager;
    import android.support.annotation.NonNull;
    import android.support.annotation.Nullable;
    import android.support.design.widget.Snackbar;
    import android.support.v4.app.Fragment;
    import android.support.v7.app.AlertDialog;
    import android.util.Log;
    import android.view.ContextThemeWrapper;
    import android.view.LayoutInflater;
    import android.view.Menu;
    import android.view.MenuInflater;
    import android.view.MenuItem;
    import android.view.View;
    import android.view.ViewGroup;
    import android.widget.EditText;
    import android.widget.ListView;

    import java.util.ArrayList;
    import java.util.List;

    import butterknife.BindView;
    import butterknife.ButterKnife;
    import butterknife.OnClick;
    import io.github.project_travel_mate.R;
    import io.github.project_travel_mate.roompersistence.ChecklistViewModel;
    import io.github.project_travel_mate.roompersistence.Injection;
    import io.github.project_travel_mate.roompersistence.ViewModelFactory;
    import io.reactivex.android.schedulers.AndroidSchedulers;
    import io.reactivex.disposables.CompositeDisposable;
    import io.reactivex.schedulers.Schedulers;
    import objects.ChecklistItem;
    import utils.TravelmateSnackbars;

    import static utils.Constants.BASE_TASKS;
    import static utils.Constants.IS_ADDED_INDB;

    public class ChecklistFragment extends Fragment implements TravelmateSnackbars {

    @BindView(R.id.listview)
    ListView listview;
    private Activity mActivity;
    private ChecklistViewModel mViewModel;
    private final CompositeDisposable mDisposable = new CompositeDisposable();
    private View mChecklistView;
    private List<ChecklistItem> mItems = new ArrayList<>();

    public ChecklistFragment() {
    }

    public static ChecklistFragment newInstance() {
        ChecklistFragment fragment = new ChecklistFragment();
        return fragment;
    }

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        mChecklistView = inflater.inflate(R.layout.fragment_check_list, container, false);

        ButterKnife.bind(this, mChecklistView);

        ViewModelFactory mViewModelFactory = Injection.provideViewModelFactory(mActivity);
        mViewModel = ViewModelProviders.of(this, mViewModelFactory).get(ChecklistViewModel.class);

        attachAdapter();


        return mChecklistView;
    }


    @OnClick(R.id.add)
    void onClick() {
        AlertDialog.Builder builder = new AlertDialog.Builder(mActivity);
        LayoutInflater inflater = (mActivity).getLayoutInflater();
        builder.setTitle("Add new item");
        builder.setCancelable(false);
        final View dialogv = inflater.inflate(R.layout.dialog, null, false);
        builder.setView(dialogv)
                .setPositiveButton("OK", (dialog, id1) -> {
                    EditText e1 = dialogv.findViewById(R.id.task);
                    if (!e1.getText().toString().equals("")) {
                        ChecklistItem checklistItem = new ChecklistItem(e1.getText().toString(), String.valueOf(0));
                        mDisposable.add(mViewModel.insertItem(checklistItem)
                                .subscribeOn(Schedulers.io())
                                .observeOn(AndroidSchedulers.mainThread())
                                .subscribe());
                    }
                });
        builder.create();
        builder.show();
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setHasOptionsMenu(true);

    }

    //get called every time whenever invalidateMenuoptions get called
    @Override
    public void onPrepareOptionsMenu(Menu menu) {
        super.onPrepareOptionsMenu(menu);
        hideShowMenuItem();
        MenuItem item = menu.findItem(R.id.action_delete);

        if (mItems.size() > 0)
            item.setVisible(true);
        else
            item.setVisible(false);


    }

    //get called only once
    @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
        getActivity().getMenuInflater().inflate(R.menu.checklist_menu, menu);
        getActivity().invalidateOptionsMenu();


    }



    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.action_delete :
                initiateDeletion();
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    private void attachAdapter() {

        SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(mActivity);
        SharedPreferences.Editor editor = sharedPreferences.edit();
        //First time users
        String isAlreadyAdded = sharedPreferences.getString(IS_ADDED_INDB, "null");
        if (isAlreadyAdded.equals("null")) {
            for (int i = 0; i < BASE_TASKS.size(); i++) {
                ChecklistItem checklistItem = new ChecklistItem(BASE_TASKS.get(i), String.valueOf(0));
                mDisposable.add(mViewModel.insertItem(checklistItem)
                        .subscribeOn(Schedulers.io())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe());
            }
            editor.putString(IS_ADDED_INDB, "yes");
            editor.apply();
        }
        mDisposable.add(mViewModel.getSortedItems()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(items -> listview.setAdapter(new ChecklistAdapter(mActivity, items, mViewModel))));



    }

    private void hideShowMenuItem() {
        mDisposable.add(mViewModel.getCompletedItems()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(items -> {
                    mItems.clear();
                    mItems.addAll(items);
                }));
    }


    @Override
    public void onAttach (Context context) {
        super.onAttach(context);
        mActivity = (Activity) context;
    }

    /**
     * Initiates deletion of completed tasks by showing
     * an alert dialog asking the user to confirm deletion
     */
    public void initiateDeletion() {
        //First add all completed tasks in mItems
        //so that on clicking undo,tasks can added again

        //Log.i("After getCompleted1", "Total disposable " + mDisposable.size());

        hideShowMenuItem();
        Log.i("ChecklistFragment", "Total items " + mItems.size());
        //Log.i("After getCompleted2", "Total disposable " + mDisposable.size());

        //set AlertDialog before deleting all tasks
        ContextThemeWrapper crt = new ContextThemeWrapper(mActivity, R.style.AlertDialog);
        AlertDialog.Builder builder = new AlertDialog.Builder(crt);
        builder.setMessage(R.string.delete_tasks)
                .setPositiveButton(R.string.positive_button,
                        (dialog, which) ->
                        deleteCompletedTasks()
                    )
                .setNegativeButton(android.R.string.cancel,
                        (dialog, which) -> {
                            //do nothing on clicking cancel
                    });
        builder.create().show();
    }

    /**
     * Deletes completed tasks from database and provides user
     * the option to undo this task.
     */
    private void deleteCompletedTasks() {

        //deletes all completed task from database
        Log.i("ChecklistFragment", "Total items " + mItems.size());
        mDisposable.add(mViewModel.deleteCompletedTasks()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe());

        Log.i("ChecklistFragment", "Total items " + mItems.size());
        //Log.i("ChecklistFragment", "Total items " + mItems.size());
        //creates a snackbar with undo option
        TravelmateSnackbars.createSnackBar(mChecklistView.findViewById(R.id.fragment_checklist),
                R.string.deleted_task_message,
                Snackbar.LENGTH_LONG)
                .setAction(R.string.undo, v -> {
                    //v.getRootView();
     //                    getActivity().invalidateOptionsMenu();
    //                    hideShowMenuItem();
                    for (int i = 0; i < mItems.size(); i++) {
                        //adds all completed task in database again
                        ChecklistItem checklistItem = new ChecklistItem(mItems.get(i).getName(), String.valueOf(1));
                        Log.i("CheckListItem ", "checklistItem " + checklistItem.getName());
                        mDisposable.add(mViewModel.insertItem(checklistItem)
                                .subscribeOn(Schedulers.io())
                                .observeOn(AndroidSchedulers.mainThread())
                                .subscribe());

                    }

                })
                .setActionTextColor(getResources().getColor(R.color.colorPrimary))
                .show();





    }

}

**Comment by kbisht84** [comment]
Let me know your thoughts Thanks

**Comment by Swati4star** [comment]
Can you just create a PR, and I will look into that directly then.

**Comment by kbisht84** [comment]
Sure will do

**Comment by kbisht84** [comment]
@Swati4star 
so as you suggested I created the private mMenu in method onCreateOptionsMenu and tried to hide/unhide delete action from there itself .I have couple of questions 1.Are we not using mItems value to hide/unhide delete action item. 2.If yes then how private Menu mMenu only can be used to hide/unhide the item? a little explanation would be helpful thanks a lot

**Comment by Swati4star** [comment]
@kbisht84 Sorry for the late reply. Did creating private menu variable helped?

**Comment by nitinnatural** [comment]
@Swati4star I have fixed this issue and created a PR. Have a look.
