### ISSUE TITLE
UI Bug in map activity

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#371]
### Steps to reproduce
- Select any city. Select `Hangout` or any other map item
- Following UI comes up:
<img width="322" alt="screen shot 2018-07-30 at 10 48 17 pm" src="https://user-images.githubusercontent.com/9164477/43412417-c805a06e-944a-11e8-9e70-c86ade7169ac.png">

### Expected behaviour
- There is space between card item & right edge of the screen. Remove that.
- Add margin between `more` button & right edge of the card
- Make `Locate` and `More` button smaller
- Change the color of blue marker items to orange (the same as the colour on the more button). The blue markers does not look that distinguished on the map

**Comment by syedjahangirpeeran** [comment]
Taking this up.
