### ISSUE TITLE
Update active marker place in the view when marker is selected

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#372]
### Steps to reproduce
- Select any city, Go to any map item
<img width="320" alt="screen shot 2018-07-30 at 10 53 15 pm" src="https://user-images.githubusercontent.com/9164477/43412592-5eba1b20-944b-11e8-8b14-075eec808bc2.png">

### Expected behaviour
When I click on any marker on the map:
- the name of place below the map should also get updated.
- the active marker should also change to the newly clicked marker

**Comment by aayushinigam** [comment]
I'll take this up
