### ISSUE TITLE
Hotel List item is overlapping on expanding

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#382]
### Steps to reproduce
- Select `Travel` -> `Hotel Booking`
- The view overlaps when items in the first column are expanded

<img width="317" alt="screen shot 2018-07-31 at 11 37 35 pm" src="https://user-images.githubusercontent.com/9164477/43478145-bc2ce2b8-951a-11e8-90e7-6fcbcc3e489a.png">

### Expected behaviour
It shouldn't overlap

**Comment by knightcube** [comment]
I think we can use this library for now - https://github.com/AAkira/ExpandableLayout/blob/master/README.md

**Comment by santoshhiremani** [comment]
Can i ?

**Comment by santoshhiremani** [comment]
https://project-travel-mate.herokuapp.com/api/get-places/19.076000/72.877700/accommodation endpoint is throwing 500 error in getHotelList method so i'm not able get hotel list from none of the cities. please can you check this with backend team?

**Comment by Swati4star** [comment]
@prabhakar267 look into it!
There might be problem with API keys.

**Comment by prabhakar267** [comment]
@santoshhiremani The API is fixed, let me know if you face any problem regarding the API

**Comment by Balram02** [comment]
i would like to work on this...  can i? @Swati4star

**Comment by Swati4star** [comment]
@santoshhiremani Are you looking into this?

**Comment by santoshhiremani** [comment]
Not now if somebody willing take, you can....

**Comment by Swati4star** [comment]
@Balram02 You can work on this

**Comment by Balram02** [comment]
Thanks... @Swati4star will send PR soon
