### ISSUE TITLE
Change the friends page UI to have 3 friends in a row

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#384]
### Steps to reproduce
- Go to `My friends` page

<img width="323" alt="screen shot 2018-07-31 at 11 47 25 pm" src="https://user-images.githubusercontent.com/9164477/43478698-3139f734-951c-11e8-9ee3-5a579e1ce4c5.png">

### Expected behaviour
Change the number of elements in a row from 2 to 3.

**Comment by syedjahangirpeeran** [comment]
Taking this up.
