### ISSUE TITLE
Add darker background to restaurant items

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#387]
### Steps to reproduce
- Select any city, go to `Restaurants`

### Expected behaviour
The background should be dark. Similar to utilities or travel cards
<img width="328" alt="screen shot 2018-08-01 at 1 10 50 pm" src="https://user-images.githubusercontent.com/9164477/43508057-766d51c8-958c-11e8-9c26-9d2ca66d9919.png">

### Actual behaviour
The background is light, which makes text not visible that much
<img width="316" alt="screen shot 2018-08-01 at 1 10 41 pm" src="https://user-images.githubusercontent.com/9164477/43508073-86204b3e-958c-11e8-8f1c-d90efca4cdb4.png">

**Comment by nikhilbansal97** [comment]
@Swati4star I'd like to work on this!

**Comment by mursyidah** [comment]
i would like to work on this issue

**Comment by Swati4star** [comment]
Sure @mursyidah 👍

**Comment by mursyidah** [comment]
okay, it try to push it by creating another branch, but i got

 ': The requested URL returned error: 403

**Comment by Swati4star** [comment]
You are having issues with creating a PR?

**Comment by mursyidah** [comment]
yes

**Comment by Swati4star** [comment]
Can you post the exact error? Please try to google the git related errors.

**Comment by mursyidah** [comment]
i got this error,

remote: Permission to project-travel-mate/Travel-Mate.git denied to mursyidah.
fatal: unable to access 'https://github.com/project-travel-mate/Travel-Mate.git/': The requested URL returned error: 403

**Comment by Swati4star** [comment]
You should fork the repo & create a branch in that repo. And then create a PR.

You don't have permission to write in this repository

**Comment by mursyidah** [comment]
alright get it
