### ISSUE TITLE
Refactor destinations module

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#39]
As mentioned in the hierarchy in [this](https://github.com/Swati4star/Travel-Mate/blob/master/Features.md) file.

description and fun facts are already there in *destinations* folder.
Move `Tweets` and `PlacesOnMap` activities also to this folder.

**Comment by jvretamero** [comment]
Is this issue about moving classes between packages? Can you give more information?

**Comment by Swati4star** [comment]
Take reference from https://github.com/Swati4star/Travel-Mate/pull/41

**Comment by Swati4star** [comment]
Fixed in 0e84ab188bff8cae7e290eefc076c96054ce7d18
