### ISSUE TITLE
Changes in UI of Profile Page

### ISSUE THREAD

**Issue by syedjahangirpeeran** [project-travel-mate/Travel-Mate#391]
Describe your issue here.

### Steps to reproduce
Open profile page in 6 inches wide emulator.
### Expected Changes
Convert all LinearLayouts to Relative Layouts and properly align them.

### Actual behaviour
UI is messed up
![screenshot_1533132714](https://user-images.githubusercontent.com/26850482/43528775-6196dab8-95c7-11e8-96b6-74ea7d707f25.png)

### Would you like to work on the issue?
Yes, I would like to work on this issue.

**Comment by syedjahangirpeeran** [comment]
@Swati4star.

**Comment by Swati4star** [comment]
Is this just for user's profile or friend's profile also?

**Comment by syedjahangirpeeran** [comment]
It's for friend's profile also.

**Comment by Swati4star** [comment]
The issue is,
- The camera icon is not on the top of the profile photo
- The pencil icon should be at the right edge.
Anything else I am missing?

**Comment by Swati4star** [comment]
You can fix #383 also in this issue, if you want.

**Comment by syedjahangirpeeran** [comment]
The UI is not centered and also when I change status and username the pencil is icon is moving to the right most side.
