### ISSUE TITLE
Remove left margin from `cities visited` in user's profile

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#401]
<img width="324" alt="screen shot 2018-08-03 at 7 57 13 pm" src="https://user-images.githubusercontent.com/9164477/43648251-809f0016-9757-11e8-9cb0-20dbb883b829.png">

### Steps to reproduce
- Select your profile from the navigation drawer

**Comment by syedjahangirpeeran** [comment]
From the title or RecyclerView???

**Comment by Swati4star** [comment]
Recycler view

**Comment by syedjahangirpeeran** [comment]
Sorry forgot to claim it first.
