### ISSUE TITLE
Remove the animation by default & change it to a button

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#403]
#### Issue 1 
- Select `Travel`. Go to `online Shopping`
<img width="339" alt="screen shot 2018-08-03 at 8 36 36 pm" src="https://user-images.githubusercontent.com/9164477/43650258-f2cdf444-975c-11e8-91ab-3649822a96af.png">

#### Issue 2 
- Select `Travel`. Go to `Hotel`
<img width="324" alt="screen shot 2018-08-03 at 8 36 10 pm" src="https://user-images.githubusercontent.com/9164477/43650236-e26109b6-975c-11e8-8b67-cc73a949fc78.png">

#### Issue 3 
- Select `Utilities`. Go to `Weather forecast`
<img width="331" alt="screen shot 2018-08-03 at 8 36 59 pm" src="https://user-images.githubusercontent.com/9164477/43650273-fe6a163e-975c-11e8-98a0-76a1a78b6c3a.png">

### Expected behaviour
The animation makes it feel like, something is loading. So, remove the animation by default, and
#### Issue 1 
- Remove the animation & add nothing there

#### Issue 2 & 3
- add a button (circular in shape), with text `Select City`
- On clicking this, the city dialog should open up

**Comment by nikhilbansal97** [comment]
@Swati4star I'd like to work on this! 😄

**Comment by Swati4star** [comment]
Sure @Diksha2008 👍

**Comment by nitinnatural** [comment]
@Swati4star @Diksha2008 Any progress here? if not, I would like to pick this up.

**Comment by Diksha2008** [comment]
@nitinnatural working on it!
