### ISSUE TITLE
Friend name is getting truncated if it is multiline

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#405]
See the screenshot below:
<img width="324" alt="screen shot 2018-08-03 at 8 45 30 pm" src="https://user-images.githubusercontent.com/9164477/43650740-385ea20a-975e-11e8-8e97-78e95e90fe3e.png">

Also,
If there are more than 9 friends (more than 3 rows), we are not able to view them all at once. There is some extra view in the bottom

**Comment by stupidly-logical** [comment]
What changes do you suggest?

**Comment by Swati4star** [comment]
@stupidly-logical Allow it to be multiline. The row height should increase in that case.

**Comment by stupidly-logical** [comment]
Okay. I am looking into it.

**Comment by stupidly-logical** [comment]
@Swati4star as the android project is in subfolder of the repo, what's the best way to work using android studio in this structure?

**Comment by Swati4star** [comment]
@stupidly-logical You can import the `Android` folder in the android studio.
[ https://github.com/project-travel-mate/Travel-Mate/wiki ]

**Comment by stupidly-logical** [comment]
Imported but now I am not able to run it on device. Run/Debug config has no module.

**Comment by Swati4star** [comment]
There must be issue with android studio sdk in your system. 
There are no errors with the project. We have automated build also to ensure that.

**Comment by stupidly-logical** [comment]
Any suggestions for fixing it? I am able to build every other repo/project BTW.

**Comment by Balram02** [comment]
its showing perfectly fine in my device, but when i scroll suddenly all friends gets vanished and some times it behaves abnormal.. below is the screenshot.
Will send PR soon regarding this issue.
<img src="https://user-images.githubusercontent.com/35597029/47259582-bcbf4700-d4c8-11e8-9ba0-abc5988bbd64.png" width=400 >
