### ISSUE TITLE
Create single restaurant Description page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#413]
### Steps to reproduce
- Go to any city page -> `Restaurants`
- The UI looks like this
<img width="340" alt="screen shot 2018-08-07 at 11 51 06 pm" src="https://user-images.githubusercontent.com/9164477/43794714-c85d226e-9a9c-11e8-9789-b7d301f0d2c0.png">

### Expected behaviour
- Open up a new activity on clicking any card. That card should have the restaurant details received from the API

### Endpoint to use
`get-restaurant/<int:restaurant_id>`
https://github.com/project-travel-mate/server/issues/110

**Comment by valericaplesu** [comment]
Hi @Swati4star how should look the new screen? (RestaurantDetailsActivity)

**Comment by Swati4star** [comment]
@valericaplesu We don't have any UI mockups for this. Create a basic UI from the information received. 
This is the sample info we will receive
```
{
    "restaurant_id": 4,
    "restaurant_name": "China 1",
    "restaurant_url": "https://www.zomato.com/dummy/china-1-1-aaaa?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "restaurant_address": "G 05, Morya Landmark 1, Off Link Road, Andheri Lokhandwala, Andheri West, Mumbai, AAAA, Dummy",
    "restaurant_longitude": 28.88,
    "restaurant_latitude": 73.99,
    "avg_cost_2": 400,
    "price_range": 4,
    "currency": "",
    "featured_image": "",
    "user_aggregate_rating": 0,
    "user_rating_votes": 0,
    "is_delivering_now": false,
    "has_table_booking": false,
    "cuisines": "Chinese, Indian",
    "phone_numbers": ""
}
```

Add scrollable image at top (similar to city info page)
then, restaurant name & add more info below that.

**Comment by valericaplesu** [comment]
@Swati4star got it. I'm working on it

**Comment by valericaplesu** [comment]
@Swati4star can I use Kotlin? it surely simplify things

**Comment by Swati4star** [comment]
Can we use java only for this? We don't want combination of both in a single project

**Comment by valericaplesu** [comment]
> Can we use java only for this? We don't want combination of both in a single project

That's the beauty of Kotlin, it works perfectly with Java and the other way around. And definitely we can improve a lot especially with the help of async(). I'll do the pull request with it, and if you do not agree I can convert it back to Java :(

**Comment by Swati4star** [comment]
Sure. Go ahead with Kotlin :)
