### ISSUE TITLE
Use vector drawables instead of PNGs

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#414]
There are a lot of PNGs being used in the code. Replace them with equivalent xml drawable files

### Reference
https://sendeyo.com/onlineconverter/en/image-png/xml

**Comment by nikhilbansal97** [comment]
@Swati4star  I'd like to work on this.

**Comment by Swati4star** [comment]
Few pngs are still there...

**Comment by Rita-Okonkwo** [comment]
I'm working on this tomorrow

**Comment by thedevelopersanjeev** [comment]
Hi Rita, you can start working on issues 1 March 2019 as coding phase for GSSoC starts from 1 March 2019.

**Comment by Rita-Okonkwo** [comment]
Alright thank you for the information

**Comment by lifeLessCoder** [comment]
Hey! Can I start working on this issue?

**Comment by Swati4star** [comment]
sure @lifeLessCoder

**Comment by lifeLessCoder** [comment]
okay

**Comment by lifeLessCoder** [comment]
I'm not able to convert pngs to XML using the website mentioned above. Can I use 
Icons from flaticon to do so?

Reference
https://www.flaticon.com

**Comment by Swati4star** [comment]
if you see the code, we now dont have flags images in the drawable folder. 
You can convert other images to vector drawables

**Comment by lifeLessCoder** [comment]
okay!

**Comment by lifeLessCoder** [comment]
Done! @Swati4star

**Comment by prabhakar267** [comment]
Trackign in #711
