### ISSUE TITLE
Add a forget password link in the login/signup page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#415]
### Expected behaviour
- Add a new link at the bottom of Login/Signup page :  `Forgot Password` 
- On clicking this link, a new page should open up with an edit text & `submit` button to allow users to type `email id`
- Check for validity of email id (Similar to login or signup email fields)
- When submit is clicked, show a new page
- This page should show up a message : `A reset code has been sent to your email id <email id>. Please enter it here`. The code is a 5-digit number. (Create UI for this)
<img width="307" alt="screen shot 2018-08-08 at 12 02 25 am" src="https://user-images.githubusercontent.com/9164477/43795235-5cc09f48-9a9e-11e8-823c-4543e3a7dc0e.png">

Ignore the `password will reset in ...` line.

- On clicking continue, open up the dialog to  update password. This dialog should have `new password` & `confirm new password` option.

### Info
We just need the UI for this now. APIs will be integrated in the next step.

**Comment by anirudh8860** [comment]
Can you provide with drawables?

**Comment by Swati4star** [comment]
Drawables for what?

**Comment by anirudh8860** [comment]
Do you want a page exactly shown above or like that?

**Comment by Swati4star** [comment]
Maybe, not exactly the same, But something similar to this UI (plus the other features mentioned in the issue description)

**Comment by amy6** [comment]
I'd like to work on this if not taken already.

**Comment by Swati4star** [comment]
Sure. You can work on this one.
