### ISSUE TITLE
Add cities visited labels in friend's profile

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#416]
### Steps to go to friend's profile
- Go to `My Friends` from the navigation drawer
- Click on any friend

### Expected behaviour
Below the friend's profile photo, show the labels of the cities visited by the user.
labels should look something like GitHub label only (with city name). Assign any random color to the label.
<img width="64" alt="screen shot 2018-08-08 at 12 18 48 am" src="https://user-images.githubusercontent.com/9164477/43796027-ad03041c-9aa0-11e8-8201-7b6a4d5e6d70.png">

### Endpoint to use
`get-trip-cities/<int:user_id>`
https://github.com/project-travel-mate/server/issues/104

**Comment by nikhilbansal97** [comment]
Can I work on this??

**Comment by nikhilbansal97** [comment]
Okay cool. I'll work on this issue then 👍

**Comment by nikhilbansal97** [comment]
@Swati4star How do I add friends?? I am trying to add friend to a trip and it shows "Please Select a valid friend to add" snackbar

**Comment by Swati4star** [comment]
start type an email id like...`swati@gmail.com`.
 name suggestions will start showing up in the autocomplete drop down.
Select the name from there.
Then, select add friend

**Comment by nikhilbansal97** [comment]
@Swati4star This is the url I am hitting to get the trips data for a user: https://project-travel-mate.herokuapp.com/api/get-trip-cities/552 It is returning an html response. Is there something that I am missing??

<img width="1280" alt="screen shot 2018-10-13 at 8 38 45 pm" src="https://user-images.githubusercontent.com/18311406/46906880-fe2f7f80-cf27-11e8-9256-6db0ec968163.png">

**Comment by Swati4star** [comment]
HI @nikhilbansal97 ! Really sorry, I didnt know that url endpoint wad changed.
Try out this one https://project-travel-mate.herokuapp.com/api/get-visited-city/1

**Comment by nikhilbansal97** [comment]
@Swati4star Thanks that worked. I had another doubt. I have completed the implementation and was about to raise a PR but was running tests:
1. `./gradlew checkstyle`
2. `./gradlew assembleDebug assembleRelease`
For both the tests, it shows an `NullPointerException` but not in any of the project files.

<img width="840" alt="screen shot 2018-10-15 at 12 42 04 am" src="https://user-images.githubusercontent.com/18311406/46920991-90f91880-d013-11e8-836c-bafdb14e81be.png">

**Comment by Swati4star** [comment]
We have included checkstyle in the Android build process only. So, the above is not required.
You can create a PR :)
...and travis will check for failure 
@nikhilbansal97
