### ISSUE TITLE
Replace `Google Maps` with `Open Street Maps`

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#417]
There are a lot of places in the application, where we are using **Google Maps**. Remove the use of google maps, and replace it with `Open Street Maps`

### Reference
https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library

**Comment by santoshhiremani** [comment]
I'd like to work on this if not assigned already.

**Comment by Swati4star** [comment]
It's not already assigned, you can work on it! @santoshhiremani

**Comment by santoshhiremani** [comment]
Do assign to me...Starting..

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/450
