### ISSUE TITLE
[New Feature]Add an in-app Language Translator in Utilities section

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#425]
In most cases, travelers are not too familiar with a regional language and suffer while trying to communicate in a broken manner. So since the backend is in python we can start some work on this Feature.

**Comment by Swati4star** [comment]
Why are you creating this issue here? This is a backend issue.

**Comment by knightcube** [comment]
We can actually directly use this api - https://cloud.google.com/translate/docs/reference/libraries#client-libraries-install-java
