### ISSUE TITLE
[New Feature] Add a Trip Review feature in the My Trips section

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#426]
Include a button in the details of a trip in My Trips section labeled as "Review your trip"
- Tap on button > Write a review (string format) > Send to backend
-  Make a new section for each city called Trip Reviews and display all reviews in this section
- Trip reviews can be customized to share publicly or only with friends

**Comment by Swati4star** [comment]
@knightcube We don't have backend support for this. So, before adding such issue in Android repo,  create it on the server repo first.

We can't start working on this.

**Comment by Swati4star** [comment]
It requires a lot of backend support first. Let's build that first & then, reopen this issue.
