### ISSUE TITLE
Parse the json in `City History` page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#427]
<img width="322" alt="screen shot 2018-08-09 at 9 15 19 pm" src="https://user-images.githubusercontent.com/9164477/43910062-66b84588-9c19-11e8-8467-44df4937e66a.png">

### Steps to reproduce
- Select any city. Select `City History`

### What to do?
For the subelements also, we have a nested json. The json is not parsed. 

### Reference : To get a list of keys from a json object
https://stackoverflow.com/questions/19195492/extracting-keys-from-a-jsonobject-using-keyset

**Comment by anirudh8860** [comment]
Ok will do
