### ISSUE TITLE
Open up city image in full screen when it is selected

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#428]
### Steps to reproduce
- Select any city or go to any trip

### Expected behaviour
- On clicking the city image, that image should open up in a new activity in few screen

### Some info
This behaviour is present in the profile photo. Go to any friend's profile or your profile and select profile photo, it opens up in new activity in full screen

**Comment by aayushinigam** [comment]
I would like to work on this.
