### ISSUE TITLE
UI changes in Add trip page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#429]
### Steps to reproduce
Current Add trip page looks like this:
<img width="325" alt="screen shot 2018-08-09 at 9 23 50 pm" src="https://user-images.githubusercontent.com/9164477/43910504-a0d22378-9c1a-11e8-9f26-bb7719179d94.png">

### Expected behaviour
Change it to something like this:
<img width="487" alt="screen shot 2018-08-09 at 9 24 56 pm" src="https://user-images.githubusercontent.com/9164477/43910525-b11c6bee-9c1a-11e8-965b-3fcb626e002c.png">

- No need to add `Add Destination` option. (We only have 1 destination per trip)
- Also, we don't have end trip option, so no need to include that.

**Comment by anirudh8860** [comment]
Do you just need UI change or code change as well?

**Comment by Swati4star** [comment]
The final output should be working.
So, yes, it will require code changes too.

**Comment by anirudh8860** [comment]
Meaning Calender popup along with destination

**Comment by Swati4star** [comment]
Calendar does pop up now also.

**Comment by anirudh8860** [comment]
i'll do it
