### ISSUE TITLE
Incorrect Date shown

### ISSUE THREAD

**Issue by anirudh8860** [project-travel-mate/Travel-Mate#436]
When a new trip is added by user, the trip date selected and displayed are incorrect
### Steps to reproduce
1. Go to My Trips.
2. Add a new trip by clicking on "+" button.
3. Click on "Select Trip Date".
4. Select the trip date from calendar popup.

### Expected behaviour
Trip date should show selected date.

### Actual behavior
Trip date shown is one month prior from selected date.

### Would you like to work on the issue?
Yes

**Comment by Swati4star** [comment]
Go ahead! You van work on this issue.
