### ISSUE TITLE
Notification page : The time should show month (not months) when it is single

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#439]
<img width="124" alt="screen shot 2018-08-15 at 11 23 14 am" src="https://user-images.githubusercontent.com/9164477/44133506-b52e9cb8-a07d-11e8-86b6-18815bdeb3d8.png">

This should be `1 month`

**Comment by syedjahangirpeeran** [comment]
Would like to work on this.
