### ISSUE TITLE
every activity/fragment should have getStartIntent() / getNewInstance()

### ISSUE THREAD

**Issue by gugakatsi** [project-travel-mate/Travel-Mate#44]
for example : 

in Activity : 

```
public static Intent getStartIntent(Context context, User user) {
	Intent intent = new Intent(context, ThisActivity.class);
	intent.putParcelableExtra(EXTRA_USER, user);
	return intent;
}
```

or in Fragment 

```
public static UserFragment newInstance(User user) {
	UserFragment fragment = new UserFragment();
	Bundle args = new Bundle();
	args.putParcelable(ARGUMENT_USER, user);
	fragment.setArguments(args)
	return fragment;
}
```

**Comment by stupidly-logical** [comment]
May I work on this?

**Comment by gugakatsi** [comment]
@stupidly-logical sure , go ahead with , make sure u create new branch

**Comment by stupidly-logical** [comment]
One issue I encountered while solving this issue is that Activities and Fragments file names are not ending with "Activity"/"Fragment" respectively.
Your views on this : @Swati4star  @gugakatsi ?

**Comment by gugakatsi** [comment]
@stupidly-logical yeah , they should be , u mean SomeActivity.java right...

**Comment by stupidly-logical** [comment]
@gugakatsi yes exactly, I'll fix this too. @Swati4star ?

**Comment by gugakatsi** [comment]
@stupidly-logical i like that idea.

**Comment by Swati4star** [comment]
@stupidly-logical 
Sure, go ahead with it. Make sure the changes are in accordance with the checkstyle rules.

**Comment by Swati4star** [comment]
@stupidly-logical Any updates on this issue? Are you working on this?

**Comment by stupidly-logical** [comment]
@Swati4star Yes, I'll send PR soon

**Comment by Swati4star** [comment]
this issue is being solved in https://github.com/Swati4star/Travel-Mate/pull/50
thanks @stupidly-logical

**Comment by brijeshshah13** [comment]
@Swati4star Can I start working on this?

**Comment by Swati4star** [comment]
Sure @brijeshshah13 👍

**Comment by brijeshshah13** [comment]
@Swati4star What is `User` as stated in the example in the beginning?

**Comment by Swati4star** [comment]
Specify the line of code you are referring to

**Comment by brijeshshah13** [comment]
Parameter passed in `public static Intent getStartIntent(Context context, User user)` and `public static UserFragment newInstance(User user)`

**Comment by Swati4star** [comment]
That was just an example.  
For city related fragment/activities, pass `City` object
Whatever seems to be relevant to be passed to the corresponding activity/fragment, add that parameter. If nothing seems to be relevant, don't add any parameter.
@brijeshshah13

**Comment by brijeshshah13** [comment]
@Swati4star Thinking it in detail, do we really require `getStartIntent()` for Activities because when we will be wanting an Intent for a certain activity, we are passing the Context and reference of the Activity anyway. Plus, if we implement this for Acitivities, we will be creating 2 copies of Intent even though one is enough. To the best of my knowledge, I think we should implement this functionality only for Fragments. Please share your views.

**Comment by Swati4star** [comment]
@brijeshshah13 
The benefit of creating it for activities:
- Cleaner code
- Less code repetition. (In case `n` activities are calling `X` activity)
- Promotes abstraction: handle complexity by hiding unnecessary details from other classes(Activities). 

And about 2 copies, we won't be having 2 copies. At any point in time, there will be only 1 copy in the memory.

**Comment by brijeshshah13** [comment]
@Swati4star Thank you for listing down the advantages. On it.

**Comment by brijeshshah13** [comment]
@Swati4star By using the same method name `getStartIntent()` for all activities will result into confusion as it will be directly called, so shall I add the name of the activity in the method?

**Comment by Swati4star** [comment]
the method will be static, so it will be called using the ClassName of particular activity/fragment. I don't think it will create confusion. Rather, it would make it easier.

**Comment by brijeshshah13** [comment]
That will be for Fragments, when I use `activity_name.getStartIntent()`, Android Studio tells me to directly refer the method without using the reference of activity `getStartIntent()` as it will directly import that method. Still, I can use the former syntax though. Shall I go with it?

**Comment by Swati4star** [comment]
Yes, Use `activity_name.getStartIntent()` this syntax. Will be more readable.

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/144
