### ISSUE TITLE
implement social logins

### ISSUE THREAD

**Issue by santoshhiremani** [project-travel-mate/Travel-Mate#447]
To get rid of that cumbersome step of telling users to create a user profile, social login can be implemented with these connectors.
- Facebook
- Google+
- Twitter

I'm not sure back end can accommodate this 
@Swati4star please let me in case you have it in your feature list.

**Comment by Swati4star** [comment]
We don't have this in our feature list yet.
This issue is similar to https://github.com/project-travel-mate/Travel-Mate/issues/105

**Comment by jddeep** [comment]
@Swati4star is it available for gssoc19? I would like to work with this.

**Comment by Swati4star** [comment]
No. It's not. We are not sure if we are going to implement this. You can leave this for now.

**Comment by prabhakar267** [comment]
As discussed in #105 we do not plan on adding social login feature.
Closing this.
