### ISSUE TITLE
add search bar on currency selector list

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#454]
### Steps to reproduce
- Go to Utilities -> Currency converter
<img width="324" alt="screen shot 2018-09-03 at 7 44 50 pm" src="https://user-images.githubusercontent.com/9164477/44991548-048a1d80-afb2-11e8-9091-0d0e16a5bcc4.png">

### Expected behaviour
- Add a search bar to top.

**Comment by santoshhiremani** [comment]
Bringing PR shortly on this...
