### ISSUE TITLE
Add Copywrite and FAQ's

### ISSUE THREAD

**Issue by santoshhiremani** [project-travel-mate/Travel-Mate#456]
Some document such as FAQs, About Us and Privacy Policy is missing.
Please let me know if you want me to do so.

**Comment by Swati4star** [comment]
We already do have a privacy policy. 
What will you add in FAQs?

**Comment by santoshhiremani** [comment]
We can have some compiled questions related to App usages,data collection etc.. By the way do we collect any data apart from Google Play..?

**Comment by Swati4star** [comment]
No. We don't.

Also, we do have an about us section in app. That already has privacy policy.
We can add licence link to it (https://github.com/project-travel-mate/Travel-Mate/blob/master/LICENSE)

Other than that, I think it's fine. These cover everything
