### ISSUE TITLE
Implement own search city dialog using bottom sheet

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#461]
### Current implementaion
We are using this library: https://github.com/mirrajabi/search-dialog

### What to do?
Remove the use of the above library, and implement our own search city dialog in a bottom sheet

**Comment by Rimjhim28** [comment]
@Swati4star I would like to work on this issue but would need a bit of clarification on how this needs to done.

**Comment by Swati4star** [comment]
@Rimjhim28 What clarification do you need?

The issue is, we are currently using a library to select the city. Instead of that, when the option to select city is clicked, show the city names in a list in bottomsheet.

**Comment by Rimjhim28** [comment]
Okay @Swati4star! I will work on the issue and send a PR soon! :)

**Comment by Swati4star** [comment]
@Rimjhim28 Updates?

**Comment by nitinnatural** [comment]
hey @Swati4star , shall I take this up??

**Comment by Swati4star** [comment]
Sure @nitinnatural

**Comment by msecilmis** [comment]
@Swati4star i can pick this up also??

**Comment by Swati4star** [comment]
As @nitinnatural hasn't started working on it, you can start @msecilmis

**Comment by msecilmis** [comment]
Ok, great. Can you assign the issue to me?

**Comment by Swati4star** [comment]
Sure, you can start working on it @msecilmis 👍

**Comment by Swati4star** [comment]
any updates @msecilmis ??

**Comment by msecilmis** [comment]
Yeah, im almost done. Right now i’m on vacation. Next week i’ll wrap it up
