### ISSUE TITLE
[Utilities - Currency converter] Add a graph to show currency rate trends

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#464]
### Steps to reproduce
- Go to navigation drawer -> utilities -> currency converter

### Expected behaviour
After the user has selected source & destination cities, and press `Convert`, show a graph at the bottom of the screen showing the change in currency rate over time

### Endpoint to use
`get-all-currency-rate/<str:start_date>/<str:end_date>/<str:source_currency_code>/<str:target_currency_code>`

**Comment by Chinmay-KB** [comment]
I want to take up this issue

**Comment by Swati4star** [comment]
Sure! @Chinmay-KB

**Comment by RanjanDharmraj** [comment]
@Swati4star 
Any progress here? Can I work on this?

**Comment by Swati4star** [comment]
@RanjanDharmraj I think you can take this up. There has been no progress.

**Comment by RanjanDharmraj** [comment]
@Swati4star 
What is simple date format for start date and end date?

**Comment by RanjanDharmraj** [comment]
it will be great if you can provide me sample request/response

**Comment by Swati4star** [comment]
Did you try out the endpoint given in description?

**Comment by RanjanDharmraj** [comment]
yes I tried, its throwing 500 server error.

**Comment by Swati4star** [comment]
@RanjanDharmraj The date format is like this : `%Y-%m-%d`

Same request
```
https://project-travel-mate.herokuapp.com/api/get-all-currency-rate/2018-03-01/2018-03-07/usd/inr
```

Response
```
[
    65.325,
    65.261431,
    65.1967000002,
    65.1967000002,
    65.1213999998,
    64.8249999997,
    64.8842999999
]
```
