### ISSUE TITLE
Add checkboxes to  checklist widget

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#465]
### Steps to reproduce
- Add checklist widget to app home screen
<img width="244" alt="screenshot 2018-09-30 at 11 54 46 pm" src="https://user-images.githubusercontent.com/9164477/46261068-4d2eeb00-c50c-11e8-983f-1f597d3a4e8a.png">

### Expected behaviour
- show checkboxes. they should be in sync with actual state of items in checklist

### Actual behaviour
- no checkboxes

**Comment by ritesh24** [comment]
Working on this. How can I add items in the checklist?

**Comment by Swati4star** [comment]
Open travel mate app. Go to utilities -> Checklist.
There is an option to add items in checklist

**Comment by Swati4star** [comment]
@pista96 You can start investigating on this. If you find the fix, create a PR.
