### ISSUE TITLE
Allow users to save map offline

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#469]
In the city description page, allow users to save map offline
When user selects that, save the map of that city offline

**Comment by aumarbello** [comment]
Can I take up this?

**Comment by Swati4star** [comment]
Sure @aumarbello

**Comment by aumarbello** [comment]
Okay nice.

**Comment by Swati4star** [comment]
updates @aumarbello ?

**Comment by aumarbello** [comment]
Really sorry about the delay in implementing this, I've been offline for a long while.

In the city description page I cant see the place where a map is displayed though, could you point me to the right page?
![screenshot_20181021-193458](https://user-images.githubusercontent.com/28558653/47270810-03647e00-d569-11e8-9bc6-66efb36552fb.png)


☝️

Thats the page am talking about.

**Comment by aumarbello** [comment]
Okay, I understand now.

Will start working on it.
