### ISSUE TITLE
Add empty state for "no restaurants" found

### ISSUE THREAD

**Issue by valericaplesu** [project-travel-mate/Travel-Mate#473]
We need to handle the case when there are no restaurants returned for a city

### Steps to reproduce
Open Bangalore city
Tap on Restaurants
The message "Searching Network" is displayed
### Expected behaviour
We should handle the api response "Not Found"
2018-10-02 13:19:02.972 9763-9838/io.github.project_travel_mate D/RestaurantsActivity: response = "Not Found"
2018-10-02 13:19:02.975 9763-9763/io.github.project_travel_mate W/System.err: org.json.JSONException: Value Not Found of type java.lang.String cannot be converted to JSONArray

### Actual behaviour
"Searching Network" is displayed

### Would you like to work on the issue?
I can pick this up

**Comment by KWright8** [comment]
I can pick this up

**Comment by wajahatkarim3** [comment]
Can I do this?

**Comment by Swati4star** [comment]
We have a no results animation. We can show that in case there are no results.
https://github.com/project-travel-mate/Travel-Mate/blob/master/Android/app/src/main/res/raw/empty_list.json

**Comment by Swati4star** [comment]
Sure @wajahatkarim3 👍
