### ISSUE TITLE
Show spotlight view after the elements are loaded

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#475]
Describe your issue here.
<img width="370" alt="screenshot 2018-10-02 at 9 16 22 pm" src="https://user-images.githubusercontent.com/9164477/46360501-3b268700-c689-11e8-9f23-e555090a51a8.png">

### Steps to reproduce
- Open home page for the first time

### Expected behaviour
Spotlight view should be displayed after the card is visible

**Comment by valericaplesu** [comment]
I pick this up. But first I want to do a small fix for the cache logic. Now the cities are loaded each time we enter in City Fragment even if there is a checkCacheItems in Db
