### ISSUE TITLE
[Forget Password] Integrate API calls

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#487]
The UI for forget password flow has been added in https://github.com/project-travel-mate/Travel-Mate/pull/484, but the actual API calls are missing.

### Expected behaviour
- Add the correct API calls as mentioned in description of #484 

### Endpoints to use:
https://github.com/project-travel-mate/server/blob/master/api/urls.py#L35-L38

`forgot-password-email-code/<str:username>`
`forgot-password-verify-code/<str:username>/<str:code>/<str:new_password>`

**Comment by amoraitis** [comment]
I can work on this

**Comment by Swati4star** [comment]
Sure @amoraitis 👍

**Comment by amoraitis** [comment]
@Swati4star Could you please inform me whenever or not `forgot-password-email-code` checks if user with that e-mail doent exist? Or how I can validate if user with the given e-mail exist? Possible ways to handle this one?

**Comment by Swati4star** [comment]
@prabhakar267 share your comments..

**Comment by prabhakar267** [comment]
@amoraitis @Swati4star 
I think there needs to be a change added in the APIs to take user email as a field as well.
Because if the user is not signed-in, his app would not have an authorization token from which we were extracting email address.
I will update this issue, once that is fixed from server side.

**Comment by Balram02** [comment]
Can i take this up? @Swati4star

**Comment by Swati4star** [comment]
@amoraitis Are you continuing on this issue?
@Balram02 If @amoraitis doesn't reply, you can take up the issue.

**Comment by amoraitis** [comment]
> @amoraitis Are you continuing on this issue?
> @Balram02 If @amoraitis doesn't reply, you can take up the issue.

This issue issue is blocked as arised from @prabhakar267 's comment

**Comment by Swati4star** [comment]
I think the issue is fixed now : https://github.com/project-travel-mate/server/issues/137

**Comment by prabhakar267** [comment]
@amoraitis The issue is fixed
You can work on it and let me know if you face any issue
