### ISSUE TITLE
Underscore is not recongnized as a special character in passwords

### ISSUE THREAD

**Issue by TheGamer007** [project-travel-mate/Travel-Mate#490]
I'm not sure if the exclusion was intentional, in which case feel free to close the issue. The fix is a simple modification of the valid password regex [here](https://github.com/project-travel-mate/Travel-Mate/blob/4c0e3d219c9b6938836f01dc4e151c9091489695/Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java#L418).

### Steps to reproduce
Open the app and attempt to "Sign Up" with a password similar to "Pass_word1" that has a capital letter, a number and `_` as the sole special character.

### Expected behaviour
`_` should be considered a special character, and passwords of the aforementioned kind should be valid.

### Actual behaviour
It will show a toast with the conditions for a valid password, indicating that the current one is invalid. According to the regex, current valid special characters are `@#$%^?&+=!`.

### Would you like to work on the issue?
Yes, I can send a PR immediately.

**Comment by Swati4star** [comment]
Sure, you can create a PR for this.
