### ISSUE TITLE
Create a world clock widget

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#494]
- Create a world clock widget.
- User should be able to select country. (timezone)
- The clock should be abvailable in digital, as well as analog format.

**Comment by santoshhiremani** [comment]
Can i?

**Comment by Swati4star** [comment]
Sure!

**Comment by farmanp** [comment]
@santoshhiremani can i work with you to see this issue being resolved?

**Comment by santoshhiremani** [comment]
Sure..

**Comment by santoshhiremani** [comment]
@Swati4star  I think we need have it in Utilities since user can't change timezone on widget itself. something like this https://github.com/arminha/worldclockwidget/wiki/Screenshots

**Comment by Swati4star** [comment]
We do have an issue for this also, https://github.com/project-travel-mate/Travel-Mate/issues/393

**Comment by santoshhiremani** [comment]
Is that merged ? Need to fix that than. Widget alone doesn't serve our purpose..

**Comment by santoshhiremani** [comment]
Ok

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/560
