### ISSUE TITLE
Create new utility : Upcoming long weekends

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#498]
- Add a new card in `utilities` : `Upcoming long weekends`
- on clicking this, open up a new fragment/activity
- this should have a list of holidays [in timeline view] - check my trips page for timeline view sample

### endpoint to use
`get-upcoming-holidays/<int:year>`

**Comment by St4no10** [comment]
Is it available? I would like to grab it :)

**Comment by Swati4star** [comment]
Sure @St4no10 👍

**Comment by amoraitis** [comment]
@Swati4star I can work on this and, once i have implemented the my-trips page before, I can reuse the UI

**Comment by Swati4star** [comment]
Sure @amoraitis 👍

**Comment by St4no10** [comment]
What about me? I am almost done with this

**Comment by St4no10** [comment]
@Swati4star ? What image should I use for card view in Upcoming long weekends? Can I choose some random from the internet?
And about endpoint get-upcoming-holidays/<int:year> The parameter year should be actual year? Or should I combine maybe actual year and actual year+1 

That's what missing in my implementation

**Comment by Swati4star** [comment]
- You can choose any random image.
- I am sorry, I havent tested the parameters of API. Can you check it? If there is still an issue, comment here.
