### ISSUE TITLE
App crashes in CurrencyActivity when the device is offline

### ISSUE THREAD

**Issue by Balram02** [project-travel-mate/Travel-Mate#500]
### Steps to reproduce
1. Open App.
2. Go to Utilities and open Currency Converter.
3. Turn off internet.
4. Click Convert button.

### Expected behaviour
It should alert the user about the internet connectivity.

### Actual behaviour
App crashes

### Would you like to work on the issue?
Yes !

**Comment by Swati4star** [comment]
Great @Balram02 👍
