### ISSUE TITLE
Duplicate trips get added on refreshing

### ISSUE THREAD

**Issue by Balram02** [project-travel-mate/Travel-Mate#502]
### Steps to reproduce
1. Open app.
2. Go to My Trips and add some trips.
3. Refresh page multiple times(continuously).

#### Screenshot
<img src="https://user-images.githubusercontent.com/35597029/46915121-83687200-cfc4-11e8-92bf-b914a1c6fcad.png" height=500></img>

### Expected behaviour
It should not allow user to refresh continuously

### Actual behaviour
Single trip is seen multiple times

### Would you like to work on the issue?
Yes !

**Comment by Swati4star** [comment]
Great Finding @Balram02 👍

**Comment by AbdulDroid** [comment]
Can I try to fix this?

**Comment by AbdulDroid** [comment]
How do I onboard on the app, as I have been trying for a while now to create an account to no avail @Swati4star

**Comment by Swati4star** [comment]
Hi @AbdulDroid What problem are you facing while creating a new account?

**Comment by AbdulDroid** [comment]
I keep getting invalid emails or password every time @Swati4star please help

**Comment by Swati4star** [comment]
Are you sure the password is valid?
`Password must contain minimum 8 characters, at least 1 Alphabet, 1 Number and 1 Special Character. `

**Comment by AbdulDroid** [comment]
I followed all and I have to wait out the loading process to get the toast that says my email or password is invalid, and I believe this matches your criteria T3ster&1 for a password

**Comment by Swati4star** [comment]
You are doing this on signup screen. Right?

<img width="321" alt="screenshot 2018-10-16 at 4 05 33 pm" src="https://user-images.githubusercontent.com/9164477/47010685-54d1cf00-d15d-11e8-8e37-78e65e6a4065.png">

**Comment by AbdulDroid** [comment]
Yes right

**Comment by Swati4star** [comment]
I just tried creating a new account with some email id, I am not facing any issue. There is no issue with server.

**Comment by AbdulDroid** [comment]
I have tried several times again still the same result
Device info
Emulator: Pixel 2XL running Android P

Please try with same device or OS and let me know if you still get results @Swati4star

**Comment by Swati4star** [comment]
@AbdulDroid I created a new sample user.
Try signing in using these credentials:
email: testing123@gmail.com
password: Test@123
