### ISSUE TITLE
 Add Delete Account option in settings

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#510]
Allow users to delete their account

### Where to add?
- Add a new option in settings fragment : `Delete Account`

### Expected behaviour
On selecting this, show an alert `Are you sure you want to remove your travel mate account? This action can't be undone.`
If user selects yes, call the below endpoint, else close the alert dialog.

### endpoint
`/delete-profile`

**Comment by tk684kw** [comment]
@Swati4star Can I work on this issue ?

**Comment by Balram02** [comment]
@tk684kw  are you working on this? I would like to take this up?

**Comment by Swati4star** [comment]
If @tk684kw doesn't reply, you can take it up.

**Comment by tk684kw** [comment]
Yes i work on it.

Získat Outlook pre Android<https://aka.ms/ghei36>

________________________________

**Comment by Swati4star** [comment]
Updates @tk684kw ?
This shouldn't take up a lot of time. It's just one API call.

**Comment by tk684kw** [comment]
Today I send PR.

Získat Outlook pre Android<https://aka.ms/ghei36>

________________________________
