### ISSUE TITLE
UI/UX suggestions for a home page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#511]
- We are planning to have a home page in the android application
- This should provide users with easy access to:
  - trips
  - friends
  - top/popular cities
  - utilities
  - real time locator

We can have small cards type layout. On clicking these, we are directed to the selected option.

Suggest some UI mock ups for this issue.
After this, we can work on implementing this in the application.

**Comment by Balram02** [comment]
Suggestion: we can provide tab layout UI like whatsapp or bottom navigation just like linkedIn/youtube.

**Comment by Swati4star** [comment]
Not the bottom tabs. We have different fragments in navigation drawer only. 
Let the the home page be some simple card layouts combination, animations..

**Comment by jddeep** [comment]
@Swati4star I would like to work on this issue (gssoc19). Kindly assign me. Thanks.

**Comment by Swati4star** [comment]
Sure @jddeep

**Comment by pradnyasd** [comment]
Can I work on the same issue?

**Comment by jddeep** [comment]
![screenshot 140](https://user-images.githubusercontent.com/43133646/53783092-331f8b80-3f36-11e9-8b19-14c9ec1b8c5c.png)
@Swati4star Please take a look. This is a just a basic mockup; All images and a background is not added. These will be added while developing.

**Comment by jddeep** [comment]
@Swati4star Kindly confirm whether I should proceed to making a PR.

**Comment by Swati4star** [comment]
@jddeep 
- Reduce the curve radius of the cards
- Shadow is looking weird. Reducing the intensity might help
- Make the text size smaller

You can work on this layout. We can create further issues to improvise.

@thedevelopersanjeev Add your views too.

**Comment by jddeep** [comment]
@Swati4star okay sure. I will work with on the asked changes and shall make a PR on the same. Thanks.

**Comment by jddeep** [comment]
And @Swati4star Do you want a full functioning Home screen with linkings to all activities or just a UX/UI screen whose functioning should be added in further issues.

**Comment by Swati4star** [comment]
Functioning screen with linking to fragments/activites

**Comment by jddeep** [comment]
Then it shall be a long tedious task if everything is to be done together in one PR.

**Comment by jddeep** [comment]
@Swati4star Should I consider making the homepage layout in `fragment_tavel.xml` ? Cause I am not finding another way to link it to the main activity.

**Comment by CoderVishalSehgal** [comment]
@Swati4star I would like to work on this issue :)

**Comment by jddeep** [comment]
@Swati4star Should I consider making the homepage layout in fragment_tavel.xml ?

**Comment by jddeep** [comment]
@Swati4star Should I consider making the homepage layout in `fragment_tavel.xml` ?

**Comment by Swati4star** [comment]
@jddeep Create a new fragment `fragment_home` and add a new entry in navigation drawer
