### ISSUE TITLE
Create a separate module for flag list view

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#512]
Currently, the flag related activities are part of main module only.
Move these to a new module - `flag-listview`

<img width="351" alt="screenshot 2018-10-18 at 4 51 17 pm" src="https://user-images.githubusercontent.com/9164477/47150989-0dcb1180-d2f6-11e8-8124-4fd81750dc96.png">

The flag related views are used in : 
- World clock
- currency converter

### Why are we doing this?
This module will be hosted on maven as a new separate library.

**Comment by patres270** [comment]
Hi, Can I work on this issue?

**Comment by blongho** [comment]
Hello @Swati4star, I would love to fix this issue if @patres270  has not already done so.

**Comment by Swati4star** [comment]
@blongho Yes you can 👍 
Let me know if you face any issue.

**Comment by blongho** [comment]
ok @Swati4star  i will work on this

**Comment by 12abhijeet12** [comment]
i would like to create this app

**Comment by blongho** [comment]
@Swati4star, you might want to tag this issue as ```in progress```. I am working on it

**Comment by blongho** [comment]
Can @Swati4star  or anyone take a look at this branch feature?
1. Clone my copy of the app
```
git clone  https://github.com/blongho/Travel-Mate.git 
```
2. Get the branch 
```
git checkout origin/fix-issue#512
```
3. Build and run app and go to `Utilities-> Currency Converter `
Things to check
- Check that CurrencyConverter displays flag list appropriately
  **Note** In this version of the app, all flags in `res/drawable` have been deleted 
    and uses that provided by [country-data](https://github.com/blongho/world-country-data)

A quick feedback would be highly appreciated as i need this to work with World Clock.
Thanks in advance

**Comment by Swati4star** [comment]
It might take a week for me to review this.

**Comment by blongho** [comment]
> It might take a week for me to review this.

@Swati4star, i think i have "completed" this task and have submitted a formal pull request.

**Comment by Swati4star** [comment]
yes you have! There are a few minor changes that I have mentioned in the PR. you can check those, and then the PR is ready to be merged.
