### ISSUE TITLE
UI Bug in World clock utility

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#513]
The UI of world clock is overlapping:
<img width="310" alt="screenshot 2018-10-18 at 4 52 30 pm" src="https://user-images.githubusercontent.com/9164477/47151071-4f5bbc80-d2f6-11e8-9999-5f3a2e4912e7.png">

### Steps to reproduce
Go to utilities -> world clock

### Expected behaviour
- The time shouldn't overlap with clock
- Increase text size of `select timezone`

### Device info
Pixel XL

**Comment by vallividhya** [comment]
Can I work on this issue?

**Comment by vallividhya** [comment]
Here is my pull request: https://github.com/project-travel-mate/Travel-Mate/pull/517
