### ISSUE TITLE
If device does not have magnetic sensor, show compass at end in utilities

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#514]
### Steps to reproduce
- select a device without magnetic sensor
- Go to utilities -> Compass

### Expected behaviour
In case the device does not have magnetic sensor,
 - show the compass card at the end in utilities section
- Grey out the card & on the top of card, show `Your device does not have magentic sensor` 
else
- The UI should be as is.

### Actual behaviour
After this issue (https://github.com/project-travel-mate/Travel-Mate/issues/457), an alert is shown if compass is opened & the device does not have magnetic senso

**Comment by renanrhoden** [comment]
can I take it?

**Comment by renanrhoden** [comment]
@Swati4star is there a debug user I can use?

**Comment by Swati4star** [comment]
Is there any issue if you create a new user?
