### ISSUE TITLE
User profile : Show if email id is verified

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#520]
### Steps to reproduce
- Go to navigation drawer. 
- click on profile picture

### Expected behaviour
At the right of the email id, show a small green tick icon (if user's email is verified), or a red small cross icon (is email id is not verified)
There is a new field in the below endpoint. Use this to check email verification
`"is_verified": false`

### Endpoint to use
`/api/get-user`

**Comment by Balram02** [comment]
I am taking this up !

**Comment by Swati4star** [comment]
Sure @Balram02 👍
