### ISSUE TITLE
UI fixes in View Contributors

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#521]
### Steps to reproduce
Go to navigation drawer -> about us -> view contributors

<img width="362" alt="screenshot 2018-10-21 at 2 57 06 pm" src="https://user-images.githubusercontent.com/9164477/47265192-9a1d4480-d541-11e8-8b50-9a785ed48565.png">

### Expected behaviour
- Make the github handle to come in a single line only (add ellipsis otherwise)
- there is thin line above the contributors github handle. Remove that.
- At the bottom, `Github` and octocat icon are not aliogned.

**Comment by YuganshT79** [comment]
I would like to work on this issue

**Comment by Swati4star** [comment]
Sure @YuganshT79 👍
