### ISSUE TITLE
Currency converter : Make number of days customizable in trends graph

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#522]
### Steps to reproduce
- Go to navigation drawer -> utilities -> currency converter
- select convert

<img width="355" alt="screenshot 2018-10-21 at 3 01 52 pm" src="https://user-images.githubusercontent.com/9164477/47265231-43fcd100-d542-11e8-9232-3a947bfd7244.png">

### Expected behaviour
- Just above the graph, show a drop down to show values like :  7 days, 1 month, 2 months, 6 months, a year
- 7 days is selected initially.
- When user selects some other value: make an API call to get value for those many days (also update it in the text at bottom)

https://github.com/project-travel-mate/Travel-Mate/blob/15a4fe414aab8a57f7167d593cd73299ea000de9/Android/app/src/main/java/io/github/project_travel_mate/utilities/CurrencyActivity.java#L285

### Endpoint
`get-all-currency-rate/<str:start_date>/<str:end_date>/<str:source_currency_code>/<str:target_currency_code>`

**Comment by hafiz703** [comment]
Can I take up this issue?

**Comment by hafiz703** [comment]
Can i take up this issue?

**Comment by Swati4star** [comment]
Sure @hafiz703 👍
