### ISSUE TITLE
UI enhancement in my trips screen

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#523]
Describe your issue here.
<img width="336" alt="screenshot 2018-10-21 at 3 06 44 pm" src="https://user-images.githubusercontent.com/9164477/47265364-a0f98680-d544-11e8-87c2-8489c9d6f4e8.png">

### Steps to reproduce
- go to navigation drawer -> my trips

### Expected behaviour
- The trips are currently shown in ascending order of time. Show them in descending order (the latest or upcoming trips should be on top)
- If there are no upcoming trips, show : `You don't have any upcoming trips. Click on + icon on bottom to add new trip!`
- If there are some past trips, show `Your past trips` heading & show a lit of past trips after this heading.

**Comment by Yahhi** [comment]
I want to work on this issue

**Comment by Swati4star** [comment]
Great! @Yahhi 👍
