### ISSUE TITLE
Allow users to verify email address

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#527]
### Steps to reproduce
- go to navigation drawer -> select your profile picture

### Expected behaviour
- IF the email id is not verified, the cross is red. 
- If user selects red icon, open up a dialog/fragment : 
  title : `Your email id is not verified` 
  add a button : `Send verification email!`
- When user selects button, show a progress icon, and call the endpoint
- after the response is received, show the otp view (similar to that of reset password). Also a text at bottom : `Didn't receive OTP. Send mail again?`
- after user has entered OTP, call API to verify it

### Endpoint
`generate-verification-code`
`confirm-verification-code/<str:verification_code>`

**Comment by Balram02** [comment]
Will send PR within next 2 days. Btw should i use the same background image for otp view as in reset password?

**Comment by Swati4star** [comment]
You can use a different background image too. Whichever feels good :)

**Comment by Balram02** [comment]
sorry for sending late PR... I was busy somewhere else.
