### ISSUE TITLE
Show `travel quote once a day` fragment

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#538]
- When user opens the app, show a new fragment with a quote & author from below endpoint
- This should be displayed just once per day
- Add a don't dhow again button also.
- Allow users to copy it & share it (sharing should work similar to how fun facts of a city are shared in our app)

### Endpoint
https://raw.githubusercontent.com/btford/philosobot/master/quotes/travel.json

(We will add more quotes to our list soon)
For now, choose any random quote

**Comment by Tc2r1** [comment]
I will take a swing at this

**Comment by Swati4star** [comment]
Sure. 👍 

Just comment here if you face any issue 💯

**Comment by Tc2r1** [comment]
Hi Swati, is this before or after the splash screen?

**Comment by Swati4star** [comment]
After the splash screen

**Comment by ajaypro** [comment]
Hi Swati, I will work on this issue

**Comment by Swati4star** [comment]
Sure! @Tc2r1 
Just send out the PR when done :)

@ajaypro You can work on some other issue, or create a new one 👍

**Comment by Tc2r1** [comment]
@Swati4star  Done, I hope, work week starts soon. I'd love to ask some questions about some of your code, is there a better way I can contact you?

**Comment by Swati4star** [comment]
Check out slack link in the readme. You can join that, and we can chat over there.
Or, we can talk over mail also :)
