### ISSUE TITLE
Show 3 cities in one row in horizontal mode

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#539]
![e57c1998-2928-46f6-9e11-e0515833f93a](https://user-images.githubusercontent.com/9164477/47547787-79276b80-d914-11e8-80a0-6dd89ccfdf03.jpeg)

### Expected behaviour
In horizontal mode, change number of cities to 3 (instead of 2)

**Comment by thilinatnt** [comment]
Hi may I take this task?

**Comment by Swati4star** [comment]
Updates @thilinatnt ?

**Comment by thilinatnt** [comment]
@Swati4star Oh sorry, actually I thought this is already taken as I din't get the confirmation message

**Comment by Swati4star** [comment]
I think, we shouldn't go ahead with this issue. Flipping of cards will also look weird if there are 3 cities in a row 👍 

and thanks for such a detailed investigation on this issue!
