### ISSUE TITLE
Swap icons on create travel screen

### ISSUE THREAD

**Issue by Charliocat** [project-travel-mate/Travel-Mate#555]
When I click on the button to create a new trip, on My Trips. The icon date and icon city are swapped.
![14-11-2018 23-40-05](https://user-images.githubusercontent.com/38671248/48517501-c7ba8c80-e866-11e8-9284-5bb6b8f01341.png)

### Steps to reproduce
Click to my trips, then add a new trip, you can see the icons ara missplaced.

### Expected behaviour
Location icon should be next to the city, and event icon should be next to the trip date.

### Actual behaviour
Icons are swaped

### Would you like to work on the issue?
I could do it.

**Comment by Swati4star** [comment]
Sure. You can work on it 👍

**Comment by numerative** [comment]
I'd like to take up this issue.
