### ISSUE TITLE
Documentation for Travel Mate app 

### ISSUE THREAD

**Issue by jtj9817** [project-travel-mate/Travel-Mate#557]
# Documentation
I would like to submit a proposal for a documentation of the app so that future contributors to the project will have an easier understanding of the codebase. This is just an idea that came up to me as I was investigating the previous issues that I've worked at. A documentation for this project can be really helpful because I haven't seen any activity from the main people that contributed to the original codebase of the project. 

That said, the intended documentation will be stored besides the 'Android' folder of the app so people will immediately notice it. The documentation will have files for diagrams and API documentation of the project's components. 

As an example of the diagram I'm referring to:
![](https://raw.githubusercontent.com/jtj9817/MediaFiles/master/Component_ExampleDiagram.png)
### Would you like to work on the issue?
I can start the work on the issue and other people can help me in documenting it.

**Comment by Swati4star** [comment]
I have few doubts regarding this:
- Are you planning to create this chart manually, or do you have automation tool for this? If manually, the cost of updating the class diagram along with the code changes might be an issue.
- Do you wish to add these in wiki page only or someplace else?

**Comment by jtj9817** [comment]
My first idea is to create these charts manually but I will start looking into automation tools that can make diagrams of classes and functions. I'm thinking Rational Rose/StarUML might have these features but I will need to research them first.

My current plan is to create a PDF file that has the documentation. Of course I can also add them to the wiki but that will involve the authorization for me to edit the wiki.

**Comment by Swati4star** [comment]
Dont create the charts manually, the maintenance of those charts will be an issue then.
Search for some automation tools only for this.

**Comment by jtj9817** [comment]
I found a method to do it using automated UML-generating tool but it will need to be imported on Gradle as an add-on.

https://stackoverflow.com/questions/17123384/how-to-generate-class-diagram-uml-on-android-studio-intellij-idea/36823007#36823007

**Comment by Swati4star** [comment]
Did you want that kind of output only? (the type that is there in the link you have mentioned)

**Comment by jtj9817** [comment]
It's not the only output that I want for the documentation but it makes the documentation easier. I still need to provide a description for the functions so that if there's a bug found in the future, future contributors can find it easily.

**Comment by Swati4star** [comment]
> https://stackoverflow.com/questions/17123384/how-to-generate-class-diagram-uml-on-android-studio-intellij-idea/36823007#36823007

@jtj9817 This link looks good. Just create a new PR with:
- a new folder which contains these diagrams
- a link to the above folder in the readme

**Comment by Swati4star** [comment]
@jtj9817 any updates here?

**Comment by jtj9817** [comment]
I will make a PR concerning this Issue within the next 2 weeks. If any problem comes up, I'll discuss it here.

**Comment by narendrasinghsolanki** [comment]
how to run this project on android studio

**Comment by Swati4star** [comment]
@narendrasinghsolanki https://github.com/project-travel-mate/Travel-Mate/wiki#installation

**Comment by narendrasinghsolanki** [comment]
how i clone repositry

**Comment by thedevelopersanjeev** [comment]
Hello @narendrasinghsolanki  
Open Terminal/GitBash(if using windows)
and
write command `git clone git@github.com:project-travel-mate/Travel-Mate.git`

**Comment by Rita-Okonkwo** [comment]
Hello is this still an issue or has it been solved? Also, are all the issues recent ones that require a solution? Looking forward to your kind and urgent response

**Comment by jtj9817** [comment]
This issue is still being worked on. To be more specific, I can be certain that there would be **no pull request** at the end of this week as I'm currently preoccupied. Next week seems to be a better time to continue working on the Issue.

**Comment by Rita-Okonkwo** [comment]
Alright thanks

**Comment by narendrasinghsolanki** [comment]
what is your test cases and user documentation,conclussion of project
DIDI

**Comment by jtj9817** [comment]
For everyone that still wants to work on this Issue, a PR was opened up 2 days ago to deal with this Issue. The PR can be seen here: https://github.com/project-travel-mate/Travel-Mate/pull/571

**Comment by mih475** [comment]
I am trying to run the tests by saying ./gradlew checkstyle. But its not working. It's saying - 
![travelMate](https://user-images.githubusercontent.com/22691383/65838414-6a85c900-e2c8-11e9-8a87-de0eb17ae7cb.JPG)

**Comment by prabhakar267** [comment]
As mentioned in #571 we don't think it is necessary for the project at this moment and maintaining this would be a lot of effort which we think would be very more tedious than fruitful.
Thanks for the issue.
