### ISSUE TITLE
This app is on admin panel if yes how to create admin panel?

### ISSUE THREAD

**Issue by mast-armaan** [project-travel-mate/Travel-Mate#562]
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Would you like to work on the issue?
Tell us if you would like to work on this issue

**Comment by Swati4star** [comment]
what do you mean by admin panel? What are your expectations for this?

**Comment by mast-armaan** [comment]
Suppose I want to add more cities or changes description or any other
information from server and after changing the information it should show
on this app so i want admin panel, is this has admin panel?

**Comment by Swati4star** [comment]
you need to set up your own server for this. You can have your database then. 
See this repo for setting up the server: https://github.com/project-travel-mate/server

**Comment by Swati4star** [comment]
If you need any other info, comment here or join us on slack, or drop a mail
