### ISSUE TITLE
Filter cities on home page

### ISSUE THREAD

**Issue by NicaNicaNicaNica** [project-travel-mate/Travel-Mate#564]
Hi, I just want to thank you guys for this amazing project.
Is there a way in filtering the city based on the number of visitors?

**Comment by Swati4star** [comment]
No. There isn't.
We actually don't have any 'filtering' option for cities yet.

**Comment by ShivangiSingh17** [comment]
I would like to work on this issue. Shall I ??

**Comment by thedevelopersanjeev** [comment]
sure @ShivangiSingh17 you can start working on it.

**Comment by Swati4star** [comment]
@ShivangiSingh17 Pick up one issue at a time please!

**Comment by agarwalprashasti** [comment]
Is this issue still open? If this is the case I would like to work on this.

**Comment by ShivangiSingh17** [comment]
@agarwalprashasti, I am not working on this issue, you can proceed working on this issue.

**Comment by agarwalprashasti** [comment]
@Swati4star Maybe we can show the most visited cities in the top.

**Comment by Swati4star** [comment]
We already show most visited cities only on destinations

**Comment by Swati4star** [comment]
@agarwalprashasti any updates here?

**Comment by prabhakar267** [comment]
@NicaNicaNicaNica 
Cities by default are sorted on the basis of **current interest** and if we want to add another sorting method, it would require for us to make changes to our **interest** calculations. Currently, we sort them based on the number of impressions and number of people who have had a trip to that city.
Regardless, you can always search for city by name.
Thanks for suggestion though.
Closing this issue. If you think there can be a different/improved sorting algorithm, feel free to open up a discussion on [server (backend) repository](https://github.com/project-travel-mate/server).
