### ISSUE TITLE
Implement Runtime Permissions Properly.

### ISSUE THREAD

**Issue by thedevelopersanjeev** [project-travel-mate/Travel-Mate#566]
Improve user experience.

### Steps to reproduce
Uninstall and reinstall the application

### Expected behaviour
Runtime permissions should be requested when they are required.

### Actual behavior
Runtime permissions are requested during the first launch of the application.

### Would you like to work on the issue?
No

**Comment by CoderVishalSehgal** [comment]
I would like to work on this issue.

**Comment by thedevelopersanjeev** [comment]
go ahead.

**Comment by ashiagarwal73** [comment]
I can work on this issue

**Comment by thedevelopersanjeev** [comment]
Hello @ashiagarwal73 This issue has already been assigned to @CoderVishalSehgal

**Comment by ashiagarwal73** [comment]
Okay

**Comment by Swati4star** [comment]
@CoderVishalSehgal updates?

**Comment by CoderVishalSehgal** [comment]
> @CoderVishalSehgal updates?

@Swati4star Will push the code by tomorrow!

**Comment by Swati4star** [comment]
@CoderVishalSehgal Are you working on this?

**Comment by prabhakar267** [comment]
Added a fresh issue with all relevant information, removing this stale one.
