### ISSUE TITLE
Application is unable to fetch data 

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#568]
When the user wants to know more about *Panjim*, the activity does not lead to any information page.

### Steps to reproduce
```Panjim city```>```Know more about Panjim```   

### Expected behaviour
On clicking ```Know more about Panjim```, the user should be redirected to the page containing information about the Panjim city.

### Actual behaviour
No loading of information .

### Would you like to work on the issue?
Yes

**Comment by ashiagarwal73** [comment]
I would like to work on this issue

**Comment by ShivangiSingh17** [comment]
Sorry.. but I am working on this issue.

**Comment by jddeep** [comment]
@Swati4star can I work on this?

**Comment by Swati4star** [comment]
@ShivangiSingh17 Are you working on this issue?

**Comment by ShivangiSingh17** [comment]
@Swati4star , Yes I am working on this issue. I will be sending a PR soon.

**Comment by Swati4star** [comment]
@ShivangiSingh17 You cant hold these many issues at a time!!

**Comment by Swati4star** [comment]
@ShivangiSingh17 Send PR for this first & then only proceed with others.

**Comment by ShivangiSingh17** [comment]
@Swati4star till now its long I am working on this issue and found that this issue is due to having problem from the server side while calling the api for the Panjim city.

I am no more working on this issue being it a server error.

**Comment by ShivangiSingh17** [comment]
I would like to proceed with my other claimed issues.

**Comment by prabhakar267** [comment]
Closing this since it seems fixed!
@ShivangiSingh17 Feel free to reopen if it isn't fixed
