### ISSUE TITLE
App bar label is minimized on orientation change  

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#570]
When the user switch to landscape mode the action app label is minimized .

### Steps to reproduce
1. Run the application.
1. Enable screen rotation and change the orientation to landscape.

### Expected behaviour
The label text size should remain same.

### Actual behaviour
The size of the label written in the action bar is minimized.

### Would you like to work on the issue?
Yes

**Comment by ShivangiSingh17** [comment]
Please I would like to fix this issue. Shall I begin working on this  ?

**Comment by thedevelopersanjeev** [comment]
go ahead @ShivangiSingh17

**Comment by ShivangiSingh17** [comment]
@Swati4star can you please review this PR and suggest the changes if any.
