### ISSUE TITLE
Typo error in README.md file

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#572]
Typo error is found in README.md file.

### Steps to reproduce
Open the README.md file of the project.

### Would you like to work on the issue?
Yes

**Comment by Swati4star** [comment]
@ShivangiSingh17 This type of issue wont be considered for gssoc.
I am merging your PR though, but points wont be added for this PR

**Comment by ShivangiSingh17** [comment]
Ok @Swati4star not a problem. I will consider that.
