### ISSUE TITLE
Snackbar is displayed for very long duration in my trips section

### ISSUE THREAD

**Issue by theabhishekavi** [project-travel-mate/Travel-Mate#577]
When there is no upcoming trip snackbar is displayed for a long duration preventing from adding a new trip

### Steps to reproduce
1. Open My Trips
2. Remove all the trips

### Actual behaviour
Snackar is displayed for long duration causing add new trip icon invisible

### Expected behaviour
1.Either Snackbar duration should be set to short
2.Or Snackbar should be shown above the level of add icon

### Would you like to work on the issue?
Yes

**Comment by Swati4star** [comment]
- Set the duration of snackbar to short

You can work on this @theabhishekavi 
choose any one issue to work first
