### ISSUE TITLE
Pressing back button in any of the fragment leads to app close

### ISSUE THREAD

**Issue by theabhishekavi** [project-travel-mate/Travel-Mate#580]
If we press back button in any of the fragment(Travel, My Trips, My Friends, Favourite clients,etc) the app closes

### Expected behaviour
On back press the fragment should open the main activity instead of closing the app.
And to close the app from main activity twice back press button should be enabled:- First back button asking "Are you sure you want to exit" and second time the app should be closed.

### Would you like to work on the issue?
Yes

**Comment by theabhishekavi** [comment]
@Swati4star should it be implemented?

**Comment by Swati4star** [comment]
Sure @theabhishekavi 👍
