### ISSUE TITLE
Is the app only for Indians?

### ISSUE THREAD

**Issue by HarryHeights** [project-travel-mate/Travel-Mate#582]
I thought  I could check out other locations. However, it is restricted to India

**Comment by blongho** [comment]
@HarryHeights, I think that is why it is open source. You can adapt it to other settings. Check the [licence here](https://github.com/project-travel-mate/Travel-Mate/blob/master/LICENSE)

**Comment by HarryHeights** [comment]
Thanks @blongho. I'm not a developer though, I don't know how I'd go about that. Hopefully someone makes another variant of the app supporting other countries.

**Comment by blongho** [comment]
@HarryHeights, in that case, you should make your feature request just as you created this one. Instead, you could make the heading **Make Travel app for XXX country**. Doing this, however, will require the developer to have some local information about "XXX" which might or might not be difficult, depending on the country

**Comment by HarryHeights** [comment]
Yea true that. Thanks for your suggestion. I will open a new issue.
