### ISSUE TITLE
Develop and link Hotels Fragment to HomeFragment.

### ISSUE THREAD

**Issue by jddeep** [project-travel-mate/Travel-Mate#585]
Currently the Home page is UX/UI based and has no functionality. Child Activities/fragments are to be linked with it.

### Steps to reproduce
1. Go to Home from Nav Drawer.
2. The Home Page opens but does not respond on clicking the cards.

### Expected behaviour
On clicking a particular card, user should be taken to that particular fragment.

### Actual behaviour
Nothing.

### Would you like to work on the issue?
Yes.

**Comment by jddeep** [comment]
@Swati4star Please check this issue and confirm me on the same. Thanks.

**Comment by jddeep** [comment]
@Swati4star Is it a `beginner` issue? Cause the fragment needs to be developed from scratch and then needs to linked.

**Comment by Swati4star** [comment]
changes it @jddeep
