### ISSUE TITLE
Improve UX of Signup Screen.

### ISSUE THREAD

**Issue by thedevelopersanjeev** [project-travel-mate/Travel-Mate#587]
During signup, the error is displayed using snackbar which is not visible when the keyboard is in use. 

### Steps to reproduce
Improve the logic and enable error on EditText.

### Expected behaviour
Show the error on EditText using method setError and setErrorEnabled.
Reference: https://developer.android.com/reference/android/support/design/widget/TextInputLayout#seterror

### Actual behavior
The error is shown on Snackbar which is not visible.

### Would you like to work on the issue?
No

### Bug demo for more clarification:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34043056/54931555-3d361800-4f3f-11e9-9742-b6a73c1a611b.gif)

**Comment by gateway2rohan** [comment]
I would like to work on this.

**Comment by thedevelopersanjeev** [comment]
go ahead.

**Comment by gateway2rohan** [comment]
I completed it. Want to know the difficulty label of this issue?
