### ISSUE TITLE
Improve validation on SignUp Screen

### ISSUE THREAD

**Issue by thedevelopersanjeev** [project-travel-mate/Travel-Mate#588]
Checking for empty First Name and Last Name is not done before sending the data to the server.

### Steps to reproduce
Perform a check for empty first name and last name before sending the data to the server and show an appropriate error if the EditText is empty.

### Expected behavior
Checking for empty EditText should be done before forwarding the data.

### Actual behavior
Empty details are sent and then an error is returned from the server which is shown to the user.

### Would you like to work on the issue?
No

### Bug demo
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34043056/54932235-78851680-4f40-11e9-83e8-e17fcda96e75.gif)

**Comment by gateway2rohan** [comment]
Want to do this.

**Comment by thedevelopersanjeev** [comment]
go ahead
