### ISSUE TITLE
Develop and Integrate Friends fragment to HomeFragment.

### ISSUE THREAD

**Issue by jddeep** [project-travel-mate/Travel-Mate#589]
Describe your issue here.
Integrate Friends fragment to HomeFragment.

### Steps to reproduce
Navigate to Home Fragment and click on Friends.

### Expected behaviour
It should lead to some Friends fragment.

### Actual behaviour
Nothing happens.

### Would you like to work on the issue?
Yes.

**Comment by jddeep** [comment]
@Swati4star please add some tags to the issue.

**Comment by jddeep** [comment]
@Swati4star I shall make a new fragment for this,

**Comment by Swati4star** [comment]
sure @jddeep
