### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Rudloff** [project-travel-mate/Travel-Mate#59]
Hello,

Would you be interested in publishing this app on [F-Droid](https://f-droid.org/)?

**Comment by Swati4star** [comment]
@Rudloff Sure! You can add a merge request for this project on FdroidData.

**Comment by Rudloff** [comment]
Great!

Would it be possible to tag [releases](https://github.com/project-travel-mate/Travel-Mate/releases)?
This makes packaging a lot easier.

**Comment by Swati4star** [comment]
Hi @Rudloff ! Sure. Just specify the tag format you want me to create. Also, make the app auto update on Fdroid.

**Comment by Rudloff** [comment]
If we want to enable auto update, the easiest way is to have tags that match the version name of the app (e.g. `2.0` for the current version).

**Comment by Rudloff** [comment]
Sorry, I just noticed you are using some Play Services libraries: https://github.com/project-travel-mate/Travel-Mate/blob/0f22d564db73c522ac38cff589e445570b41177c/Android/app/build.gradle#L55
Unfortunately, these are not open-source so we can't include it in F-Droid (unless we could build a variant of your app wihtout these libraries but that's probably a lot of work).

**Comment by Swati4star** [comment]
We need maps in our application. After all, this is a travel app!

**Comment by Rudloff** [comment]
If you are interested, there are some open-source alternatives to Google Maps like [osmdroid](https://github.com/osmdroid/osmdroid).

I'm sorry, I didn't notice this dependency when I first had a look at your code. But I'm afraid this means we can't publish it on F-Droid.

**Comment by Swati4star** [comment]
Hi @Rudloff ! We have removed the usage of google maps, and replaced it with osmdroid.
Can you check if it can be published on f-droid now?

**Comment by Rudloff** [comment]
That is great!
It should be OK now. I will start working on packaging the app.

**Comment by Rudloff** [comment]
@Swati4star I created a build recipe for the app: https://gitlab.com/fdroid/fdroiddata/merge_requests/3803
I just had to remove the http://repo.commonsware.com.s3.amazonaws.com repository (not sure how it is used).

Do you think it would be possible to add [Git tags](https://github.com/project-travel-mate/Travel-Mate/tags) for 3.9.2 and future releases? It makes packaging updates a lot easier.

**Comment by Swati4star** [comment]
Hi @Rudloff 
Sure, I'll add git tag for current & future releases as well.
https://github.com/project-travel-mate/Travel-Mate/releases/tag/3.9.2

**Comment by Swati4star** [comment]
I think, adding https to the url will solve the issue.

**Comment by Swati4star** [comment]
The gitlab build should pass after this commit, https://github.com/project-travel-mate/Travel-Mate/commit/25ed7271108a67f7dc291fcd6f775339408a45e7

I have created a new release with the above commit included also.

**Comment by Rudloff** [comment]
Everything works correctly now, thanks!

**Comment by Swati4star** [comment]
Do share the fdroid link, when it is merged on gitlab.

**Comment by guest4711** [comment]
It's on f-droid now: Travel Mate (A complete travel guide) - https://f-droid.org/app/io.github.project_travel_mate

**Comment by Swati4star** [comment]
I'll update the readme soon to incorporate your comments 💯
