### ISSUE TITLE
API_LINK_V2

### ISSUE THREAD

**Issue by jeevanreddyb** [project-travel-mate/Travel-Mate#592]
what exactly String uri = API_LINK_V2 + "get-places/" + latitude + "/" + longitude + "/accommodation"; this string return? 

How can someone see that details in API_LINK_V2?

**Comment by Swati4star** [comment]
You can make an http call to above link using postman (or something else)
This is the value of API_LINK_V2
https://github.com/project-travel-mate/Travel-Mate/blob/master/Android/app/src/main/java/utils/Constants.java#L27
