### ISSUE TITLE
Improve UI for the profile screen

### ISSUE THREAD

**Issue by lifeLessCoder** [project-travel-mate/Travel-Mate#596]
Describe your issue here.
The user profile page has few changes to be made
- The no_image drawable is blurred out.
- The cross mark overlaps the email ID

Also, the UI needs to be improved in both portrait and landscape Orientation. 

![Screenshot_20190403-001312](https://user-images.githubusercontent.com/33070301/55429115-4e6ace80-55a8-11e9-97fd-74b5008b9d6c.png)

![Screenshot_20190403-001327](https://user-images.githubusercontent.com/33070301/55429106-47dc5700-55a8-11e9-8e4b-95e0ff36f8f5.png)

### Steps to reproduce
Launch the profile screen from the navigation drawer

### Would you like to work on the issue?
Yes

**Comment by usmanrafi** [comment]
Hi @Swati4star 

If this is still open, I'd like to work on it.

**Comment by Swati4star** [comment]
Yes, it's open. You can work on it @usmanrafi

**Comment by usmanrafi** [comment]
@Swati4star I've made a pull request regarding this, please review it.
