### ISSUE TITLE
Change monument detection logic from estimote beacons to GPS location

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/Travel-Mate#60]
Currently monuments or near by attractions are detected using estimote beacons but we decided to remove it to improve usability and scalability of the app.
Instead, use the current GPS location of the user and constantly poll (in certain interval ~600 seconds) the server providing the GPS coordinates and the proximity radius (in meters) to get a list of attractions near-by and accordingly send out a push notification.

**Comment by PauloKanno** [comment]
Hi
I just wanna give you a suggestion: use the "estimote beacons" just as some source of gamefication, to make the users to search & find the places with those items and help them to explore the city. 
And please, really do this enhancement purposed on this issue. Using this hardware (estimote beacons) to track monuments is not the best way to do this (and makes your app too costly to keep)
Congrats to the app, It's a really good idea

**Comment by Swati4star** [comment]
The estimote logic is removed in 1f9b6b408ac52a1fb0f5941f65854a5b905c7c5a
