### ISSUE TITLE
DATABASE NOT FOUND 

### ISSUE THREAD

**Issue by pranitp2222** [project-travel-mate/Travel-Mate#601]
Describe your issue here.
HOW TO FIND AND CONNECT DATABASE
### Steps to reproduce
Tell us how to reproduce this issue. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Would you like to work on the issue?
Tell us if you would like to work on this issue

**Comment by Swati4star** [comment]
Please give some description of what information do you exactly need?

**Comment by pranitp2222** [comment]
I have to see database file in your project
How you have created and how u have used i want to used in my project

**Comment by Swati4star** [comment]
check this repo https://github.com/project-travel-mate/server
