### ISSUE TITLE
Setting the word limit for the Username input box  

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#607]
Lengthy username is not supported and an error message is displayed rejecting the username updation.

### Steps to reproduce
Update the username and type a lengthy username. 

### Expected behaviour
To avoid the error message the word limit can be set. 

### Actual behaviour
The user is allowed to input the username of his choice but long username is not supported and the error message is displayed.

### Would you like to work on the issue?
Yes

### Screenshot
![Username updation](https://user-images.githubusercontent.com/43827236/56089509-824fc900-5eb1-11e9-8d2f-18057a5ea47c.gif)

**Comment by ShivangiSingh17** [comment]
@Swati4star and @thedevelopersanjeev, I would like to know your opinion regarding setting up the word limit to 50

**Comment by ShivangiSingh17** [comment]
@Swati4star please add labels to this.

**Comment by Swati4star** [comment]
Sure. Go ahead with this.
