### ISSUE TITLE
Integrate Cities Fragment & utilities fragment with Home Fragment

### ISSUE THREAD

**Issue by jddeep** [project-travel-mate/Travel-Mate#608]
Describe your issue here.
Integrate Cities & utilities Fragment with Home Fragment

### Actual behaviour
Nothing happens onClick.

### Would you like to work on the issue?
Yes.

**Comment by jddeep** [comment]
@Swati4star Please add tags to this.

**Comment by Swati4star** [comment]
Work on it @jddeep
