### ISSUE TITLE
Updating the pull request template

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#609]
While creating the pull request there can be a need of adding screenshots according to the issue type. Also at times attaching screenshots helps to understand the issue in a better way.

### Actual behaviour
Right now in the PR template, there is no reference given for adding screenshots. I will add that.

### Would you like to work on the issue?
Yes

**Comment by Swati4star** [comment]
This isnt a valid issue @ShivangiSingh17

**Comment by ShivangiSingh17** [comment]
@Swati4star most of the projects have that in there template.

**Comment by ShivangiSingh17** [comment]
I will add separate templates for issues, feature requests and chores for ease.

**Comment by ShivangiSingh17** [comment]
![template](https://user-images.githubusercontent.com/43827236/56121374-99fc7f80-5f8d-11e9-9c93-6ad97cd40831.png)
It will look like this once implemented.
