### ISSUE TITLE
Change in user details; Instead of phone number take email address

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/Travel-Mate#61]
For Sign in and Sign up processes, accept **email address** instead of phone number.
#### Reason for change
+ With phone number, we should be authenticating the user by sending a text message or call which is currently not in scope
+ With email address, we can update *(read \*spam\*)* user with latest changes we do in the app and also we can track any feedback sent by the user.
+ In future, we can add a layer of authentication by sending a verification link to the user on his email address

**Comment by anandkumarkparmar** [comment]
Hi @prabhakar267, Can I take this change up, if no one is working yet?

**Comment by Swati4star** [comment]
Hi @anandkumarkparmar , Yes you can work on it. Replace these fields from the UI. 

For API call, you can for now send some random number in the phone number field. We will soon have a new API ( https://github.com/project-travel-mate/server/pull/5) that accepts email address.
