### ISSUE TITLE
No Error Messages on Invalid Email for Sign-up Screen

### ISSUE THREAD

**Issue by jtj9817** [project-travel-mate/Travel-Mate#616]
## Issue
When I enter an invalid email address and click the "Signup" button, nothing happens and it doesn't display the error message.

![](https://raw.githubusercontent.com/jtj9817/MediaFiles/master/NoErrorMessages.gif)

## Steps to reproduce
Install development version of TravelMate, go to Signup screen. Fill out the 'First Name' and 'Last Name' sections, then enter an invalid email address. Press the 'Signup' button.

## Expected behaviour
Should show an error message that the email address is invalid (i.e. format is invalid)

## Actual behaviour
Nothing happens

## Would you like to work on the issue?
I can work on it

**Comment by DevanandGowda** [comment]
@jtj9817 Can I work on this? Please assign this to me.

**Comment by Swati4star** [comment]
Sure @jtj9817 you can work on it

**Comment by f71uday** [comment]
I checked this issue  this is working fine 
@Swati4star I think this issue needs to be closed

**Comment by prabhakar267** [comment]
Closing this since it seems fixed!
@jtj9817 Feel free to reopen if it isn't fixed
