### ISSUE TITLE
Bad behavior on navigating to Trips, Friends Fragment from Home

### ISSUE THREAD

**Issue by jddeep** [project-travel-mate/Travel-Mate#618]
Bad behaviour on navigating to Trips, Friends Fragment from Home.

Steps to reproduce:-
Click on Home.
Then click on Trips or Friends fragment,

I would like to Work on this issue.

**Comment by jddeep** [comment]
@Swati4star Please provide difficulty tags.

**Comment by jddeep** [comment]
@Swati4star Please provide difficulty tags.

**Comment by jddeep** [comment]
@Swati4star ?

**Comment by Swati4star** [comment]
what exactly do you mean by `bad behaviour`?

**Comment by jddeep** [comment]
@Swati4star The Home Fragment remains in the background and the new fragment comes on top of it. The replacement is not properly functional.

**Comment by Swati4star** [comment]
isnt it the intended behaviour? 
app should go back to home fragment only

**Comment by jddeep** [comment]
No i didn't mean that. wait i will post screenshot.

**Comment by Swati4star** [comment]
https://github.com/project-travel-mate/Travel-Mate/pull/615 should have taken care of the issue with back from fragments on home page. 
we wont be having a new issue for this. We can reopen the #615 only in this case

**Comment by jddeep** [comment]
@Swati4star In that case I don't need score for this. I will be making a PR for this and you don't need to reopen the earlier PR

**Comment by jddeep** [comment]
![Screenshot_20190419-151526](https://user-images.githubusercontent.com/43133646/56419573-59b43e80-62b8-11e9-856a-01fd4279f9dc.png)
![Screenshot_20190419-151530](https://user-images.githubusercontent.com/43133646/56419584-633da680-62b8-11e9-8569-a8a8335452d6.png)

**Comment by jddeep** [comment]
@Swati4star Have a look at above screenshots. Why do you think happens anyway? Like this problem is only with the `Trips` and `Friends` Fragments.

**Comment by jddeep** [comment]
@vyankatesh24

**Comment by Swati4star** [comment]
When I faced this issue, I changed the background color of whole fragment to white. I dont know if this is the right way to do so, but this works

**Comment by jddeep** [comment]
Okay then @Swati4star Do you want me to make a PR doing the same? Please tell me so but please don't reopen the previous PR. I would not want score for the new PR.

**Comment by Swati4star** [comment]
yeah, create a new PR
