### ISSUE TITLE
The app crashing when going to view city trend post by hashtag

### ISSUE THREAD

**Issue by maaudrana** [project-travel-mate/Travel-Mate#619]
<h4>Actual behavior</h4>
When i trying to view trends post by hashtag,app stuck and crashes.
<h4>Expected behavior</h4>
I expected that I can view trending post successfully by hashtag
<h4>How to reproduce</h4>
<ol>
<li>Download the latest version app from playstore.</li>
<li>Open the app</li>
<li>Creat account and login with mail and password.</li>
<li>Allow all the permission and start the app</li>
<li>From home page of the app choose any city and click the city name</li>
<li>Now click city trends</li>
<li>you will get a list of hash tag</li>
<li>click any hashtag to view city trends post</li>
<li>See error</li>
</ol>
Information
<ul>
<li>App version:v5.4.0</li>
<li>OS:Android 6.0.1,5.1</li>
<li>Device:Samsung J5,symphony v85</li>
</ul>
<h4>Recording of the bug</h4>
<a href="https://youtu.be/MfDFi9Chdt0">https://youtu.be/MfDFi9Chdt0</a>
<h4>Logcat</h4>
<pre>
<code>
E/AndroidRuntime(24184): FATAL EXCEPTION: main

E/AndroidRuntime(24184): Process: io.github.project_travel_mate, PID: 24184

E/AndroidRuntime(24184): java.lang.IllegalArgumentException: Unknown pattern character 'Y'

E/AndroidRuntime(24184): 	at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:314)

E/AndroidRuntime(24184): 	at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:303)

E/AndroidRuntime(24184): 	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:356)

E/AndroidRuntime(24184): 	at io.github.project_travel_mate.destinations.description.TweetsDescriptionAdapter.onBindViewHolder(TweetsDescriptionAdapter.java:60)

E/AndroidRuntime(24184): 	at io.github.project_travel_mate.destinations.description.TweetsDescriptionAdapter.onBindViewHolder(TweetsDescriptionAdapter.java:26)

E/AndroidRuntime(24184): 	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)

E/AndroidRuntime(24184): 	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)

E/AndroidRuntime(24184): 	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)

E/AndroidRuntime(24184): 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)

E/AndroidRuntime(24184): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)

E/AndroidRuntime(24184): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)

E/AndroidRuntime(24184): 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)

E/AndroidRuntime(24184): 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)

E/AndroidRuntime(24184): 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)

E/AndroidRuntime(24184): 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)

E/AndroidRuntime(24184): 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)

E/AndroidRuntime(24184): 	at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3225)

E/AndroidRuntime(24184): 	at android.view.View.measure(View.java:17570)

E/AndroidRuntime(24184): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5604)

E/AndroidRuntime(24184): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)

E/AndroidRuntime(24184): 	at android.view.View.measure(View.java:17570)

E/AndroidRuntime(24184): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5604)

E/AndroidRuntime(24184): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)

E/AndroidRuntime(24184): 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)

E/AndroidRuntime(24184): 	at android.view.View.measure(View.java:17570)

E/AndroidRuntime(24184): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5604)

E/AndroidRuntime(24184): 	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)

E/AndroidRuntime(24184): 	at android.view.View.measure(View.java:17570)

E/AndroidRuntime(24184): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5604)

E/AndroidRuntime(24184): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)

E/AndroidRuntime(24184): 	at android.view.View.measure(View.java:17570)

E/AndroidRuntime(24184): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5604)

E/AndroidRuntime(24184): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)

E/AndroidRuntime(24184): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)

E/AndroidRuntime(24184): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)

E/AndroidRuntime(24184): 	at android.view.View.measure(View.java:17570)

E/AndroidRuntime(24184): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5604)

E/AndroidRuntime(24184): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)

E/AndroidRuntime(24184): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2640)

E/AndroidRuntime(24184): 	at android.view.View.measure(View.java:17570)

E/AndroidRuntime(24184): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)

E/AndroidRuntime(24184): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)

E/AndroidRuntime(24184): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)

E/AndroidRuntime(24184): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)

E/AndroidRuntime(24184): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5895)

E/AndroidRuntime(24184): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)

E/AndroidRuntime(24184): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)

E/AndroidRuntime(24184): 	at android.view.Choreographer.doFrame(Choreographer.java:550)

E/AndroidRuntime(24184): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)

E/AndroidRuntime(24184): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(24184): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(24184): 	at android.os.Looper.loop(Looper.java:
</code>
</pre>

**Comment by maaudrana** [comment]
@Swati4star, @prabhakar267 can you view the issue.

**Comment by Swati4star** [comment]
Thanks for reporting the bug! We will try to fix it in future release

**Comment by bhavyakaria** [comment]
@Swati4star Can I fix this issue?

**Comment by Swati4star** [comment]
sure @bhavyakaria
