### ISSUE TITLE
Enhancing the UI/UX for the home screen

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#621]
For the cities that are marked on the right side on the home screen, the card functionality is working for more than once while on the left side it works well.

###  Expected behaviour 
The card should open only once.

### Actual behaviour
The card opens allows 3 openings, for the cities marked on the right side.

### Would you like to work on the issue?
Yes
### Screenshot

![BIDU](https://user-images.githubusercontent.com/43827236/56516477-2099f980-6558-11e9-9c3e-158d23c08905.gif)

**Comment by ShivangiSingh17** [comment]
@Swati4star, @prabhakar267, @thedevelopersanjeev, I would like to work on this issue.

**Comment by prabhakar267** [comment]
@ShivangiSingh17 Yeah go ahead
