### ISSUE TITLE
[ Travel Mate version 5.4.0 ] Unable to change my profile picture

### ISSUE THREAD

**Issue by XAMIR555** [project-travel-mate/Travel-Mate#622]
#### Project Information
* Repository    :  https://github.com/project-travel-mate/Travel-Mate
* Project Name  : Travel Mate
* Publisher     :  Swati Garg

#### Expected behavior
I expected that when I click on the camera button and choose an image from the phone gallery the profile picture should be changed

#### Actual behavior
after opening the profile when I try to change the profile picture in Travel Mate application. I cannot able to change my profile picture. you can see in bug video properly  

#### How to reproduce
* [Download ](https://play.google.com/store/apps/details?id=io.github.project_travel_mate)and open the application 
* click on your profile 
* click on the camera button 
* choose you image 
* refresh the page  or reopen  the profile page 
* Note the Bug
* Browser/App version:   5.4.0
* Operating system:  8.0.0 

#### Recording Of The Bug
https://youtu.be/W7kZYnAa-sQ
#### GitHub Account
https://github.com/XAMIR555

#### Logcat
<pre><code>04-21 02:30:48.457  5228  5228 E AndroidRuntime: FATAL EXCEPTION: main
04-21 02:30:48.457  5228  5228 E AndroidRuntime: Process: com.huawei.autoinstallapkfrommcc, PID: 5228
04-21 02:30:48.457  5228  5228 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.huawei.autoinstallapkfrommcc.InstallAPKReceiver: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3705)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(Unknown Source:0)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1979)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7425)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:312)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at com.huawei.autoinstallapkfrommcc.InstallAPKReceiver.onReceive(InstallAPKReceiver.java:42)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3695)
04-21 02:30:48.457  5228  5228 E AndroidRuntime: 	... 8 more
</code></pre>

**Comment by XAMIR555** [comment]
thank you  very much

**Comment by prabhakar267** [comment]
Closing this since it seems fixed!
@XAMIR555 Feel free to reopen if it isn't fixed
