### ISSUE TITLE
[ Travel Mate version 5.4.0 ]  In landscape mode Rename option is not working properly 

### ISSUE THREAD

**Issue by XAMIR555** [project-travel-mate/Travel-Mate#623]
#### Project Information
* Repository    :  https://github.com/project-travel-mate/Travel-Mate
* Project Name  :  Travel Mate
* Publisher     :  Swati Garg

#### Expected behavior

I expected that when I change the profile name   in landscape mode the profile name should be changed

#### Actual behavior

after opening the application when I try to change profile name in landscape mode   Profile name would not have been changed. you can see in bug video properly 

#### How to reproduce
* [Download ](https://play.google.com/store/apps/details?id=io.github.project_travel_mate)and open the application
*  click on your profile
*  rotate your phone screen portrait to landscape 
* click on  rename icon
* enter the new name 
* rotate your phone screen landscape to portrait  
* Note the Bug
* Browser/App version:    5.4.0
* Operating system:  8.0.0 

#### Recording Of The Bug
https://youtu.be/eSTs5xwlutY
#### GitHub Account
https://github.com/XAMIR555

# Logcat

[logcat.txt](https://github.com/project-travel-mate/Travel-Mate/files/3109410/logcat.txt)

**Comment by jddeep** [comment]
Thanks for pointing out the issue. @Swati4star Please provide some tags on it. I will work on it.

**Comment by Swati4star** [comment]
go ahead @jddeep

**Comment by XAMIR555** [comment]
good work
