### ISSUE TITLE
[ Travel Mate version 5.4.0 ] The Convert  button disappears in the landscape mode 

### ISSUE THREAD

**Issue by XAMIR555** [project-travel-mate/Travel-Mate#626]
#### Project Information
* Repository    :  https://github.com/project-travel-mate/Travel-Mate
* Project Name  :  Travel Mate
* Publisher     :  Swati Garg
* My GitHub account----:  [[Here]](https://github.com/XAMIR555)
#### Expected behavior

I expected that The Convert  button should not disappear in the landscape mode

#### Actual behavior

after opening the application and rotate the mobile screen portrait to landscape  The Convert button disappears.  You can see in bug video properly 

#### How to reproduce
* [Download ](https://play.google.com/store/apps/details?id=io.github.project_travel_mate)and open the application
* on your  phone auto-rotate mode 
*  click on the menu on the top left corner 
*   click  on Utilities 
* click on Currency Converter
* rotate the Mobile screen portrait to landscape 
* Note the Bug
* Browser/App version:  5.4.0
* Operating system:  8.0.0 

#### Recording Of The Bug
![final_5cc8047b43010d0013ce9ad7_532193](https://user-images.githubusercontent.com/49812927/56948712-d4196580-6ae5-11e9-8026-4fe79aed7eeb.gif)

**Comment by vincent-paing** [comment]
I think this can be fixed with `ConstraintLayout`, let me try this one

**Comment by Swati4star** [comment]
Sure @vincent-paing  👍
