### ISSUE TITLE
[ Travel Mate ][ version 5.4.0 ] In landscape mode of world clock i am unable select country and digital time disappears 

### ISSUE THREAD

**Issue by sourovafrin** [project-travel-mate/Travel-Mate#629]
#### Expected behavior

In world clock section user should be able to select country and watch the digital time under the analog clock on landscape mode same as portrait mode. If there is less space on landscape mode, the page should be scrollable.  

#### Actual behavior

While tried to the visit world clock page on landscape mode, the app page rotated in Such way which made me unable to select country and i was unable to see the digital time. The page wasn’t scrollable as well. This is a ui/ux error.
   
#### How to reproduce

- Turn on auto rotation and enter into the app
- Go to Utilities and click on World clock
- Now rotate your phone to landscape mode
- You will observer the same issue.

#### Possible Solution

This is a ui/ux bug, so i don't think a logcat is needed in this case. It can be fixed either by making the analog clock smaller or by making the page scrollable.       

#### Recording Of The Bug

https://youtu.be/577qryN739w

- Device Huawei y9 

- App version 5.4.0

- Operating system: Android 8.0.0

**Comment by jddeep** [comment]
Thanks for reporting the issue. @Swati4star Please add difficulty labels. I shall work on it.

**Comment by miso11** [comment]
Hi, can i work on this bug? Can you assign it to me?

**Comment by prabhakar267** [comment]
@miso11 sure you can go ahead.

**Comment by miso11** [comment]
Issue is solved on version 5.6.0, World clock is scrollable now. Do you need this fix on 5.4.0 version?

**Comment by Swati4star** [comment]
No. We don't want a fix in previous version.
Thank you for investigation this issue. Closing it now as fixed.
