### ISSUE TITLE
Show an alert after user clicks on sign out

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#63]
Show a confirmation alert after user clicks on sign out

**Comment by snufflesrea** [comment]
Will try working on this since it looks easy

**Comment by Swati4star** [comment]
Sure. Go ahead! Just show an alert saying "Are you sure you want to sign out?"
and 2 options : OK, Cancel

**Comment by Swati4star** [comment]
@snufflesrea Are you working on this one?

**Comment by brijeshshah13** [comment]
@Swati4star I would like to work on it if its still up for grabs.

**Comment by snufflesrea** [comment]
I am working on it

**Comment by Swati4star** [comment]
@brijeshshah13 This one is in-progress. You can pick up any other issue or create a new one.

**Comment by Swati4star** [comment]
Fixed by #88. Thanks to @snufflesrea 👍
