### ISSUE TITLE
I can't reset my password on Travel Mate Version 5.4.0

### ISSUE THREAD

**Issue by chrisbarth01** [project-travel-mate/Travel-Mate#630]
**Expected behavior**
- I expected my password to be reset and sent to my email when I click on 'SUBMIT' option. 

**Actual behavior**
- I typed in my email as requested and whenever I click on the 'SUBMIT' option, the app tells me that I imputed an invalid username or password and when I use my username, it tells me that I imputed an invalid Email

**How to reproduce**
- [Download](https://play.google.com/store/apps/details?id=io.github.project_travel_mate) and install the latest version of the Travel Mate app
- Launch the application  
- Click on forgot password 
- Type in your email ID as requested 
- Click on SUBMIT
- See error 

---

- App version: 5.4.0
- Device: Gionee f100s 
- Operating system: android version 6.0

---

**Recording of the bug**
- https://youtu.be/pxoSNVljfs4

---

**Proof that the account exists**
![PicsArt_04-25-03 44 49](https://user-images.githubusercontent.com/49325171/56744971-5f56cc00-6771-11e9-87d7-5386a5f21f86.png)

**Comment by chrisbarth01** [comment]
Hello @project-travel-mate, can anything be done about this error.

**Comment by chrisbarth01** [comment]
Hello @Swati4star, can anything be done about this bug as I really want to reset my password and login.

**Comment by Swati4star** [comment]
Thank you for reporting! @chrisbarth01 
We will work on it & fix it in future release

**Comment by jddeep** [comment]
@Swati4star I would like to work on this. Please confirm.

**Comment by Swati4star** [comment]
Sure @jddeep
