### ISSUE TITLE
Map unable to fetch item location and app crashed when I clicked on the menu button

### ISSUE THREAD

**Issue by cckole** [project-travel-mate/Travel-Mate#631]
###Discription

I clicked on the real time location to select items so that the map can display their locations. But it displayed a network error. I then went ahead to click the menu button on the map and the app crashed.

### Expected behaviour

I expected that when I selected the items and clicked on the okay button, the map was supposed to display the locations of the items. However, when I clicked on the menu button, I expected to see an option and not for the app to crash

### Reproducing the bug

After signing up and logging into the app
- Click on the menu ( there horizontal lines) by. the top left side of the app.
- Click on travel ( three options will be displayed)
- Click on "real time locator" (the map view will open up)
- Click on the icon with a Check mark beside the menu by the top right side of the app.(Items listed will be displayed)
- Select any of the items by checking the box/boxes.
- Click on select, you will see the network error "We are sorry we couldn't connect" 
- Click on the menu icon by the top right side of the app and note the crash.

### Reproducing the bug

https://youtu.be/eDOnjmhaRqA

### Device used: Tecno Spark K7

Operating system: Android 7.0

**Comment by cckole** [comment]
It started working perfectly this morning when I tried it again. I can say for now that the bug is ineffective.

**Comment by Swati4star** [comment]
Should we close this then @cckole ?

**Comment by cckole** [comment]
Yea. Sure you can close it. I've tried it several times and its working fine. That is a magic fix I guess. Smiles.
