### ISSUE TITLE
[ Travel Mate ][ version 5.4.0 ] Online shopping search result disappears on every rotation

### ISSUE THREAD

**Issue by sourovafrin** [project-travel-mate/Travel-Mate#632]
#### Expected behavior

On online shopping the search result should always show so the user don't need to search again after rotating the phone

#### Actual behavior

After rotating the phone the search result disappears and user need to search again which is quite irritating.
   
#### How to reproduce

- Turn on auto rotation and enter into the app
- Go to Travel and click on Online shopping
- Now search something by clicking the search icon
- After result being displayed, rotate your phone
- You will see the search result has disappeared and you have to search again

#### Recording Of The Bug

https://youtu.be/Gqjob5WlLKg

- Device Huawei y9 

- App version 5.4.0

- Operating system: Android 8.0.0

**Comment by prabhakar267** [comment]
@jm200dp Sure, go ahead.
