### ISSUE TITLE
Upgrading the gradle version

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#635]
### Describe the chore
Gradle version that is currently 3.2.1 should be updated to the latest version that 3.4.0 and the kotlin gradle plugin that is 1.2.71 should be upgraded to 1.3.31.

### Steps to reproduce
Check app level ```build.gradle``` file.

### Would you like to work on the issue?
Yes

**Comment by ShivangiSingh17** [comment]
@Swati4star

**Comment by Swati4star** [comment]
I'll update it myself. This isnt an issue. It's just a version update.

**Comment by ShivangiSingh17** [comment]
@Swati4star, I already made the changes to the branch. Shall I create a PR, please. :)
