### ISSUE TITLE
[Travel Mate][version 5.4.0]The app crashed if i click on my created trips.

### ISSUE THREAD

**Issue by maaudrana** [project-travel-mate/Travel-Mate#636]
<h4>Actual behavior</h4>
App crashes if i click on my trips to view trip details.
<h4>Expected behavior</h4>
Expected that i can on my trips and view details successfully without crash.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>click navigation bar select "My trips"</li>
<li>Create one trip by clicking "+" or if you have already trip list don't need to create.</li>
<li>Just click any trip you created</li>
<li>See the error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:V5.4.0</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/D1ZJ7uwRLKk">https://youtu.be/D1ZJ7uwRLKk</a>
<h4>Logcat</h4><pre>
<code>
04-28 15:31:23.994 31928 31928 E AndroidRuntime: FATAL EXCEPTION: main
04-28 15:31:23.994 31928 31928 E AndroidRuntime: Process: io.github.project_travel_mate, PID: 31928
04-28 15:31:23.994 31928 31928 E AndroidRuntime: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:974)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:950)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at io.github.project_travel_mate.mytrips.MyTripsFragment.lambda$onCreateView$0(MyTripsFragment.java:89)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at io.github.project_travel_mate.mytrips.-$$Lambda$MyTripsFragment$aagzd9bpdfL-txnYFNCy_aYdSnY.onItemClick(Unknown Source:2)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at io.github.project_travel_mate.mytrips.TripsListAdapter$TimelineViewHolder.onClick(TripsListAdapter.java:133)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at android.view.View.performClick(View.java:7339)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7305)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27788)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-28 15:31:23.994 31928 31928 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
</code></pre>

**Comment by jddeep** [comment]
@Swati4star i would work on this

**Comment by jddeep** [comment]
@Swati4star PR made. Please merge.

**Comment by maaudrana** [comment]
@jddeep Good job.
