### ISSUE TITLE
Adding more than one trip shows duplicated trips, and deleted trip seem not deleted. Still shows in the trip list

### ISSUE THREAD

**Issue by cckole** [project-travel-mate/Travel-Mate#639]
### Description 

In the "my trip" feature, I added my first trip and it was okay, but subsequent additional trip duplicates the already added ones in multiples.

### Another description

I'm reporting it together because it's almost the same.

When I removed my trip from the list of the added trip,it will show that my trip was removed but it still remains in my trip list.

### Expected behavior

I expected that adding subsequent trip should not duplicate the already existing trip. It ought to be added alone to it.

For the other one, I expected the trip I removed to be immediately deleted.

### Steps to reproduce

After signing up and entering the app

- Click on the three lines (menu) at the top left side of the app. 
- Click on my trip (it will display a blank page)
- locate a plus sign below by the left side and click on it.

- On the next page, fill every commands by entering your trip name,select trip date, and city, and click Add trip.

- Your trip will be created without without any duplicate.

- Press the plus button again to add another trip, fill the commands as usual and add another trip.

- The trip will be duplicated. The more you add trips, the more duplicate you get.

### For the trip that didn't delete, here are the steps to find it.

After following the above steps and creating a trip. 

- Click on any trip you create

- Click on the vertical dots by  the top right side of the app.(you will see a drop down) 

- Click on "remove me from list" and click OK to complete the action.

- The trip would be removed successfully, but you will still find it on the list.

### Additional information

The behavior of these bugs isn't normal. However, the bug reset itself when you move out from the page and go back in. So you would need to create trip, move out and go back in before the app works perfectly. 
Also, you will need to remove trip, move out and move back in before the trip is finally removed.

### Reproducing the bug.

- ***Video for Duplicated trips***
https://youtu.be/fL0PlTlpyrw

- ***Video for Trip not removed***

https://youtu.be/BtSK0ecW5A4

- Device used
Techno spark K7
- Operating system: Android 7.0

**Comment by vincent-paing** [comment]
Will check and see what I can do

**Comment by Swati4star** [comment]
Sure @vincent-paing

**Comment by miso11** [comment]
Hi, i can not reproduce it on Android 5.0.1 API 22m application version: 5.6.1. Maybe issue has been already solved.

**Comment by prabhakar267** [comment]
We can close this then. Please reopen if this issue is still there.
