### ISSUE TITLE
First trip added not showing on my friend list

### ISSUE THREAD

**Issue by cckole** [project-travel-mate/Travel-Mate#640]
### Description 

I added a friend to my trip and clicked on "my friend" to see if the friend was added. I got a message that "I haven't added any friend to trip". I added another trip and checked again. Now I saw both trips. Meaning that if only one trip is added, the app cannot fetch it.

### Expected behavior

I expected to see the first friend I added to my trip when I clicked on " my friend" to check 

### Steps to reproduce

After signing up and entering the app

- Click on the three lines (menu) at the top left side of the app. 

- Click on my trip(It will display a blank page)

- locate a plus sign below by the left side and click on it.

- On the next page, fill every commands by entering your trip name,select trip date, and city, and click Add trip.

- Your trip will be added.

- After adding a trip, click on it. 

- On the shown page, enter friends name.(Note that friend name is an email address)

- Click on add new friend

- Go back and click on the menu button by top left side.

- Click on my friend. You will get a message that "you've not added any friend to tri

Video. First added friend no showing

https://youtu.be/FVv25TVmzEI 

***Device used***: Techno spark K 7
***Operating system
Android 7.0

**Comment by prabhakar267** [comment]
Closing this since it seems fixed!
@cckole Feel free to reopen if it isn't fixed
