### ISSUE TITLE
( Bug found in Tavel-Mate version 5.5.0 ) In the Real time locator tab app is crash when i click on the 3 horizontal dots

### ISSUE THREAD

**Issue by saraji-ali** [project-travel-mate/Travel-Mate#648]
# Project Information

* Repository: https://github.com/project-travel-mate/Travel-Mate
* Project Name:  Travel-Mate

# Expected behavior

I was expecting that   when I click on the 3 horizontal dots there are show more option 

# Actual behavior

open the application goto travel and open the Real Time Locator tab and then click on the 3 horizontal dots   the Tavel-Mate version 5.5.0  is crash 

# How to reproduce

1-[Download latest application](https://f-droid.org/packages/io.github.project_travel_mate/)
2-install and open the application
3-click on Travel
4-click on REAL TIME LOCATOR
5- click on 3 horizontals dots
6- see bug 
* Browser/App version:  Tavel-Mate version 5.5.0
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190501_122232](https://user-images.githubusercontent.com/50115498/57008977-acd79c80-6ba8-11e9-9fae-fdf5fe9810b0.gif)

# My Github Account
https://github.com/facebook-786

# Logcat
<pre><code>D/AndroidRuntime(10249): Shutting down VM

E/AndroidRuntime(10249): FATAL EXCEPTION: main

E/AndroidRuntime(10249): Process: io.github.project_travel_mate, PID: 10249

E/AndroidRuntime(10249): java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.project_travel_mate/io.github.project_travel_mate.travel.ListViewRealTimeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.osmdroid.views.MapView.getContext()' on a null object reference

E/AndroidRuntime(10249): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)

E/AndroidRuntime(10249): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)

E/AndroidRuntime(10249): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)

E/AndroidRuntime(10249): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)

E/AndroidRuntime(10249): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(10249): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(10249): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(10249): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(10249): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(10249): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(10249): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime(10249): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.osmdroid.views.MapView.getContext()' on a null object reference

E/AndroidRuntime(10249): 	at org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.<init>(MyLocationNewOverlay.java:100)

E/AndroidRuntime(10249): 	at utils.GPSTracker.displayLocationRequest(GPSTracker.java:154)

E/AndroidRuntime(10249): 	at io.github.project_travel_mate.travel.ListViewRealTimeActivity.onCreate(ListViewRealTimeActivity.java:55)

E/AndroidRuntime(10249): 	at android.app.Activity.performCreate(Activity.java:6178)

E/AndroidRuntime(10249): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)

E/AndroidRuntime(10249): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)

E/AndroidRuntime(10249): 	... 10 more
</cod></pre>

**Comment by prabhakar267** [comment]
Closing this since it seems fixed!
@saraji-ali  Feel free to reopen if it isn't fixed
