### ISSUE TITLE
( Bug found in Tavel-Mate version 5.5.0 ) the application is crash when I try to change the username 

### ISSUE THREAD

**Issue by facebook-786** [project-travel-mate/Travel-Mate#649]
# Project Information

* Repository: https://github.com/project-travel-mate/Travel-Mate
* Project Name:  Travel-Mate

# Expected behavior
I was expecting that when I try to change the username  the username should be changed easily 

# Actual behavior

the application is crash when I try to change the username 

# How to reproduce
1-[Download latest application](https://f-droid.org/packages/io.github.project_travel_mate/)
2-install and open the application
3- Go to profile
4- click on Edit icon of username 
5- enter the new username 
6- click on the save button
7- see the bug
* Browser/App version:  Tavel-Mate version 5.5.0
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190501_124027](https://user-images.githubusercontent.com/50115498/57009407-3ee0a480-6bab-11e9-88dd-08a3c0577b5e.gif)

# My Github Account
https://github.com/facebook-786

# Logcat
<pre><code>D/AndroidRuntime(12644): Shutting down VM

E/AndroidRuntime(12644): FATAL EXCEPTION: main

E/AndroidRuntime(12644): Process: io.github.project_travel_mate, PID: 12644

E/AndroidRuntime(12644): java.lang.StringIndexOutOfBoundsException: length=3; regionStart=0; regionLength=-1

E/AndroidRuntime(12644): 	at java.lang.String.startEndAndLength(String.java:504)

E/AndroidRuntime(12644): 	at java.lang.String.substring(String.java:1333)

E/AndroidRuntime(12644): 	at io.github.project_travel_mate.ProfileActivity.setUserDetails(ProfileActivity.java:475)

E/AndroidRuntime(12644): 	at io.github.project_travel_mate.ProfileActivity.lambda$onCreate$0(ProfileActivity.java:181)

E/AndroidRuntime(12644): 	at io.github.project_travel_mate.-$$Lambda$ProfileActivity$uMfJn8YicZHKcJUSAPpQOXOVDEQ.onClick(lambda)

E/AndroidRuntime(12644): 	at android.view.View.performClick(View.java:5076)

E/AndroidRuntime(12644): 	at android.view.View$PerformClick.run(View.java:20279)

E/AndroidRuntime(12644): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(12644): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(12644): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(12644): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(12644): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(12644): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(12644): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(12644): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by malieop** [comment]
I will resolve this bug

**Comment by Swati4star** [comment]
Sure. Pleae create a PR for the fix @malieop 👍
