### ISSUE TITLE
App crashes after clicking 'call' button

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#65]
Login to the app
Go to Emergency contacts
Click on any 'CALL' button.
The app crashes.

**Comment by Niranjan-B** [comment]
I can take this up. Will open a PR in a couple of hours.

**Comment by Swati4star** [comment]
Fixed by dea7f6aa9819fe27928078a626aa42169a0f7d29 . Thanks to @Niranjan-B 👍
