### ISSUE TITLE
Scrolling is unavailable   

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#650]
The scroll is not working for the world clock activity under ```Utilities```

### Steps to reproduce
Choose ```World clock``` from ```Utilities```and switch to landscape mode.

### Expected behaviour
The time zone selection list option should appear, allowing the scroll function.

### Actual behaviour
Only the clock appears on the screen.

### Would you like to work on the issue?
Yes
### Screenshot
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43827236/57023698-558d0700-6c50-11e9-9488-4c99db30d508.gif)

**Comment by ShivangiSingh17** [comment]
@Swati4star @thedevelopersanjeev, Shall I work on this issue?

**Comment by Swati4star** [comment]
Go ahead @ShivangiSingh17

**Comment by Swati4star** [comment]
@ShivangiSingh17 Please work on previously claimed issues first!

**Comment by jddeep** [comment]
Yes @Swati4star I can see that @ShivangiSingh17 has been holding #568 and #569 as well for a long time. But how was she allowed to solve further issues?

**Comment by Swati4star** [comment]
I didnt realize she was holding multiple issues. Now, I have noted it & already mentioned in the comment as you can see.

@jddeep If you want to claim any open issue, please comment on that
