### ISSUE TITLE
Error symbol cannot be seen properly

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#651]
In the ```Settings```, when the ```Done``` button is clicked without any input, the warning is shown but the two icons collide and not seen properly. 
### Steps to reproduce
Choose ```Settings``` from the home screen and without any input  click on the ```Done``` option.

### Expected behaviour
Both symbols should be seen separately and clearly for the user convenience.

### Observed behaviour
The two symbols collide together resulting in no clear view.

### Would you like to work on this issue?
Yes
### Screenshot
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/43827236/57027716-c9341180-6c5a-11e9-9a30-f6dab8cc64ff.gif)

**Comment by ShivangiSingh17** [comment]
@Swati4star @thedevelopersanjeev, Shall I work on this issue?

**Comment by thedevelopersanjeev** [comment]
sure @ShivangiSingh17

**Comment by Swati4star** [comment]
@ShivangiSingh17 Complete previously claimed issues first. This is open for others to pick currently

**Comment by OlgaMorales** [comment]
hi @ShivangiSingh17  I was working on this issue and I solved it setting the error in the InputLayout instead the editText, I'll send my PR, please check it and tell me what do you think about it?
