### ISSUE TITLE
TravelMate  v.5.5.0 says reset code has been sent to my unregistered email

### ISSUE THREAD

**Issue by realrufans** [project-travel-mate/Travel-Mate#652]
## Expected behavior
I was expecting it to toast an error message that an email isn't registered while trying to get a reset  code via email.

## Actual behavior
It says , ```A new code has been sent``` when the user clicks on **Didn't get the code ? resend**

## How to reproduce
- Launch travelMate v 5.5.0
- click on forget password?. Then, enter 
an unregistered email, then click the submit button
-  Click on a button down the screen that says, **Didn't get the code ? resend** 
-  you'll see a message that says; ```A new code has been sent.```

# Screenshot
![Screenshot_20190503-233233.png](https://cdn.steemitimages.com/DQmXjjwMEzrvSQsabetCNnfJPheyK23wKd5b37A5Urmenkh/Screenshot_20190503-233233.png)

* Browser/App version: Tavel-Mate version 5.5.0
* Android version 8

**Comment by realrufans** [comment]
```Didn't get the code ? resend``` shouldn't show when an emails is invalid/ not registered

**Comment by Swati4star** [comment]
sure @gateway2rohan

**Comment by prabhakar267** [comment]
Closing this since it seems fixed!
@realrufans Feel free to reopen if it isn't fixed
