### ISSUE TITLE
Background image quality on home screen is pixelated .Specially on portrait mode.Seems like landscape image used in portrait. 

### ISSUE THREAD

**Issue by GauravDixit11** [project-travel-mate/Travel-Mate#653]
![Screenshot_20190504-204946](https://user-images.githubusercontent.com/22414838/57181934-64292780-6eb7-11e9-848c-fe3dd7a281c8.png)

Version : 5.4.0
Description :
Portrait :Background image quality on home screen is pixelated or tear down.

Steps to reproduce :
1.Load the app.
2.Observe the background image quality after loading on home screen.

Actual :Image quality is not sharpen as it should be on home screen.
Expected : Image quality should be sharp and visible without any pixelated effects.

**Comment by Abhishekds94** [comment]
@GauravDixit11 @Swati4star Instead of using it as an ImageView, use it as a background in the parent tag.
Eg - android:background="@drawable/your_image_name"

Let me know if this doesn't work.
