### ISSUE TITLE
Landscape : Link Text "forgot password" and "create new account" are almost overlapped.Unable to click on link once in a time.

### ISSUE THREAD

**Issue by GauravDixit11** [project-travel-mate/Travel-Mate#654]
![Screenshot_20190504-204458](https://user-images.githubusercontent.com/22414838/57182429-72c60d80-6ebc-11e9-9f7b-9d4a2413d314.png)

Version : 5.4.0
Description :
Landscape : Link Text "forgot password" and "create new account" are almost overlapped.Unable to click on link once in a time.

Steps to reproduce :
1.Load the app in landscape mode.
2.Observe "forgot password" and "create new account" links.
3.Try to click on them.

Actual :As both the links are not correct aligned as per landscape mode due to which their functionality is not working correct.
Expected : Alignment of "forgot password" and "create new account" links should be correct with proper spacing .Functionality should be work fine.

**Comment by nasreekar** [comment]
Can I take this up?

**Comment by Swati4star** [comment]
Sure @nasreekar

**Comment by nasreekar** [comment]
@Swati4star  Update: sorry for the delay. I was busy with some office work and also traveling. Will try to complete it asap.

**Comment by prabhakar267** [comment]
@nasreekar Any update?

**Comment by miso11** [comment]
I can take a look on it. Can you assign it to me?

**Comment by nasreekar** [comment]
@prabhakar267  Sorry Prabhakar (for both late reply and no update).. was a little busy with office work (currently on site) and couldn't fix the bug.

**Comment by prabhakar267** [comment]
@miso11 You can have a look into this
