### ISSUE TITLE
Signup snackbar error for a new user.

### ISSUE THREAD

**Issue by jddeep** [project-travel-mate/Travel-Mate#661]
**Description**
Signup snackbar error for a new user.
![Screenshot_20190515-150151](https://user-images.githubusercontent.com/43133646/57765751-aeb26b80-7723-11e9-9b74-ebab5d957e81.png)

The snack bar has some meaningless message shown when the user clicks on sign up.

**Steps to reproduce:**
The user fills up the details, clicks on sign up and a misleading snack bar pops up.

I would like to work on this.

**Comment by jddeep** [comment]
@Swati4star Please provide difficulty tags.

**Comment by Swati4star** [comment]
@jddeep you can work on this

**Comment by Group4-GUSTO** [comment]
Have you been able to fix this? Please do so I’m facing difficulty without using this app during my travel here before going back in a the after tmr

**Comment by prabhakar267** [comment]
Closing this since it seems fixed!
@jddeep  Feel free to reopen if it isn't fixed
