### ISSUE TITLE
App keeps popping up invalid email when I put in my email to reset my password.

### ISSUE THREAD

**Issue by darewealth** [project-travel-mate/Travel-Mate#662]
### Describe the bug.

I forgot the password I used for the application and I used the function down  below the app "Forget password feature." When I  checked on it, a page pops up asking for my email ID.  I put in my email but the app says my email is invalid. Invalid email keeps popping up. Whereas I am sure that it is the email that I used. 

### Steps to reproduce.
* Launch the app.

* Clicked on forgot password 

* Then, put in your email 

*  Submit and note the bug

### Expected Behaviour

I expect that there should be a message that a reset password as been sent to my email not invalid email.

### Screen recording
https://youtu.be/PA8fTcH9lGU

### Devices and Versions):)
* Device: [Itel]

* Version [6.1]

* App version [5.5.0]

**Comment by lewisgarton** [comment]
Hi team, I would like to contribute to this project!
Can I work on this one?

Thanks.

**Comment by sr1990** [comment]
Can reproduce this issue for a registered user. 
I get a 400 bad request response as follows: 
Response{protocol=http/1.1, code=400, message=Bad Request, url=https://project-travel-mate.herokuapp.com/api/forgot-password-email-code/<email>}
The res in onResponse() has "Unable to send a forgot password email to user".
Should 400 errorcode be handled in this case to show the above response or 
should there be a change to request url?

**Comment by Swati4star** [comment]
@prabhakar267 can you see why are we getting this error message for valid credentials?

@sr1990 yes please, let's show the "res" value message in our app. That'll be helpful.
