### ISSUE TITLE
Login in with correct credentials is showing invalid username or password

### ISSUE THREAD

**Issue by cckole** [project-travel-mate/Travel-Mate#663]
### App info
- Travel mate V.5.5.0
- [GITHUB LINL](https://github.com/project-travel-mate/Travel-Mate/issues/663_
### Description
I was having a full memory, so I had to uninstall some apps on my device for a free space and Travel mate happens to be one of them. Later, I installed it and tried to log in but, upon using the right username and password, I couldnt log in.

### Expected behaviour
Since I'm using the right usename, and password, I should be able to log in succesfully

### Reproducint the behaviour

If you are signed in already, log out 

- input your username and password in the provided space 

- Press the sign in button. You will get a message below saying invalid username or password.

### Video

https://youtu.be/xeYcCrP5whI

### Device used
Techno spark K7
Android 7.0

**Comment by ameyand98** [comment]
Hello can I work on this issue? Please assign it to me

**Comment by Swati4star** [comment]
Can you please check if this issue is still valid? I think, this is resolved. @ameyand98

**Comment by ameyand98** [comment]
Sure

**Comment by prabhakar267** [comment]
Closing this since it seems fixed!
@cckole Feel free to reopen if it isn't fixed
