### ISSUE TITLE
The currency converter does not work. 

### ISSUE THREAD

**Issue by darewealth** [project-travel-mate/Travel-Mate#664]
### Describe the bug.

I tried to convert currency using the currency converter but it kept loading without any results.

### Steps to reproduce.
* Launch the app.

* Click on the menu and go to utilities 

* Then, click on currency converter 

*  And convert any currency 

* And note the bug

### Expected Behaviour

I expected that I should be able to convert from one currency to another 

### Screen recording
https://youtu.be/0oLl_G2OnIA

### Devices and Versions):)
* Device: [Gionee]

* Version [7.0]

* App version [5.5.0]

**Comment by blongho** [comment]
I would like to fix this

**Comment by ameyand98** [comment]
Hey can I take up this issue?

**Comment by Swati4star** [comment]
Sure @ameyand98

**Comment by prabhakar267** [comment]
@Swati4star @ameyand98 @darewealth Currency converter issue has been fixed in https://github.com/project-travel-mate/server/commit/bb6fa001851b564cc91d08b67a19dc41da8f93c9
Please reopen this issue if there is any other issue
