### ISSUE TITLE
(BUG) [ Travel Mate ]  I click on the Google play store button and the application opens on F-Droid

### ISSUE THREAD

**Issue by XAMIR555** [project-travel-mate/Travel-Mate#666]
#### Project Information
* Repository-----------:[Here](https://github.com/project-travel-mate/Travel-Mate)
* Project Name---------: Travel Mate
* Publisher------------:  Swati Garg
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior

The google play store should open when I click on the google play store button and the travel-mate application should also appear on google play store.

#### Actual behavior

When I click the google play store button, google play store does not open, but f -droid opens

#### How to reproduce
* Open [github ](https://github.com/project-travel-mate/Travel-Mate) link on mobile
* Click the Google Play Store button
* Note the Bug

* Operating system----: 9.0.0

#### Recording Of The Bug

![20190517_144358](https://user-images.githubusercontent.com/49812927/57920632-588f1680-7850-11e9-9b89-ef3995590e69.gif)

**Comment by prabhakar267** [comment]
Seems to be fixed now.
Closing this issue.
