### ISSUE TITLE
(BUG) [ Travel Mate version 5.5.0 ] New account is not registering

### ISSUE THREAD

**Issue by XAMIR555** [project-travel-mate/Travel-Mate#667]
#### Project Information
* Repository-----------:[Here](https://github.com/project-travel-mate/Travel-Mate)
* Project Name---------: Travel Mate
* Publisher------------:  Swati Garg
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior
When I click on the signup button after entering all of my information and after clicking on I signup, my account should be register.
#### Actual behavior

When I try to create a new account, the new account is not registered you can see in bug video properly 

#### How to reproduce
* open the application
* click on the create new account
* Enter all your information
* click on Signup Button
* Note the Bug
* Browser/App version-: 5.5.0 
* Operating system----: 9.0.0

#### Recording Of The Bug

![20190517_150756](https://user-images.githubusercontent.com/49812927/57921466-41e9bf00-7852-11e9-9e8d-cf3b860b45f2.gif)

**Comment by asoback** [comment]
I'm getting the same issue after downloading from the play store.

**Comment by Group4-GUSTO** [comment]
Can you login though?

**Comment by Group4-GUSTO** [comment]
Can someone plz fix this issue? I have tried but server side is too hard for me

**Comment by Swati4star** [comment]
There are some server issues. We are working on that.

**Comment by SafalShrestha369** [comment]
hello guys 
how to login first, I m very beginner of android 
so please help me, it asking me email id and password. What might be password and email id or something else

**Comment by Swati4star** [comment]
Server issues have been fixed now. You should be able to signup.
