### ISSUE TITLE
Scrolling unavailable in the login screen 

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#672]
### Description
The login screen does not allow the user to scroll down, thereby restricting the screen contents from being viewed like button is not visible as there is no scrolling of the page.
### Steps to reproduce:
The user switches to use the app in landscape mode.

### Would you like to work on this issue?
Yes

### Screenshot
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43827236/58149526-fafc2f00-7c80-11e9-883c-cf9a12ab48a4.gif)

**Comment by ShivangiSingh17** [comment]
@Swati4star @thedevelopersanjeev I would like to work on this.

**Comment by Group4-GUSTO** [comment]
Cannot login or sign up its keeps crashing saying <!DOCTYPE html> <html>..

**Comment by ShivangiSingh17** [comment]
@Group4-GUSTO as suggested by you, that is not what I am dealing with. That is already an issue and yet to be solved: https://github.com/project-travel-mate/Travel-Mate/issues/661

**Comment by Group4-GUSTO** [comment]
Sry but can you please tell me if you can login? Because I cant login with
account that is already created

**Comment by ShivangiSingh17** [comment]
Today I by mistake I uninstalled my app also and now even I am also not
able to log in. I asked mentors also but no reply yet. I even contacted the
person solving issue #661 but he is also not able to follow the same.
It is better to ask on the community slack channel.
Warm Regards,
Shivangi Singh
GitHub <https://github.com/ShivangiSingh17> | Blog
<https://aeonianchapters.wordpress.com/> | amFoss <http://amfoss.in>
Amrita Vishwa Vidyapeetham <http://amrita.edu>

**Comment by Group4-GUSTO** [comment]
Noted and thank you I hope the issue gets solved sooner since I use the app
real time locator to travel
