### ISSUE TITLE
Incorrect message displayed

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#673]
### Description 
When the user clicks on the ```Forgot password``` then while inputting credentials the application displays misguiding message when the user clicks on submit button.
Initially, it functions well but in the end, it displays incorrect message.
***##For a registered user***

### Steps to reproduce
Click on ```Forgot Password? Click here to reset.```. Enter your E-mail and click on ```SUBMIT``` button. See the message displayed.
### Would you like to work on this issue?
Yes
### Screenshots
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/43827236/58150601-becacd80-7c84-11e9-9bec-cba1a07ce778.gif)

**Comment by ShivangiSingh17** [comment]
@Swati4star please label the issue.

**Comment by Group4-GUSTO** [comment]
I think its probably the server crashes and send back the wrong response that contains html  -> https://stackoverflow.com/questions/42096207/value-doctype-of-type-java-lang-string-can-not-be-converted-to-jsonobject

**Comment by Swati4star** [comment]
The issue has been fixed now. It indeed was because of server.
