### ISSUE TITLE
Main Screen activity repeats itself when opened after long time

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#676]
### Description
The main screen activity repeats itself when the application is opened after a long time and once refreshed retains the original (correct) activity.

### Steps to reproduce
Open the application after a long time and scroll down the main screen.

### Would you like to work on this issue?
Yes

### Screenshots
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/43827236/58277411-4d3f6c00-7db7-11e9-9f5f-c0d7cbcd3bc8.gif)

**Comment by ShivangiSingh17** [comment]
@Swati4star @prabhakar267 @thedevelopersanjeev  I would like to work on this issue. Shall I proceed?

**Comment by Group4-GUSTO** [comment]
How is it possible that are you able to login and use the app?

**Comment by ShivangiSingh17** [comment]
I'm able to do so through another device in which I didn't signout through
the application.
Also I suggest for you that once you have the code base you can directly
use the emulator in android studio making sure changes in small
functinalities.

**Comment by Swati4star** [comment]
No @ShivangiSingh17 You may not start working on this issue. Send PR for previously claimed issues first.

Let's follow basic open source principles. If you have claimed a issue, finish that up first or comment that you are not going forward with that.

**Comment by Swati4star** [comment]
This issue is not reproducible now. Closing it.
