### ISSUE TITLE
The activity multiplies in itself on refreshing

### ISSUE THREAD

**Issue by ShivangiSingh17** [project-travel-mate/Travel-Mate#678]
### Description
On refreshing the page the activity multiplies itself as per the RefreshView happen.

### Steps to reproduce
Go to ```My Trips``` refresh your page.

### Screenshots
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/43827236/58433218-bbe03a80-80d3-11e9-83d8-f8ac83e93fbe.gif)

### Would you like to work on this issue?
Yes

**Comment by Swati4star** [comment]
@ShivangiSingh17 Are you willing to work on it now?

**Comment by ShivangiSingh17** [comment]
I would like to continue in mere future. :)

**Comment by aman0408** [comment]
Can I work on this issue?

**Comment by RMVIVEK55** [comment]
I when  do you refresh data list and also list  clear (newly adding data clear the list)

**Comment by Swati4star** [comment]
sure @aman0408

**Comment by aman0408** [comment]
> sure @aman0408

I am unable to reproduce the error. I think it has been fixed already.

**Comment by Swati4star** [comment]
I'll close this issue then :)
