### ISSUE TITLE
Broken link in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by gifmackenzie** [project-travel-mate/Travel-Mate#689]
Under "Pull Requests Process", the  "TRAVIS" link is broken (opens up "https://github.com/project-travel-mate/Travel-Mate/blob/master/Travis-ci.org" rather than the intended link : "Travis-ci.org"

**Comment by charlygg** [comment]
Hi, Is this issue open to contribute?

**Comment by Swati4star** [comment]
yes @charlygg 
You can create a PR for this
