### ISSUE TITLE
Login Screen cropped

### ISSUE THREAD

**Issue by nasreekar** [project-travel-mate/Travel-Mate#694]
Description
I tried to clone the repo and installed the app on both emulator and a real device and I found the login screen cropped

What the current behavior is?
Login Screen is cropped to half 

What behavior should?
Login screen should be completely filling the mobile screen like the one in the play store.

Devices Used:
Galaxy Note 8 - Android 9, API 28
Pixel 2 XL API 28
Nexus 6 API 27

[![Screenshot-20190726-094903-Travel-Mate.jpg](https://i.postimg.cc/SKP1kGXB/Screenshot-20190726-094903-Travel-Mate.jpg)](https://postimg.cc/gwvHK8Hs)

**Comment by valericaplesu** [comment]
pull request here: https://github.com/project-travel-mate/Travel-Mate/pull/695

**Comment by Swati4star** [comment]
Great @valericaplesu 👍
