### ISSUE TITLE
toast message is showing when navigating back to login

### ISSUE THREAD

**Issue by vaibhavsharma316** [project-travel-mate/Travel-Mate#697]
![Screenshot_1566124474](https://user-images.githubusercontent.com/17318663/63223378-099ba900-c1d2-11e9-89f6-7def6a0d0fa5.png)

**Current Behaviour**

Snackbar is showing a message "your password has been reset. Login with the new password" when moving back to login screen from forgot password screen. (I have not done password reset but still it shows this message).

**Steps to reproduce**

1. Click on Forgot password 
2. Forgot password screen will be opened 
3. Then click on back to login
4. It shows the snackbar with a message

**Expected Behaviour**

It should show the message on forgot password screen only when password is actually changed in the backend.

**Comment by vaibhavsharma316** [comment]
@Swati4star  - shall i start working on this ?

**Comment by Swati4star** [comment]
sure @vaibhavsharma316 
The playstore build is not updated.

**Comment by prabhakar267** [comment]
@vaibhavsharma316 any updates?

**Comment by RMVIVEK55** [comment]
Can you return bool flag value from user click the submit button

**Comment by RMVIVEK55** [comment]
if the use the use click the submit button set true and not click or back press set value false.
and login openLogin check the bool value if true show toast message other dont toasr

**Comment by prabhakar267** [comment]
@RMVIVEK55 can raise a PR for the fix

**Comment by ambika1101** [comment]
i'd like to work on this

**Comment by Swati4star** [comment]
Sure @ambika1101

**Comment by pintu236** [comment]
anybody working on it?

**Comment by droid-it** [comment]
Is it open to be picked up? If yes, I would like to pitch in!

**Comment by Swati4star** [comment]
@ambika1101 Updates?
@pintu236 You may work in it, if ambika doesn't reply.

**Comment by dekzitfz** [comment]
is it still open to be picked up? I'll open PR for this :D
