### ISSUE TITLE
Kotlin Version Problem

### ISSUE THREAD

**Issue by sukhbeer** [project-travel-mate/Travel-Mate#701]
Kotlin Has some problem that creates a warning in code.
![Screenshot (27)](https://user-images.githubusercontent.com/25095372/63362815-11a14780-c390-11e9-9952-0060088feafd.png)

**Comment by Swati4star** [comment]
These are just warnings. You can submit a fix to update kotlin version.

**Comment by light-kira** [comment]
Is the kotlin version updated ?
