### ISSUE TITLE
Navigate to Currency converter activity on pressing back button from error (animation) screen 

### ISSUE THREAD

**Issue by nasreekar** [project-travel-mate/Travel-Mate#702]
If there is an error with the converter, it is showing an animation but then clicking on the back button is dismissing the whole activity and navigating the user to utilities fragment. It would be great if the user is navigated to the currency converter activity instead of utilities so that the user doesn't have to do it again from the beginning.

**Comment by sankalpchauhan-me** [comment]
I would like to work on this issue, Thanks

**Comment by Swati4star** [comment]
sure @sankalpchauhan-me
