### ISSUE TITLE
Future trip date not selected of current month.

### ISSUE THREAD

**Issue by AminullahTajMuhammad** [project-travel-mate/Travel-Mate#703]
## Current Behaviour

When I selected future date of this month like this.

![after_estimote](https://user-images.githubusercontent.com/43150539/63638182-3f430500-c69e-11e9-8da2-cc1262773942.png)

after clicking ok button. It gives error massage on snakeBar like this.

![snackbar](https://user-images.githubusercontent.com/43150539/63638169-19b5fb80-c69e-11e9-9195-5f5ace18aa5e.png)

But when I selected any date of next month. It works fine

## Expectec Behaviour:
- When I select current date it shows a time dialog
- When I select current date and current time it show a error that select future date or future time
- When I select future date of this month or any other month it book my trip

**Comment by Swati4star** [comment]
@AminullahTajMuhammad  What is the expected behaviour here?
Please fill up the issue template. It gives clearer information.

**Comment by AminullahTajMuhammad** [comment]
issue updated

**Comment by AminullahTajMuhammad** [comment]
@Swati4star can I do this?

**Comment by Swati4star** [comment]
Yes @AminullahTajMuhammad 👍
