### ISSUE TITLE
Validate user sign up details

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#71]
On signup : 
- Add checks for a valid and non-empty email id
- Add check for a valid and non-empty password
- Add a different field for first name & last name

Show proper error messages for each.

**Comment by momen-ghulmi** [comment]
there isn't any phone number field in signup

**Comment by Swati4star** [comment]
@momen-ghulmi Thanks for pointing it out. I have updated the issue description.

**Comment by momen-ghulmi** [comment]
what are your criteria for a valid password ?

**Comment by syedjahangirpeeran** [comment]
I would like to work on it

**Comment by Swati4star** [comment]
@momen-ghulmi Are you working on this one?

**Comment by brijeshshah13** [comment]
@Swati4star @momen-ghulmi hasn't replied since 2 days and I believe @syedjahangirpeeran is dealing with some other issue. Is this still up for grabs?

**Comment by Swati4star** [comment]
Actually, his PR was almost ready https://github.com/project-travel-mate/Travel-Mate/pull/73

That's why I was waiting for him to reply. Let's wait till tomorrow. If he doesn't reply by tomorrow. We'll consider him not working on this issue & make it up for grabs.

**Comment by Swati4star** [comment]
@brijeshshah13 @syedjahangirpeeran This issue is up-for-grabs now. You can pick it up (if you are not holding any other issue)

**Comment by syedjahangirpeeran** [comment]
i would like to take it

**Comment by Swati4star** [comment]
Sure 👍

**Comment by Swati4star** [comment]
You can take help from the #73 PR

**Comment by syedjahangirpeeran** [comment]
![screenshot_20180626-231854](https://user-images.githubusercontent.com/26850482/41930428-a514514e-7998-11e8-8f89-41aeee4d0139.png)

**Comment by Swati4star** [comment]
@syedjahangirpeeran Any questions?

**Comment by syedjahangirpeeran** [comment]
I submitted the PR.

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/151
