### ISSUE TITLE
Time shown in world clock is incorrect

### ISSUE THREAD

**Issue by HeinKhantZaw** [project-travel-mate/Travel-Mate#717]
![Screenshot_2019-10-03-02-54-31-802_io github project_travel_mate](https://user-images.githubusercontent.com/40730345/66079301-cb8ff400-e589-11e9-8eda-3babdb089168.png)
In the world clock setting of the app, the time shown according to the time zone are incorrect. Not only for Yangon, I found that there are several time zones that are showing incorrect time. 
![Screenshot_2019-10-03-02-54-52-698_io github project_travel_mate](https://user-images.githubusercontent.com/40730345/66079436-0e51cc00-e58a-11e9-86c6-4f52bc8c939e.png)
![Screenshot_2019-10-03-02-55-08-497_io github project_travel_mate](https://user-images.githubusercontent.com/40730345/66079443-114cbc80-e58a-11e9-95fb-cc0079cfba37.png)
I want to tell that I will try to fix this issue. Please let me know if anyone is interested to fix this too!
P.S: I am new to github and this is the very first OSS that I am contributing. If there are any mistakes, please forgive me.

**Comment by prabhakar267** [comment]
Same as #669
