### ISSUE TITLE
Unable to add a "my trip"

### ISSUE THREAD

**Issue by shubhamdamani** [project-travel-mate/Travel-Mate#719]
showing "integer out of range\n" in snackbar

**Comment by prabhakar267** [comment]
@shubhamdamani Can you describe the problem a little more?

**Comment by shubhamdamani** [comment]
![WhatsApp Image 2019-10-03 at 18 01 52](https://user-images.githubusercontent.com/43433565/66126883-151f2400-e608-11e9-9833-40850428774a.jpeg)
While adding a trip to my trip, this error is getting popped-up!

**Comment by Swati4star** [comment]
@shubhamdamani Do you want to work on this issue?

**Comment by shubhamdamani** [comment]
yes, i want to give a try

**Comment by aman0408** [comment]
I am giving it a try too.

**Comment by aman0408** [comment]
The issue is with the start date being sent. Is the requirement of the API a timestamp? I tried sending "1" instead of the actual timestamp and it got added.

**Comment by prabhakar267** [comment]
@aman0408 Can you raise a PR for the fix?

**Comment by aman0408** [comment]
Haven't fixed it yet. I tried sending a hardcoded value for which it worked. For an actual timestamp, the backend server is sending "integer out of range". So I need to know what exactly does the server require

**Comment by prabhakar267** [comment]
@aman0408 Can you send me the exact timestamp you're sending when it gives `integer out of range` error and also one when it doesn't

**Comment by aman0408** [comment]
"61528617000" gives the error. Sending "1" does not.

**Comment by aman0408** [comment]
You probably need to update the database to accept bigInteger. There's nothing wrong from the android side.

**Comment by prabhakar267** [comment]
@aman0408 I checked the server code, `61528617000` is failing because this is Epoch milliseconds, whereas the server expectes it to be Epoch seconds. 
@Swati4star can confirm if the milliseconds to seconds conversion needs to be added to server code or the Android code

**Comment by aman0408** [comment]
Okay. I'll do the needful changes if required.

**Comment by Swati4star** [comment]
yes @aman0408 
Do the changes in android code to send time as Epoch seconds. Thank you!

**Comment by aman0408** [comment]
The problem was not with seconds or milliseconds. It was because of using a deprecated Date class constructor. I have fixed it.

**Comment by Swati4star** [comment]
@aman0408 Great finding :)
If you see the use of these deprated classes at some other place also, feel free to create a PR for that too!

**Comment by aman0408** [comment]
> @aman0408 Great finding :)
> If you see the use of these deprated classes at some other place also, feel free to create a PR for that too!

Sure, I will do that!
