### ISSUE TITLE
Bug:Delhi weather forecast causes app crash

### ISSUE THREAD

**Issue by ambika1101** [project-travel-mate/Travel-Mate#730]

**Comment by aman0408** [comment]
This is not only for Delhi. It crashes for multiple cities.

**Comment by prabhakar267** [comment]
API seems to be giving correct output. 
@aman0408 Can you look into the reason?

**Comment by aman0408** [comment]
Yes I'm looking into it. API is giving the correct response. The drawable is null. I'm working on it.

**Comment by aman0408** [comment]
The issues is because of missing icons drawable xml in the app. There is only "wi_day_rain" present. No other icon is present.

**Comment by prabhakar267** [comment]
Recently a lot of files were deleted but they were supposed to be unused resources, can you verify if the files needed for weather were present in any of the following PRs?
https://github.com/project-travel-mate/Travel-Mate/pull/725
https://github.com/project-travel-mate/Travel-Mate/pull/718

**Comment by aman0408** [comment]
Yeah the required files are present in those PRs.

**Comment by Swati4star** [comment]
You can check the previous version of repo and download files from there. 
This is the repo version just before that PR: https://github.com/project-travel-mate/Travel-Mate/tree/b48ae53090242680803937d8e5c44fbfa91da6f9


I would recommend to add those drawables back, but also, even when the drawables are not there, app should not crash.

**Comment by vincent-paing** [comment]
> I would recommend to add those drawables back, but also, even when the drawables are not there, app should not crash.

I think we can do a conditional check and provide a drawable icon, any idea what default drawable should be?

**Comment by aman0408** [comment]
I have created a PR for the issue.
