### ISSUE TITLE
Weather forecast drawables shouldn't show up in "unused resources"

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#736]
A side effect of this issue:
https://github.com/project-travel-mate/Travel-Mate/pull/732#issuecomment-538771597

If we check for unused drawables in IDE, it shows all weather drawables, but they are required.

**Comment by DroidSU** [comment]
can you please explain a little more please?

**Comment by HeinKhantZaw** [comment]
I have fixed the problem @Swati4star
