### ISSUE TITLE
Improve world clock home page UI

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#737]
![wc](https://user-images.githubusercontent.com/9164477/66379877-fa67f900-e9d3-11e9-8844-9a6e3b018e71.jpeg)

Some suggestions:
- Move "select timezone" and the "asia/kolkata" dropdown to same line
- Reduce the size of "Select timezone"

More suggestions are welcome

**Comment by reynaldo22** [comment]
let me do this
assign me

**Comment by prabhakar267** [comment]
Sure @reynaldo22 , go ahead

**Comment by droid-it** [comment]
Is it open to be picked up? If yes, I would like to pitch in!

**Comment by Swati4star** [comment]
@reynaldo22 Updates?

@droid-it Please comment on one issue at a time and pick that up.

**Comment by mridul-arora** [comment]
Can I take this? If it's still open and if nobody is working on it still.

**Comment by RyanMarzec** [comment]
is anyone working on this? if not I can complete this

**Comment by Swati4star** [comment]
Sure @reynaldo22 Please create a PR.

**Comment by Swati4star** [comment]
@4rthurRousseau Can you please comment on issue next time before creating a PR?
