### ISSUE TITLE
Dismiss the loader in login/signup when there is some error

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#74]
1. Add some invalid credentials on the login page
2. There is a toast message displayed,  but the loader is still there.

Expected: The loader should be dismissed.

**Comment by brijeshshah13** [comment]
I'm working on it. Will send the PR shortly.

**Comment by Swati4star** [comment]
Fixed by 6f4738a9a16b670bd492af21a1827deb2af2fabc
Thanks to @brijeshshah13 👍
