### ISSUE TITLE
Modifications in "daily quotes" page UI

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#742]
![daily quotes](https://user-images.githubusercontent.com/9164477/66494092-bf012380-ead4-11e9-90b4-41aee707441d.jpg)

### Enhancements:
- Remove the app bar
- background is distorted. fix this.
- "Don't show again" should be a checkbox
- Activity shouldnt get dismissed on clicking "dont show again"
- Add an ok or continue button to dismiss activity
- any other enhancements are also welcome!

**Comment by mangelovic** [comment]
I might take a look at it

**Comment by prabhakar267** [comment]
@mangelovic Please either claim the issue and make sure you work on it or don't claim for other to pick 😄

**Comment by masrnam** [comment]
Can you also assign it to me? Thanks.

**Comment by Swati4star** [comment]
updates @masrnam ?

**Comment by masrnam** [comment]
I am working on it. I think, that it should be finished tomorrow or on Wednesday at the latest.

**Comment by Swati4star** [comment]
It looks good.
Just modify the continue button also. Make it smaller in size. Not all caps. change background to some orangish or blue color & text white color.

**Comment by Swati4star** [comment]
Looks good @masrnam

**Comment by Swati4star** [comment]
Please create a PR for this @masrnam 👍

**Comment by masrnam** [comment]
Ok. I am going to create PR tomorrow.
