### ISSUE TITLE
[BUG] Can't see city name when city has default image

### ISSUE THREAD

**Issue by AmrDeveloper** [project-travel-mate/Travel-Mate#748]
Can't see city in FindCityInfoActivity when slider showing the default image

**Bug screenshot**
![city name](https://user-images.githubusercontent.com/23631699/66708359-a9e3f900-ed4f-11e9-891c-a1946c9c05fb.PNG)

**Expected behavior**
See city name in any image color in the slider

**Suggestion**
Add TextView with good color for example colorPrimary to show city name

**Suggestion screenshot**
![fixed UI](https://user-images.githubusercontent.com/23631699/66708353-959ffc00-ed4f-11e9-9658-efbd7785330a.PNG)

Would you like to work on this issue?

Yes

**Comment by Swati4star** [comment]
My suggestion would be: to add black contrast to background image, like in the Utilities section. The cards have reduced transparency with black background. White text will look good in this case.
Reason: your suggestion won't look good when I fully scroll up the screen.

**Comment by nextybrown** [comment]
Hey Guys 
I don't think this is a gub put just FontColor issue, The city font color is just merging with the image color. We can change the image  or generate color according to the image

**Comment by HeinKhantZaw** [comment]
Can I fix this issue?

**Comment by HeinKhantZaw** [comment]
Can I fix this?

**Comment by AmrDeveloper** [comment]
@Swati4star You are right i will implement your suggestion

**Comment by AmrDeveloper** [comment]
@HeinKhantZaw Sorry bro i am working on it

**Comment by HeinKhantZaw** [comment]
Oh! Sry, I didn't see that you want to work on this issue.
