### ISSUE TITLE
[BUG] Clicking on home page recycler opens up the wrong item

### ISSUE THREAD

**Issue by DroidSU** [project-travel-mate/Travel-Mate#750]
**Describe the bug**
A clear and concise description of what the bug is:

On the main screen, clicking one the even recycler items opens its previous odd item.

**To Reproduce**
1. Go to Home Screen
2. Click on any recycler item on the right side.
4. The next activity opens with the data of the previous item.

**Expected behavior**
The next activity should open with the selected item's data.

*Additional context*
I didnt find any other opened issue, i was surprised nobody has found this out yet, pardon me if i have missed something. I can work on this issue if it is still valid.

**Comment by nextybrown** [comment]
Hey  DroidSU
I have tried do reproduce the error but, everything looks good so far if you can be more specific about the bug  that will be helpfull

**Comment by HeinKhantZaw** [comment]
![72742544_897260510656642_7907122280419819520_n](https://user-images.githubusercontent.com/40730345/66716761-94c2a500-edf7-11e9-9259-0699ce55a8bf.jpg)

I can reproduce the error @nextybrown  Did u choose the recycler item on the right side such as Bangalore , Chennai. If these items are clicked, the next activity shows the left side items - for example, if you select bangalore, the app shows the information about Delhi.

**Comment by nextybrown** [comment]
Ok, The error is in List of cities @HeinKhantZaw  not in the menu ... let me see what is wrong in the code

**Comment by AmrDeveloper** [comment]
Can i work on this issue?

**Comment by nextybrown** [comment]
@AmrDeveloper  I actually start working on it

**Comment by AmrDeveloper** [comment]
@nextybrown Sorry bro, good luck

**Comment by Swati4star** [comment]
@nextybrown Could you find the issue?
