### ISSUE TITLE
[BUG] Wrong snackbar message appears when creating a new account and submitting user credentials

### ISSUE THREAD

**Issue by svignesh93** [project-travel-mate/Travel-Mate#756]
**Describe the bug**
When creating a new account and while the internet was turned off and submitting user credentials shows a snack bar message "Invalid username or password"

**To Reproduce**
1. Turn Off the internet
2. Create a new Account from Login Screen. If logged in already, please sign out.
3. Enter user credentials and submit
4. A snack Bar message will appear

**Expected behavior**
"Could not create new Acc, There was no internet" message or similar one should be shown.

**Actual behavior**
"Invalid username or password" was shown

**Device Information (please complete the following information):**
 - Device: Nokia 6.1
 - OS: Android Pie

**Comment by Swati4star** [comment]
**Suggested Expected behaviour:**
`"We couldn't find an active internet connection. Please try again."`

**Comment by Swati4star** [comment]
Or, you can directly use ** check_internet** string in strings.xml file

**Comment by Irfan-S** [comment]
Hi , can I be assigned this issue?
