### ISSUE TITLE
Show default Status as a hint in ProfileActivity

### ISSUE THREAD

**Issue by AmrDeveloper** [project-travel-mate/Travel-Mate#761]
## Current State 
When user edit state in ProfileActivity for first time he need to delete all default status from EditText then start to write status

![before_commit](https://user-images.githubusercontent.com/23631699/67024603-fd19cb00-f104-11e9-80ba-006345654cb2.PNG)

## Suggestion 
Show default status in ProfileActivity as a hint so he can start write new status without delete default one

## Screenshot
![default_status](https://user-images.githubusercontent.com/23631699/67024359-93012600-f104-11e9-9367-09eb53dbec6a.PNG)

Would you like to work on this issue?
Yes

**Comment by prabhakar267** [comment]
@AmrDeveloper Do you want me to assign this to you?

**Comment by AmrDeveloper** [comment]
@prabhakar267 Yup i want to work on it
