### ISSUE TITLE
[BUG] Logging in to different devices at the same time with one account not possible

### ISSUE THREAD

**Issue by Lika-B** [project-travel-mate/Travel-Mate#764]
Describe the bug
I used the same account to log on to the tablet and the mobile phone at the same time. It does not work, once you are logged in with one device, the same account data will be displayed as incorrect on the other device.

1. Go to two devices at the same time to log in to the app. 
2. Sign in, after a successful login to one device, to the other device with the same account. 
3. After successful login to one device, simultaneous login to the other devices is not possible.

**Comment by prabhakar267** [comment]
@Lika-B  What does it show? Are you not getting the same data on both devices or are you able to login only to one of the devices?
If its the data issue, then what data is not showing the same?

**Comment by Swati4star** [comment]
@Lika-B Please provide the requested details of this issue?
