### ISSUE TITLE
Images on the github pages not displayed

### ISSUE THREAD

**Issue by pfieffer** [project-travel-mate/Travel-Mate#768]
### Images on the github pages is not displayed.
Fix the images not displayed on the [github pages](https://project-travel-mate.github.io/Travel-Mate/) for the project.

![image](https://user-images.githubusercontent.com/16465152/67183975-61d56e00-f402-11e9-888b-fc24957fc883.png)

### Would you like to work on the issue?
Yes

**Comment by prabhakar267** [comment]
@pfieffer We would need to change the relative image paths in README to absolute paths. That should fix the missing images.

**Comment by pfieffer** [comment]
I can work on that. @prabhakar267
