### ISSUE TITLE
Change toast to snackbar messages

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#77]
change all the toast messages in the app to snackbar messages.

**Comment by shiv07tiwari** [comment]
Can I start working on this issue under GSSoC ?

**Comment by knightcube** [comment]
@shiv07tiwari yes you can start working on this issue and yes there are Toast messages in the source code.

**Comment by Swati4star** [comment]
@shiv07tiwari These are the activities where we have toast messages : https://github.com/project-travel-mate/Travel-Mate/search?q=Toast&unscoped_q=Toast

..and are you working on this issue?

**Comment by shiv07tiwari** [comment]
Okay !
Working on it :)

**Comment by shiv07tiwari** [comment]
@Swati4star  Shouldn't we keep Toasts as is it inside the LocationService, as the snackbar needs a view to be displayed ?

**Comment by Swati4star** [comment]
You can leave the toasts that are inside location service.

**Comment by git-typecode** [comment]
Anyone working on this?

**Comment by Swati4star** [comment]
No. You can take this up 👍
