### ISSUE TITLE
Add unit tests for DateUtils class

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#787]
### Describe the chore
Add unit tests for DateUtils class: https://github.com/project-travel-mate/Travel-Mate/blob/master/Android/app/src/main/java/utils/DateUtils.java

Code coverage should be ~90%

**Comment by fokion** [comment]
I will pick it up if it is ok

**Comment by Swati4star** [comment]
Sure @fokion

**Comment by fokion** [comment]
#790
