### ISSUE TITLE
Build fails due to issue with Android Plugin for Gradle 3.1.2

### ISSUE THREAD

**Issue by brijeshshah13** [project-travel-mate/Travel-Mate#79]
**Actual Behaviour**

Building the latest `master` branch fails due to Known Issues with Android Plugin for Gradle 3.1.2.

**Expected Behaviour**

To prevent build from failing, we should downgrade to Android Plugin for Gradle 3.1.1 until a new version fixes it. (3.1.3 also doesn't fix it)

**Steps to reproduce it**

Pull the latest changes of the development branch and try to build the project.

**LogCat for the issue**

Error message: `Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.
`
    
**Would you like to work on the issue?**

Yes.

**Comment by Swati4star** [comment]
Fixed by #80
