### ISSUE TITLE
database

### ISSUE THREAD

**Issue by rahimakhan313** [project-travel-mate/Travel-Mate#793]
sir if i want to change the database. how can I do that? I can't find the database file

**Comment by prabhakar267** [comment]
The database and related interactions are in different repository. 
https://github.com/project-travel-mate/server

**Comment by rahimakhan313** [comment]
thank you sir!
but this is the django site and travel mate is the android app. so if i change the database in the given link , will my travel mate project updated automatically? or i have to change something in that code. 
also  which database you used for storing all information related to india like sqlite, mysql , firebase? 
    On Monday, November 18, 2019, 10:19:14 PM GMT+5, Prabhakar Gupta <notifications@github.com> wrote:  
 
 
The database and related interactions are in different repository.
https://github.com/project-travel-mate/server

**Comment by prabhakar267** [comment]
@rahimakhan313 If you want to make some change in the database, you would have to make a copy of complete server along and produce your own data; run the server. Then in Android studio, you would need to change the server credentials and start using your own local server.

If you want to point out any data incorrection on the app, please feel free to raise a new issue on the server repository, I will be more than happy to make the change for you :smile:

**Comment by rahimakhan313** [comment]
thanx for your help
    On Tuesday, November 19, 2019, 04:13:48 PM GMT+5, Prabhakar Gupta <notifications@github.com> wrote:  
 
 
@rahimakhan313 If you want to make some change in the database, you would have to make a copy of complete server along and produce your own data; run the server. Then in Android studio, you would need to change the server credentials and start using your own local server.

If you want to point out any data incorrection on the app, please feel free to raise a new issue on the server repository, I will be more than happy to make the change for you 😄

**Comment by rahimakhan313** [comment]
Hi!
sorry for disturbing you again sir, but i need your help earlier i told you that i want this app as my semester project and i have to change the data base for this purpose. i want to generate data for another country, but i can't find the database so plz help me find it so i will change the database. 
earlier  you also told me about server on django i have already done that but what about next?
i'm greatly thankful to you for this act of kindness.
regards:rahima khan    On Tuesday, November 19, 2019, 07:23:28 PM GMT+5, rahima khan <rahimakhan313@yahoo.com> wrote:  
 
  thanx for your help
    On Tuesday, November 19, 2019, 04:13:48 PM GMT+5, Prabhakar Gupta <notifications@github.com> wrote:  
 
 
@rahimakhan313 If you want to make some change in the database, you would have to make a copy of complete server along and produce your own data; run the server. Then in Android studio, you would need to change the server credentials and start using your own local server.

If you want to point out any data incorrection on the app, please feel free to raise a new issue on the server repository, I will be more than happy to make the change for you 😄
