### ISSUE TITLE
FlipViewPager has an issue with the number of pages. [BUG] 

### ISSUE THREAD

**Issue by lewisgarton** [project-travel-mate/Travel-Mate#803]
**Describe the bug**
On the "Most Popular Cities" page, the FlipViewPager has an issue with the number of pages.
When turning a page for an item in the left column (e.g Delhi) the pager works correctly: it will only allow you to turn the page once to see the options ("know more", "View weather info", "fun facts", "City Trends"), but when turning a page on the right (e.g Bangalore) it will allow you to turn the page 8 times showing the same information, when you wish to return you will need to turn the page back 8 times.

**To Reproduce**
1. Go to 'Most Popular Cities"
2. From the initial state, turn any page in the right column 8 times
3. Turn the page back 8 times to get back to the initial state
5. Do the same for any item in the left column 
6. See correct behavior 

**Expected behavior**
When turning a page in the right column it should only be able to turn once, as it does with the left column.

**Screenshots**
![image](https://user-images.githubusercontent.com/32315300/72322831-2fd75d80-370c-11ea-9353-e9119bb0ef0a.png)

**Device Information (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: Android 9
 - App Version: 5.6.1

**Comment by lewisgarton** [comment]
Can i please work on this?

**Comment by prabhakar267** [comment]
@lewisgarton Sure go ahead
