### ISSUE TITLE
Signup activity does not inform user email address is invalid during signup [BUG]

### ISSUE THREAD

**Issue by lewisgarton** [project-travel-mate/Travel-Mate#805]
**Describe the bug**
The signup activity does not notify the user there is an issue with the email address provided during signup.
Input field should check if valid and prompt user the same as it does when mismatching passwords are entered.

**To Reproduce**
1. Open application
2. Sign up with details
3. Enter an email address with an incorrect format
4. Click signup
5. See error

**Expected behavior**
Email address field should be parsed and provide feedback that the email address is invalid when they click signup

**Screenshots**
![Screenshot_20200115-102620_Travel Mate](https://user-images.githubusercontent.com/32315300/72393023-72de1300-3796-11ea-9f70-871f97c2329b.jpg)

**Device Information (please complete the following information):**
 - Device: Samsung Galaxy s10+
 - OS: Android 9
 - App Version: 5.6.2

**Comment by lewisgarton** [comment]
Can i please work on this issue?

**Comment by Swati4star** [comment]
Sure @lewisgarton

**Comment by prabhakar267** [comment]
@lewisgarton Sure go ahead.
