### ISSUE TITLE
Cant able to change the popular city names and their info!

### ISSUE THREAD

**Issue by Amrit27k** [project-travel-mate/Travel-Mate#808]
I was actually making some changes in the popular cities layout but i am not been able to find the database and layout for mumbai and other cities.Can you suggest me how to do that?

### Would you like to work on the issue?
Tell us if you would like to work on this issue.

**Comment by prabhakar267** [comment]
The database is not publically available. If you find any discrepancy with the data please make an issue on the [server repository](https://github.com/project-travel-mate/server), I would be happy to verify and correct the database.
Thanks
