### ISSUE TITLE
Contribution request from Business Administration students

### ISSUE THREAD

**Issue by SedaCTN** [project-travel-mate/Travel-Mate#809]
Dear contributors of Travel-Mate,

Together with a group of 3 students we are working on a project for our studies. We would like to contribute to Travel-Mate in a way that fits your needs, that does not involve coding.

We can do one of the following contributions:
- Test the app and give feedback from our point of view (or i.e. 65+)
- Make a small survey about the app and distribute it amongst our peers at the university.
- Anything else that fits your needs.

We would like to interview some of your contributors for some background information on the project.

If some of you could help us out we would really appreciate this. We would like a quick response since we have to move on with our project.

Thank you in advance,

Seda and team mates.

**Comment by lewisgarton** [comment]
@Swati4star user feedback would be a great opportunity to improve the application?

**Comment by prabhakar267** [comment]
@SedaCTN you can contribute to the project any way you feel comfortable. If you want to discuss a non-technical contribution please email us at projecttravelmate.github.io@gmail.com. 
For technical contributions please feel free to open an issue explaining the exact issue and possibly a Pull Request for the same. Additionally you can pick something from existing list of issues on each repository. 
Closing this and hoping for an active contribution 😄
