### ISSUE TITLE
Unable to add checklist items to empty checklist [BUG] 

### ISSUE THREAD

**Issue by lewisgarton** [project-travel-mate/Travel-Mate#810]
Relates to the Checklist utility
You cannot add new items to the checklist if all are checked off as editText is no longer visible

Steps to reproduce the behaviour:
1. Go to Utilities->Checklist
2. Check all items
3. See error

Expected behaviour
It should be possible to add items to the checklist.

![Screenshot_20200227-214013_Travel Mate](https://user-images.githubusercontent.com/32315300/75427107-c2754880-59aa-11ea-9693-87a95654d33f.jpg)
![Screenshot_20200227-214038_Travel Mate](https://user-images.githubusercontent.com/32315300/75427115-c43f0c00-59aa-11ea-9c60-25c66ce02e56.jpg)

Device Information
 - Device: Samsung Galaxy S10+
 - OS: Android 10
 - App Version: 5.6.1

**Comment by Swati4star** [comment]
Are you interested in working on this issue?

**Comment by lewisgarton** [comment]
Yeah sure

**Comment by lewisgarton** [comment]
@Swati4star good to go?
