### ISSUE TITLE
Other language wikipedia and fetching (city) data...

### ISSUE THREAD

**Issue by alfje2000** [project-travel-mate/Travel-Mate#813]
I changed the server site /modules/api/city/views.py

This api call
wiki_api_url = "https://en.wikipedia.org/w/api.php" +
"?action=query&prop=extracts&explaintext&titles=" +
city.city_name +
"&format=json"

into

wiki_api_url = "https://nl.wikipedia.org/w/api.php" +
"?action=query&prop=extracts&explaintext&titles=" +
city.city_name +
"&format=json"

After that nothing is shown and fetched from this site in the app when i click 'know more about ...' a city.

Is this thing causing by the server or app and how do i solve this?

**Comment by Swati4star** [comment]
This isn't being caused by due to travel mate server. This server is no involved in invoking this particular API.

Please check the json structure being returned in both the APIs. Is there issue with json parsing? or we don't even have any results for this city in other language?

**Comment by alfje2000** [comment]
@Swati4star ....ok, it must be an issue withe the json parsing. The API call for this citie(s) work when i check them in a browser. All content in json format returns. I only change the https://**en**.wikipedia.org/w/api.php"  into  the dutch https://**nl**.wikipedia.org/w/api.php"  and there is no parsing....

**Comment by Swati4star** [comment]
As this just some language functionality you are adding, you need to debug through the code to check where it is failing. 
Or you have to share, what exact API (I mean full - with parameters replaced) are you calling, whats its response? What is the error? then I'll be able to help.

**Comment by alfje2000** [comment]
@Swati4star : You mean this ?

**https://en.wikipedia.org/w/api.php?action=query&prop=extracts&explaintext&titles=almelo&format=json**

returns

{"batchcomplete":"","warnings":{"extracts":{"*":"\"exlimit\" was too large for a whole article extracts request, lowered to 1."}},"query":{"normalized":[{"from":"almelo","to":"Almelo"}],"pages":{"118451":{"pageid":118451,"ns":0,"title":"Almelo","extract":"Almelo (Dutch pronunciation: [\u02c8\u0251lm\u0259lo\u02d0] (listen)) is a municipality and a city in the eastern Netherlands. The main population centres in the town are Aadorp, Almelo, Mariaparochie, and Bornerbroek.\nAlmelo has about 72,000 inhabitants in the middle of the rolling countryside of Twente, with the industrial centres of Enschede and Hengelo as close neighbours but also with tourist towns like Ootmarsum, Delden and Markelo only a bicycle ride away. Almelo received city rights in 1394.  Within the city limits lies the castle of the Counts of Almelo.\nLocated in the city centre is Huize Almelo, a castle that in its current form dates back to 1662 (This castle is not open to the public). There are mosaics which decorate the walls of the tunnel close to the railway station.\nThe city is also known for its local association football club Heracles Almelo, which plays in the Eredivisie, the highest football league in the Netherlands. The club uses the Polman Stadion.\n\n\n== History ==\nAt the end of the 19th century textile emerged as a major employer and drew many workers to Almelo, at first from within the Netherlands. Since the 1960s workers from Spain and Turkey came to Almelo. The first mosque of the Netherlands was built in Almelo in 1976 for the Turkish population of the city. Almelo also has a sizeable number of Armenians.\nIn the 1970s the industry dwindled and most factories were relocated to countries with cheaper labour. Some factories remain in the city centre and are now in use for apartments or offices.\n\n\n=== Topography ===\n\nTopographic map of Almelo, Sept. 2014\n\n\n== Economy ==\nCurrently, a major employer in Almelo is Urenco Nederland. This is a uranium enrichment plant which uses the gas centrifuge method and produces uranium with about five percent U-235, for nuclear reactors. A bakery factory, Bolletje, Malvern Panalytical, the Stichting Ziekenhuisgroep Twente (a hospital) and the regional court are also major employers.\n\n\n== Transport ==\n\nAlmelo has 2 railway stations:\n\nAlmelo railway station\nAlmelo de Riet railway stationThe main station is Almelo and offers links to Hengelo, Enschede, Amersfoort, Amsterdam Airport Schiphol, Utrecht, Gouda, Rotterdam, The Hague and Zwolle. There is also a train every 2 hours into Germany serving cities such as Osnabr\u00fcck, Hannover and Berlin.\n\n\n== Sport ==\n\n\n=== Football ===\nHeracles Almelo, a professional football club playing in the Eredivisie is based in Almelo.\n\n\n=== Cycling ===\nSince 1983 Almelo has organised the Profronde van Almelo, an elite men's and women's professional road bicycle racing event.\n\n\n== Notable people ==\n\nCatharina Julia Roeters van Lennep (1813\u20131883) a Dutch artist\nIzaak Kolthoff (1894\u20131993) an analytical chemist and chemistry educator\nJudith Ledeboer OBE (1901\u20131990) architect\nEvert Willem Beth (1908-1964) philosopher and logician\nGerritdina Benders-Letteboer (1909\u20131980) an active member of the Dutch Resistance\nWubbo Ockels (1946-2014) a physicist and astronaut of the European Space Agency\nHerman Finkers (born 1954) comedian, known for his friendly, dry-witted humour\nTom Egbers (born 1957) a Dutch English journalist, writer and TV presenter \nLiesbeth van Tongeren (born 1958) a Dutch politician, Director of Greenpeace Netherlands 2003\u20132010, grew up in Almelo\nHero Brinkman (born 1964) a police officer and former Dutch politician\nJos de Blok, Dutch Wiki (born 1960) founder and CEO of Buurtzorg\nMichiel Veenstra (born 1976) Radio-dj on KINK\nIlse de Lange (born 1977) a Dutch country and pop rock singer-songwriter\nLoes Haverkort (born 1981) a Dutch movie, TV and theater actress \nAzra Ak\u0131n (born 1981) Miss Turkey World 2002 and Miss World 2002 \n\n\n=== Sport ===\nKea Bouman (1903 \u2013 1998) female tennis player; only Dutch female tennis player to win a Grand Slam singles tournament\nLex Mullink (born 1944) a retired rower, bronze medallist at the 1964 Summer Olympics\nHendrie Kr\u00fczen (born 1964) football midfielder, over 500 club caps\nBrian van Loo (born 1975) retired soccer goalkeeper, 261 club caps\nMarnix Smit (born 1975) retired soccer player, 231 club caps with Heracles Almelo\nArnold Bruggink (born 1977) retired soccer player, 447 club caps\nMark Looms (born 1981) soccer player, 329 club caps\nKirsten Wild (born 1982) track and road race cyclist; multiple National Champion\nMarc H\u00f6cher (born 1984) a Dutch football player with over 350 club caps\nDennis Kuipers (born 1985) a Dutch rally driver\nAnouk Dekker (born 1986) a Dutch footballer with over 250 club caps\nFabian Roosenbrand (born 1988) a Dutch professional darts player\nMaret Balkestein-Grothues (born 1988) a Dutch volleyball player\nMaud Roetgering (born 1992) a football defender 184 caps with FC Twente Vrouwen\n\n\n== International relations ==\n\n\n=== Twin towns \u2014 Sister cities ===\nAlmelo is twinned with:\n\n\n== See also ==\nAmbt Almelo\n\n\n== Gallery ==\n\n\t\t\n\t\t\n\t\t\n\t\t\n\n\n== References ==\n\n\n== External links ==\n Media related to Almelo at Wikimedia Commons\nOfficial website"}}}}

and
**https://nl.wikipedia.org/w/api.php?action=query&prop=extracts&explaintext&titles=almelo&format=json**

returns

{"batchcomplete":"","warnings":{"extracts":{"*":"\"exlimit\" was too large for a whole article extracts request, lowered to 1."}},"query":{"normalized":[{"from":"almelo","to":"Almelo"}],"pages":{"10414":{"pageid":10414,"ns":0,"title":"Almelo","extract":"Almelo ( uitspraak (info / uitleg)) is een stad en gemeente in de regio Twente in de Nederlandse provincie Overijssel. De gemeente Almelo beslaat een oppervlakte van 69 km\u00b2 en telt 72.849 inwoners.\nDe gemeente Almelo is ontstaan uit een fusie (1914) tussen de gemeenten Ambt Almelo en Stad Almelo. Behalve de stad Almelo omvat de gemeente de kernen Aadorp, Bornerbroek en Mariaparochie (gedeeltelijk). De gemeente Almelo maakt deel uit van de Regio Twente. Een deel van de Almelo\u00ebrs spreekt Twents, een Nedersaksisch dialect.\n\n\n== Geschiedenis en architectuur ==\nAlmelo ontstond in de middeleeuwen. De naam gaat terug op de Germaanse woorden alma \"olm\" en lauha \"lo\". Een lo is een bos dat gelegen is op zandgrond en vaak vlak bij een nederzetting ligt.\n\nOp de hierboven genoemde kruising van de Almelose Aa en die landweg stond het voor het eerst in 1236 genoemde en nog steeds bestaande Huis Almelo. Uit oude documenten blijkt dat de nederzetting in ieder geval in 1420 al stadsrechten had. De stad had een gracht, maar geen muur, en is dan ook nooit van militair belang geweest. Huis Almelo bestaat waarschijnlijk al sinds de 12e eeuw en is tot op de dag van vandaag in handen van de familie Van Rechteren Limpurg. De familie had eeuwen verschillende rechten in de stad Almelo, waaronder dat om recht te spreken. Tegenwoordig houdt de graaf zich bezig met restauratie van oude panden in de binnenstad en het onderhouden van bossen die eigendom van de familie zijn.\nTussen 1818 en 1914 was de gemeente Almelo opgesplitst in de gemeenten Stad Almelo en Ambt Almelo.\n\nIn de 17e en 18e eeuw kwam de huisweverij steeds meer op. De entree in Almelo van de eerste stoommachine, in 1830, veroorzaakte een overgang naar fabrieksmatige productie. De textielindustrie werd ook bevorderd door de aanleg van het Overijssels Kanaal (in 1855) en de spoorlijn van Almelo naar Salzbergen, in 1865. Rond 1900 waren er dan ook vele zeer rijke families in Almelo en uit die tijd dateren veel landhuizen en villa's in diverse stijlen zoals Jugendstil, expressionisme en neorenaissance.\nVanaf de jaren 1960 kreeg de Almelose textielindustrie het door de goedkopere buitenlandse concurrentie erg moeilijk, wat tot massale bedrijfssluitingen leidde. Vandaag de dag zijn de effecten hiervan nog zichtbaar in de werkloosheidscijfers. Veel textielfabrieken zijn afgebroken, maar sommige gebouwen zijn behouden gebleven.\nVan de villa's die textielbaronnen lieten bouwen is Bellinckhof aan de Wierdensestraat volgens velen de mooiste. Gebouwd door de familie Ten Cate in de jaren 20 van de 20e eeuw is het eveneens een van de grootste textielhuizen in Twente. Het huis en park zijn niet toegankelijk voor publiek. Het ontwerp is van architect Karel Muller. De eetkamer is betimmerd met mahoniehout, de hal heeft een zwartgeaderde witte marmeren vloer en de zaal is van groene betimmering voorzien met roze zijde en behangen met familieportretten van de Ten Cates. De huidige familietelg is, net als de graaf, actief in stadsbehoud en helpt naast zijn eigen park het Egbert ten Cateplantsoen en het Beeklustpark in Almelo onderhouden.\nNadat in 1664 de in het Huis Almelo wonende toenmalige heer van Almelo, Zeger van Rechteren (1623-1674), het uitoefenen van de katholieke godsdienst verbood vertrokken de nonnen van het Almelose Sint Catharinaklooster in 1665 en vestigden zich 300 meter over de grens met Duitsland iets ten zuidwesten van het Nederlandse Glane in een klooster dat zij de naam Maria Vlucht gaven. Na de opheffing van het klooster werden de, voor een deel uit Almelo afkomstige kerkschatten verspreid over de regio.Op 15 november 1944 werd door acht verzetsmensen een overval gepleegd op De Nederlandsche Bank aan de Wierdensestraat. De buit bedroeg 46,1 miljoen gulden, de hoogste buit ooit tijdens een overval in Nederland. Deze bankroof werd nagespeeld in de stadsmusicals Van Katoen & Nu en Het verzet kraakt. De straatnamen in de Almelose wijk Sluitersveld zijn vernoemd naar verscheidene verzetsmensen.\n\n\n== Geografie ==\n\n\n=== Wijkindeling ===\nDe stad Almelo is verdeeld in twaalf wijken en kernen.\nAadorp\nBornerbroek\nBinnenstad\nDe Riet\nHaghoek\nHofkamp\nNieuwstraat-Kwartier\nNoorderkwartier\nOssenkoppelerhoek\nSchelfhorst\nSluitersveld\nWierdensehoek (Kerkelanden/Aalderinkshoek)\nWindmolenbroek\n\n\n=== Straten ===\nLijst van straten in Almelo\n\n\n== Cultuur ==\n\n\n=== Bezienswaardigheden ===\nHet koor van de protestantse Grote Kerk stamt uit de 15e eeuw, het schip dateert uit 1733. Reeds in 1236 is sprake van een burchtkapel in Almelo dat toen onder de parochie Ootmarsum viel. De torenspits werd in de 18e eeuw geplaatst door gravin Sophia Juliana von Castell R\u00fcdenhausen. Boven de ingang van de toren bevindt zich een Latijnse inscriptie uit het jaar 1738. Lang hebben voor de toegangsweg naar de kerk twee van Bentheimer zandsteen gemaakte pilaren gestaan met de wapenschilden van Van Rechteren Limpurg en Almelo. Deze zijn in 1884 verplaatst naar de oprijlaan van het kasteel. Deze oprijlaan, de Gravenallee, is drie kilometer lang en eindigt bij het Kanaal Almelo-Nordhorn. Halverwege is een tolhuis en kan een rondwandeling gemaakt worden door de bossen, waarin zich ook de grafkelder van Van Rechteren Limpurg bevindt.\n\nDe rooms-katholieke Georgiuskerk werd gebouwd in het begin van de 20e eeuw (1900-1902) in neogotische stijl en is de eerste kerk die werd ontworpen door Wolter te Riele. De kerk is 3 november 2009 verheven tot basiliek. In de volksmond wordt de kerk \"de Sjors\" genoemd.\nAchter de Georgiuskerk ligt de oudste sociale woningbouw-wijk van Almelo: de Westeres, grotendeels in de Eerste Wereldoorlog gebouwd in opdracht van woningbouwvereniging Volksbelang, later overgenomen door woningstichting Sint Joseph, die in 2008 plannen presenteerde om de wijk af te breken en te vervangen voor eigentijdse bouw, met meer parkeerruimte en hogere huurprijzen. Sinds eind 2009 zijn deze plannen van tafel, mede vanwege de economische recessie en dankzij protesten uit de wijk en heel Almelo.\nHet pittoreske wijkje onderscheidt zich door zijn smalle straatjes en in rood baksteen, met geel bakstenen versieringen uitgevoerde huizen.\nDe straten zijn opgebouwd uit een steeds veranderende combinatie van een aantal woningtypen, waarbij sommige woningtypes maar 1 keer voorkomen.\nVerder is er het vanaf 1914 gebouwde tuindorp De Riet. Deze wijk is voor het merendeel tussen de twee wereldoorlogen gebouwd en bestaat uit goed onderhouden, kleine huisjes die in een zeer kenmerkende bouwstijl zijn gebouwd. Een deel is in handen van de twee woningbouwstichtingen. De wijk heeft sinds 3 oktober 1926 een eigen treinstation.\nDe stad kent nog een complete molen, de korenmolen De Hoop uit 1870.\nNabij het vroegere bleekveld en de voormalige Bleekweg (nabij de Aa) ligt stadskerk De Bleek, een kruiskerk met zadeldak. Dit gemeentelijk monument werd in 1927 voltooid naar een ontwerp van architect H.H. Krabshuis en werd bekostigd door de vrijzinnige protestanten in Almelo (Vereniging van Vrijzinnig Godsdienstigen). De kerkzaal heeft bijzondere glas-in-loodramen die - net als de rest van de kerkzaal - in late art-decostijl zijn.\n\n\n=== Monumenten ===\nIn de gemeente zijn er een aantal rijksmonumenten en oorlogsmonumenten, zie:\n\nLijst van rijksmonumenten in Almelo (gemeente)\nLijst van rijksmonumenten in Almelo (stad)\nLijst van oorlogsmonumenten in Almelo\nLijst van gemeentelijke monumenten in Almelo\nGenocidemonument\n\n\n=== Musea ===\nHet Stadsmuseum Almelo laat een beeld zien van de geschiedenis van Almelo. Het is gevestigd in het Rectorshuis, een monumentaal pand in het centrum. Vlak bij de Grote Kerk staat het eveneens monumentale Wevershuisje. Hier is onder meer een expositie te vinden over weven en vinden demonstraties plaats van oude ambachten als spinnen en kantklossen. Boven de geschenkwinkel van Bolletje aan de Grotestraat is Bakkerijmuseum De Meelzolder gevestigd. De toegang tot het Wevershuisje en het Bakkerijmuseum is gratis.\nHet Huis van Katoen & Nu is gevestigd in de binnenstad van Almelo en is ontstaan na de opvoering van de musical Van Katoen & Nu. Van Katoen & Nu werd in september 2014 als stadsmusical opgevoerd en ging over de opkomst en teloorgang van de textielindustrie in Twente in honderd jaar. De uitvoering was ter ere van het 100-jarig bestaan van de stad Almelo, waar de ontwikkelingen rond deze industrie, zoals ook merkbaar in andere textielsteden in Nederland, veel invloed hebben gehad. Het museum is een culturele hotspot en broedplaats voor nieuwe activiteiten in Almelo. Net als bij de musical worden zaken en mensen hier met elkaar verbonden. Een decor uit een cabaretprogramma van Herman Finkers is er te bewonderen, naast foto's van bekende Almelo\u00ebrs, historische foto's en informatie over de geschiedenis van voetbalclub Heracles.\nAan de Herengracht staan twaalf monumentale huizen die in 1889 zijn gebouwd in opdracht van Graaf van Rechteren Limpurg voor het personeel van het nabijgelegen Huis Almelo. Tegenwoordig zijn ze in gebruik als ateliers voor kunstenaars waar bezoekers iedere laatste zondag van de maand kunnen kijken naar de exposities van de verschillende Almelose kunstenaars.\nIn Kunsthal Hof 88 organiseert de stichting Indigo professionele tentoonstellingen van hedendaagse beeldende kunst. Jaarlijks worden in het museum 6 grote tentoonstellingen georganiseerd, met werk van landelijke, internationale en regionale kunstenaars. Behalve schilderijen, sculpturen, keramiek en sieraden, worden er ook fotografie, video, objecten en installaties tentoongesteld. Ook wordt er jaarlijks de Herman Krikhaarprijs uitgereikt. Deze award is een ode aan de Almelose kunstenaar Herman Krikhaar. De winnaar van de prijs wordt door een vakjury aangewezen. In 2018 bestond de Herman Krikhaarprijs tien jaar.\n\n\n=== Uitgaansleven en culturele centra ===\nCulturele aangelegenheden in Almelo zijn onder meer het Theaterhotel, het Preston Palace (hotel en vermaak in het voormalige Ireneziekenhuis) en het oude, voormalige Sint-Elisabethziekenhuis dat grotendeels dienstdoet als huisvesting van de Almelose vestiging van Kaliber Kunstenschool en Theater Hof 88. Theater Hof 88 heeft een uitgebreide eigen programmering van theatervoorstellingen en theaterconcerten in vrijwel alle genres in de Herman Finkers Zaal. Verder worden klassieke concerten door de Stichting Kamermuziek Almelo verzorgd en films door de stichting Filmhuis Almelo getoond. Ook biedt Theater Hof 88 onderdak aan een groot aantal Almelose amateurkunst-gezelschappen voor hun uitvoeringen en de wekelijkse repetities. Daarnaast vindt in Almelo sinds 2006 in juli het gratis toegankelijke HobNob festival plaats. Sinds de herfst 2004 is de bioscoop aan de Grotestraat gesloten, de nieuwe bioscoop aan het Amaliaplein is in het najaar van 2008 opgeleverd en wordt gerund door Movie Unlimited. Aan het Amaliaplein zit ook een veelvoud aan restaurants, caf\u00e9s en terrasjes.\n\n\n=== Sport ===\nMet meer dan 70 sportverenigingen actief in Almelo zijn er wekelijks vele sporters en vrijwilligers actief op en rondom het sportveld. Grote sportverenigingen en takken van sport zijn PH en Oranje Nassau (beide voetbal), MHC Almelo (hockey) en de F.A.G. (Federatie Almelose Gymnastiekverenigingen). Almelo kent diverse sportaccommocaties, waarvan de IISPA de bekendste is. Daarnaast kent Almelo een overdekt en openluchtzwembad, meerdere sporthallen, gymlokalen en buitensportvelden. Op termijn zijn alle gemeentelijke accommodaties in het beheer van Sportbedrijf Almelo.\nNaast de amateursport kent Almelo ook diverse topsport- en talentorganisaties, waarvan de voetbalclub Heracles Almelo de bekendste is. De club werd tweemaal landskampioen. Sinds de promotie in 2005 komt Heracles uit in de Eredivisie, het hoogste niveau in Nederland. Sinds 2010 trainen ook de topturnsters en talenten van Bosan/TON (Topturnen Oost-Nederland) in Almelo. Zij presteren (inter)nationaal op het hoogste niveau van het damesturnen. In 2012 ontving Almelo ook Eurosped TVT (Topvolleybal in Twente), afkomstig uit Oldenzaal als het voormalige Pollux, die dagelijks trainen en wekelijks spelen op het niveau van de DELA Eredivisie. Daarnaast zijn er regionale talentcentra van de NBB, Nevobo en NHV in Almelo georganiseerd.\nNaast topsportorganisaties kent Almelo ook meerdere topsportevenementen als Topvolleybal Almelo (voormalig Ermasport Volleybal Classic), de Profronde van Almelo en de Almelose Ruiterdagen. Daarnaast vinden er jaarlijks internationale wedstrijden plaatsen in de topsporthal van de IISPA.\n\n\n== Gezondheidszorg ==\nDe ZGT Almelo (het vroegere Twenteborg), onderdeel van de Ziekenhuis Groep Twente, is een algemeen ziekenhuis met 634 bedden officieel (425 in praktijk). Er werken ruim 1800 medewerkers en bijna 105 specialisten.\n\n\n== Economie ==\n\n\n=== Bedrijven ===\nAlmelo heeft een Arrondissementsrechtbank en een Huis van bewaring. Bolletje, met name bekend van zijn beschuiten, vindt zijn oorsprong in de stad. VDL, PANalytical en Urenco, dat verrijkt uranium voor kerncentrales produceert, zijn belangrijke werkgevers. De textiel, de oorsprong van de industrie in Almelo (en Twente) raakt meer en meer op de achtergrond, hoewel Koninklijke Ten Cate nog steeds een vestiging in Almelo heeft op het Indi\u00ebterrein. Ook de internationale schoenen- en kledingfabrikant Timberland is gevestigd in Almelo met een distributiecentrum op het XL Businesspark.\n\n\n=== Kantoren, industrie- en bedrijventerreinen ===\nAlmelo heeft veel bedrijvigheid, gesitueerd in de oude stad en ook op later geplande terreinen. Bedrijvigheid vindt men in de Bornsestraat, de Buitenhaven, het Dollegoor, het Wendelgoor, Noordbroek, de Turfkade en op de terreinen Twentepoort en het Bedrijvenpark Twente. In juli 2011 werd bekend dat de haven sinds 2008 een stabiele groei heeft. In de industriehaven worden zo'n 904.996 ton goederen gelost, ofwel zo'n 80.000 vrachtwagens. Ten zuiden van de stad is een nieuw bedrijventerrein gepland onder de naam XL Businesspark dat voor de gehele regio bedoeld is en een eigen aansluiting op de A35 heeft. Het ligt tussen Almelo, Bornerbroek en het Twentekanaal. Het gaat daarbij om bedrijven in de logistiek, transport, distributie en industrie. Nadat na veel protesten van omwonenden de aanleg was vertraagd heeft in 2007 de Raad van State alle bezwaren van de hand gewezen zodat de bouw een aanvang kon nemen. Er komen mogelijk drie windmolens op het bedrijventerrein.\n\n\n== Infrastructuur ==\n\n\n=== Autowegen ===\nVanuit de richting Deventer en Oldenzaal is Almelo over de snelweg te bereiken via de A1. Vanuit de richtingen Deventer en Hengelo is Almelo ook over de snelweg te bereiken via de A35. Deze snelweg loopt ten zuiden van Almelo en geeft via de N35 ook een verbinding met Zwolle. De autoweg N36 geeft voor Almelo een verbinding richting de provincie Drenthe. Almelo beschikt over een eigen ringweg rondom het centraal gelegen deel van de stad: de Ring Almelo.\n\n\n=== Spoorwegen ===\nSinds 18 oktober 1865 heeft Almelo een station aan het beginpunt van de toenmalige spoorlijn Almelo - Salzbergen, aangelegd door de Spoorwegmaatschappij Almelo-Salzbergen (AS). Op 1 januari 1881 werd door de Staatsspoorwegen de enkelsporige spoorlijn Zwolle - Almelo geopend. Per 1 september 1888 bracht de Koninklijke Nederlandsche Locaalspoorweg-Maatschappij een enkelsporige verbinding met Deventer tot stand, tot Wierden op een gemeenschappelijk baanlichaam met Zwolle-Almelo. Hiermee was de verbinding met Amsterdam een feit. Ten slotte nam de NOLS op 1 oktober 1906 de spoorlijn Mari\u00ebnberg - Almelo in dienst.\nNaast het hoofdstation heeft Almelo een halte (Station Almelo de Riet) aan de spoorlijn richting Hengelo-Enschede en verder beschikken de industrieterreinen Dollegoor en Bedrijvenpark Twente over spooraansluitingen.\nHet dubbelspoor tussen station Almelo en Almelo de Riet is verdiept aangelegd. Dit project, genaamd Almelo Verdiept, is in 2009 afgerond.\n\n\n=== Waterwegen ===\nRond en door Almelo lopen meerdere beken, rivieren en kanalen, waaronder het Twentekanaal, het Overijssels Kanaal, het kanaal Almelo-Nordhorn, de Almelose Aa en de Loolee.\n\n\n=== Fietssnelweg ===\nIn 2009 is een eerste deel van F35 (fietssnelweg) gerealiseerd. Deze fietssnelweg doorkruist Twente van de Duitse grens tot aan de Sallandse Heuvelrug bij Nijverdal via Enschede, Hengelo, Borne, Almelo en Wierden. De verbeteringen voor de fietser zijn te vinden in het verkorten van de reistijd en het comfort. Vanaf november 2019 is er ook een verbinding met Vriezenveen.\n\n\n== Godsdienst ==\nDe Protestantse Gemeente Almelo bestaat uit 5 autonome wijkgemeenten: de Bleekkerk, de Grote Kerk (Almelo), de Ontmoeting, Noach en Pni\u00ebl.\nOok heeft Almelo drie Rooms-Katholieke kerken. De Sint-Georgiusbasiliek (Almelo) aan de Boddenstraat in het centrum en de Sint-Jozefkerk (Almelo) in de wijk Sluitersveld vormen samen de St.-Jorisparochie. De Elisakerk (Elisaparochie) bevindt zich in Almelo Zuid. Binnen de gemeentegrens van Almelo heeft Bornerbroek de St.-Stephanuskerk (Marcellinusparochie) en in Mariaparochie staat de Onze-Lieve-Vrouw van Altijddurende Bijstand (Pancratiusparochie).\nIn Almelo woonden anno januari 2008 nog zo'n twintig belijdende joden. Naast het protestants-christelijke centrum De Schouw aan het Kerkplein staat sinds november 1980 de Aron de Haas Synagoge waar zij hun samenkomsten hielden. Al in 1803 was er in Almelo een synagoge in gebruik. Deze lag toen in de Bodden. Door groei werd in 1846 uitgeweken naar het Schalderoi. Het gebouw kwam ongeschonden door de Tweede Wereldoorlog. In 1980 werd het interieur van de synagoge overgeplaatst naar het Kerkpleingebouw. In augustus 2011 werd bekend dat de synagoge wordt teruggekocht door de gemeente. De nu nog tien belijdende joden zijn dan aangewezen op de synagoge in Enschede.\nAlmelo kent een baptistengemeente, \"de Bron\". Deze gemeente is ontstaan uit een fusie in 1996 tussen de voormalige gemeente \"Bethel\" aan de Nieuwstraat en de grotere gemeente aan de Geraniumstraat. Na de eenwording zijn zij eerst samen verdergegaan in het kerkgebouw aan de Geraniumstraat. Begin 1999 is het voormalige FNV-gebouw gekocht aan de Adriaen Brouwerstraat. Deze is na een grondige renovatie in gebruik genomen in november 1999. Een deel van het pand is afgebroken en daar is de nieuwe kerkzaal op gebouwd die in de loop van het jaar 2000 in gebruik is genomen.\nOok telt Almelo enkele duizenden leden van de Armeens-Apostolische Kerk, waarvan het kerkgebouw aan de Vriezenveenseweg staat.\nDe islamitische gemeenschap gebruikt een moskee die de eerste was in Nederland (in 1974), en de eerste moskee met minaret en kubbe.\n\n\n== Politiek ==\n\n\n=== College van B en W ===\nHet college van burgemeester en wethouders bestaat naast de burgemeester van Almelo, Arjen Gerritsen (VVD), uit de fracties van VVD, CDA, LAS en CU en kent de volgende 4 wethouders:\nArjen Maathuis (VVD): Sociale Zaken, Werkgelegenheid en economie, Economische betrekkingen, MBO-onderwijs, Recreatie en toerisme, Markt en haven, Sport, Mobiliteit.\nEug\u00e8ne van Mierlo (CDA): WMO en preventie (inclusief sociale wijkteams), Publieke gezondheid, Welzijn en dierenwelzijn, Milieu en afval, Energietransitie,\nWater en riolering, Omgevingswet.\nJan Martin van Rees (LAS): Binnenstadsontwikkeling, Kunst en cultuur, Middenstand, Ruimtelijke ordening, Wonen en volkshuisvesting, Stadsbeheer, beheer openbare ruimte, Plattelandsontwikkeling.\nAlex Langius (ChristenUnie): Jeugdzorg en preventie, Onderwijs (met uitzondering van MBO), Financi\u00ebn, Bedrijfsvoering, Planning en control, Belastingen, Vastgoed, Grondbedrijf.\n\n\n=== Gemeenteraad ===\nVerkiezingsuitslag gemeenteraad sinds 2006:\n\n\n=== Stedenbanden ===\n\nAlmelo heeft een stedenband met de volgende steden:\n\n Preston (Verenigd Koninkrijk), sinds 1948. Er is ook een all-in hotel/uitgaanscentrum vernoemd naar deze stad, genaamd Preston Palace.\n Iserlohn (Duitsland), sinds 1954\n Denizli (Turkije), sinds 1975.De vriendschappelijke betrekkingen met het Turkse Denizli zijn op 16 maart 2017 door de Turkse overheid be\u00ebindigd.\n\n\n== Bekende Almelo\u00ebrs ==\n\n\n== Wapen ==\nIn azuur drie ruiten van zilver; het schild gedekt met een gouden kroon met vijf bladeren en gehouden door twee leeuwen in natuurlijke kleur getongd van keel. Stad Amelo voerde dit wapen reeds eind 14e eeuw. Van 1815 tot 1954 waren de zilveren ruiten abusievelijk van goud.Het wapen van de Gemeente Almelo wordt ook wel De dree drupkens genoemd.\n\n\n== Vernoeming ==\nDe plaats New Almelo in de Amerikaanse staat Kansas is vernoemd naar Almelo.\n\n\n== Aangrenzende gemeenten ==\n\n\n== Externe link ==\nOffici\u00eble website"}}}}

**The first api works and second doesn't ....**
