### ISSUE TITLE
Slack account 

### ISSUE THREAD

**Issue by godfather2** [project-travel-mate/Travel-Mate#818]
The link to your slack account is no longer active. Could anyone please update it? This looks like a cool project. I would love to contribute to it and get in touch with the team

**Comment by prabhakar267** [comment]
@godfather2 We don't use Slack anymore. You can pick up any existing issue from the repositories or create new ones if you want to add a new feature. 
If you want to reach out to us about anything, please feel free to drop a mail at projecttravelmate.github.io@gmail.com
Will update the README for same.
