### ISSUE TITLE
Unequal height list items on home page

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#82]
The items in the 3rd row have the different height than the first two.
![device-2018-06-15-111648](https://user-images.githubusercontent.com/9164477/41452072-b133fc54-708d-11e8-9107-b3a84c1b975e.png)

**Comment by syedjahangirpeeran** [comment]
I would like to contribute to it. @Swati4star ,@prabhakar267  can you please tag all issues based on GSSoc difficulty level?

**Comment by Swati4star** [comment]
Sure. You can start working on this issue. :+1:

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/102
Thanks to @syedjahangirpeeran 👍
