### ISSUE TITLE
Unusual behaviour of list view in CityHistoryActivity [BUG]

### ISSUE THREAD

**Issue by abhinav0612** [project-travel-mate/Travel-Mate#822]
**Describe the bug**
Two issues in the CityHistoryActivity's list view.

- When an item is clicked the view is expanded but if you try to expand any other list item you have to click twice.
- If an item is expanded and the user scrolls down some other random list items will already be expanded.

**To Reproduce**
1. Go to any city Delhi, Mumbai.
2. Click on Know more about the city.
3. Click on any list item to expand it.
4. Scroll down the list.
5. See error

**Expected behavior**
Users should be able to expand any item on one click and only the item clicked should remain expanded in the list view.

**Screenshots**

**Device Information (please complete the following information):**
 - Device: [Realme XT]
 - OS: [Android 10]
 - App Version: [5.6.3]

**Would you like to work on this issue?**
Yes

**Comment by Rajnish23** [comment]
Hi, I checked the code and there is a issue causing due to reusability of ViewHolder for ListView. I would like to fix this issue. 
Should I go ahead. 
Also, I want to replace ListView with RecyclerView.

**Comment by prabhakar267** [comment]
@Rajnish23 Sure! Go ahead.
