### ISSUE TITLE
change color of White top bar in activities

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/Travel-Mate#89]
The top bar is white in colour in the following activities:
`checklist, select more of transport, train, bus, car, hotel, online shopping, real-time locator, fun facts`
change it to blue.

Reference:
A similar fix has been resolved in https://github.com/project-travel-mate/Travel-Mate/issues/64.

**Comment by syedjahangirpeeran** [comment]
I would like to work on it!

**Comment by Swati4star** [comment]
Sure. You can start with this one.

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/103
Thanks to @syedjahangirpeeran 👍
