### ISSUE TITLE
An option to delete all completed tasks in one go

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#90]
- Give the user to delete all completed tasks with one button. 
- SnackBar for undoing it should also be made.

**Comment by brijeshshah13** [comment]
@knightcube @Swati4star Is this option to be provided as a menu item in the top right corner?

**Comment by Swati4star** [comment]
Yes

**Comment by brijeshshah13** [comment]
@Swati4star Should it be inside the drop-down menu (3 dots icon) or directly outside?

**Comment by Swati4star** [comment]
directly outside. (s this would be the only option right now)

**Comment by brijeshshah13** [comment]
@Swati4star How about we display an `AlertDialog` before deleting all the tasks instead of the `Snackbar` as it reduces the complexity of temporary storing the records of the tasks from the table.

**Comment by Swati4star** [comment]
@brijeshshah13 
1. Show the confirmation dialog before deleting the tasks
2. But, the option to undo this should also be there. and snackbar is the best option for this.

**Comment by brijeshshah13** [comment]
@Swati4star Can we divide this issue into the following sub-tasks, each of `cakewalk` level?

1. Display confirmation dialog and delete the tasks.
2. Display Snackbar to provide the Undo functionality

Because the second one is taking some time.

**Comment by knightcube** [comment]
I dont think we should do that because we this issue has the intermediate label and breaking it into two separate cakewalk issues would ultimately add upto 20 points anyway.

**Comment by brijeshshah13** [comment]
@knightcube I agree. But the second requires some time, however, the first one I've already implemented. We can atleast that functionality right away.

**Comment by Swati4star** [comment]
I agree with @knightcube 
Take your time & implement both the functionalities together.

**Comment by knightcube** [comment]
Are you workingb

**Comment by brijeshshah13** [comment]
@knightcube I already working on an another one. It's up for grabs 👍

**Comment by aayushinigam** [comment]
Delete as in vanish the list completely or just mark them as done and list is still visible?

**Comment by aayushinigam** [comment]
Taking this up!
