### ISSUE TITLE
Give a rich preview of the links that open up in the browser straight away

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#92]
On clicking the hash tags give a rich preview of the URL like WhatsApp before opening it on the browser or the twitter app.
![screenshot_20180619-074937 2](https://user-images.githubusercontent.com/22871961/41572483-aed5dfe4-7395-11e8-8c17-9c7c0551aa58.png)

**Comment by knightcube** [comment]
Another work around can be fetching a set of 5 most recent tweets of a particular hashtag and displaying it to user inside the app thus increasing user engagement

**Comment by Swati4star** [comment]
This sounds better. We can come up with new UI for this. Let me think for a while, and I'll also post my suggestions here. You may too.

**Comment by Swati4star** [comment]
Will be doing this based on the new UI mockup. (https://github.com/project-travel-mate/Travel-Mate/issues/132)
