### ISSUE TITLE
Show Restaurants,Monuments, and Shopping Malls with proper icons in the map

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#93]
When selecting Monuments,Shopping,Hangout or restaurants from any city detail page there is just a map that comes up. We need some proper location markers to highlight the places that we want to show the user. Currently this is what comes up - 
![screenshot_20180625-234406](https://user-images.githubusercontent.com/22871961/41867872-f8990e4e-78d1-11e8-877d-0610dca65c88.png)

**Comment by Swati4star** [comment]
The description is not clear. @knightcube, Can you specify what you want exactly by posting some screenshots?

**Comment by knightcube** [comment]
Yes sorry for the late reply....saw your comment a little late

**Comment by knightcube** [comment]
Mc

**Comment by syedjahangirpeeran** [comment]
Actually all the places(selecting Monuments,Shopping,Hangout or restaurants from any city) are showing the same location in map.

**Comment by Swati4star** [comment]
Did you check the response from here API?

**Comment by syedjahangirpeeran** [comment]
No, but in app it is showing the same map for every city and the locate buttons aren't working.

**Comment by Swati4star** [comment]
I'll look into it & create relevant issues for the same. You can work on any other issue.
