### ISSUE TITLE
Use ViewHolders in Adapters to contain all the findViewById's

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/Travel-Mate#95]
It is always considered a best practice to actually contain all findViewByIds calls in ViewHolders. It is much more efficient than calling findViewById inside getView method of ArrayAdapter

**Comment by Swati4star** [comment]
This issue can be clubbed with https://github.com/project-travel-mate/Travel-Mate/issues/85
Whoever works on this issue should take care of both.

**Comment by amy6** [comment]
I'd like to work on this along with #85

**Comment by Swati4star** [comment]
@snufflesrea is doing this for hotels module. You can leave that module & do it for all the other modules. 👍 @amy6 
I'll mark this issue `in-progress`

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/160
