### ISSUE TITLE
Change GPS options; Instead of taking the user to settings have an option to switch on GPS there itself

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/Travel-Mate#97]
If GPS is turned off, instead of having a dialog to direct user to Settings page, instead have dialog to enable GPS there itself. 
### Reference
https://stackoverflow.com/questions/29801368/how-to-show-enable-location-dialog-like-google-maps

### Current behaviour 
![](https://user-images.githubusercontent.com/10768588/41552473-7862240c-734c-11e8-93a3-c3e74be33be9.jpeg)

### Expected behaviour
![](https://user-images.githubusercontent.com/10768588/41552623-e94fe9e2-734c-11e8-810d-245867ea9e78.jpeg)

**Comment by Pritom14** [comment]
I would like to work on this issue

**Comment by Swati4star** [comment]
Sure. Go ahead.

**Comment by Swati4star** [comment]
Yes. My bad. I didn't see that @Pritom14 was working on other tissue too. Let him work on this one this time. I'll take care of it next time

**Comment by Pritom14** [comment]
Really sorry on taking up two issues at the same time. When I submitted my earlier PR, I didn't check the travis error, so took up this issue. Will try to careful next time

**Comment by Swati4star** [comment]
👍 
You can start with this issue now. @Pritom14
