### ISSUE TITLE
Have a "report a bug" tab in the app

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/Travel-Mate#98]
In the side panel, have a tab where user can report a bug.
To start with, it should have a text box, where user can type in his issue and then make a POST request to server

**Comment by Niranjan-B** [comment]
I can take this up. I would have written the API as well if it was a Node Server.

**Comment by prabhakar267** [comment]
@Niranjan-B  (un)fortunately it's in Django (Python)

**Comment by Niranjan-B** [comment]
@prabhakar267 Haha yes. I'll write up the client code.

**Comment by Swati4star** [comment]
Create a new option in the navigation panel of 'Report a bug'. On this fragment, add 2 options : 
1. **Bug type** ( this will be a spinner : crash, feature request, other) 
2. **what's the isuue?** (A big text box for user to type the message )
**Report** : This will be a button that makes a post call (just write nothing in the API link right now.. We'll add the API link when it's ready)

**Comment by prabhakar267** [comment]
@Swati4star we can have a shared (between client and server) enum for `bug_type`

**Comment by Swati4star** [comment]
Sure. Just specify the bug_type enum values here.

**Comment by Niranjan-B** [comment]
I had a query w.r.t to the POST req params. I'm assuming the "feedback id" and "created date" would be taken care by the server code?

**Comment by Swati4star** [comment]
Yes. These parameters will be taken care of by the server only.

**Comment by Swati4star** [comment]
@Niranjan-B Are you working on it?

**Comment by Swati4star** [comment]
Fixed by https://github.com/project-travel-mate/Travel-Mate/pull/146 👍
