### ISSUE TITLE
Don't make an API call for add-friend when no user is selected

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/Travel-Mate#99]
If we do not have any user selected on the trip, and click on `Add new friend`, we get this kind of response. Instead we should not be making this particular API call.

![](https://user-images.githubusercontent.com/10768588/41553626-f1515bfa-734f-11e8-8b7c-6e2905b0bf54.jpeg)

**Comment by Swati4star** [comment]
Fixed in 9b76f2931a8bb963053c27d3124b2deed1152a59 👍
